compiler:
  - clang
  - gcc
dist: trusty
env:
  - TEST_BUILD_DYNAMIC=1
  - TEST_BUILD_STATIC=1
language: cpp
notifications:
  email: false
script:
  - sh ./tools/travis-ci.sh
sudo: required

# Remember, Travis needs to be able to connect to the server so if the IRC server's dead, UPDATE the server address!
notifications:
  irc:
  - "irc.heimkoma.com#irc"

# blacklist
branches:
    - insp10
    - insp11
    - insp12
    - obsolete/insp21

# whitelist
branches:
  only:
    - master
    - insp20