# This file contains configuration for exempting known safe crawlers from the
# securelist module.

# IRC Driven (https://www.ircdriven.com)
<securehost exception="*@crawler.ircdriven.com">

# netsplit (https://netsplit.de)
<securehost exception="*@*.netsplit.de">

