# This file contains module sources for use with the Module Manager. Most users
# will not need to edit this but you can add your own sources here if your
# network has its own private modules.

[inspircd]
description = Official Third-Party Module Repository
url  = https://raw.githubusercontent.com/inspircd/inspircd-contrib/refs/heads/master/modules.lst
