.\"
.\" InspIRCd -- Internet Relay Chat Daemon
.\"
.\"   Copyright (C) 2020 Nicole Kleinhoff <ilbelkyr@shalture.org>
.\"   Copyright (C) 2014, 2018, 2020, 2022 Sadie Powell <sadie@witchery.services>
.\"
.\" This file is part of InspIRCd.  InspIRCd is free software: you can
.\" redistribute it and/or modify it under the terms of the GNU General Public
.\" License as published by the Free Software Foundation, version 2.
.\"
.\" This program is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\" FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\" details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"


.TH "InspIRCd" "1" "2020-09-26" "InspIRCd @VERSION_FULL@" "InspIRCd Manual"

.SH "NAME"
\t\fBInspIRCd\fR - \fIthe\fR stable, high-performance and modular Internet Relay Chat Daemon
.BR

.SH "SYNOPSIS"
\t\fBinspircd-genssl\fR [ auto | gnutls | openssl ] [ SSL-DIR ]

.SH "OPTIONS"
.TP
.B "auto"
.br
Looks for both GnuTLS and OpenSSL and uses the first one which is available for certificate generation.
.TP
.B "gnutls"
.br
Generates certificates using GnuTLS.
.TP
.br
.B "openssl"
Generates certificates using OpenSSL.

.SH "SUPPORT"
IRC support for InspIRCd can be found at ircs://irc.inspircd.org/inspircd.

Bug reports and feature requests can be filed at https://github.com/inspircd/inspircd/issues.
