.\"
.\" InspIRCd -- Internet Relay Chat Daemon
.\"
.\"   Copyright (C) 2014 Peter Powell <petpow@saberuk.com>
.\"
.\" This file is part of InspIRCd.  InspIRCd is free software: you can
.\" redistribute it and/or modify it under the terms of the GNU General Public
.\" License as published by the Free Software Foundation, version 2.
.\"
.\" This program is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
.\" FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
.\" details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"


.TH "InspIRCd" "1" "June 2014" "InspIRCd @VERSION_FULL@" "InspIRCd Manual"

.SH "NAME"
\t\fBInspIRCd\fR - \fIthe\fR stable, high-performance and modular Internet Relay Chat Daemon
.BR

.SH "SYNOPSIS"
\t\fBinspircd\fR [--config <file>] [--debug] [--nofork] [--nolog] [--runasroot] [--version] 

.SH "OPTIONS"
.TP
.B "--config <file>"
.br
Sets the path to the main configuration file. Defaults to \fI@CONFIG_DIR@/inspircd.conf\fR.
.TP
.B "--debug"
.br
Log verbosely to the standard output stream.
.TP
.B "--nofork"
.br
Don't fork into the background after starting up.
.TP
.B "--nolog"
.br
Don't write to log files.
.TP
.B "--runasroot"
.br
Allow the server to start as root (not recommended).
.TP
.B "--version"
.br
Displays the InspIRCd version and exits.

.SH "EXIT STATUS"
.TP
.B "0 (EXIT_STATUS_NOERROR)"
.br
The server exited cleanly.
.TP
.B "1 (EXIT_STATUS_DIE)"
.br
The server exited because the DIE command was executed.
.TP
.B "2 (EXIT_STATUS_CONFIG)"
.br
The server exited because of a configuration file error.
.TP
.B "3 (EXIT_STATUS_LOG)"
.br
The server exited because of a log file error.
.TP
.B "4 (EXIT_STATUS_FORK)"
.br
The server exited because it was unable to fork into the background.
.TP
.B "5 (EXIT_STATUS_ARGV)"
.br
The server exited because an invalid argument was passed to it on the command line.
.TP
.B "6 (EXIT_STATUS_PID)"
.br
The server exited because it was unable to write to the PID file.
.TP
.B "7 (EXIT_STATUS_SOCKETENGINE)"
.br
The server exited because it was unable to initialize the @SOCKETENGINE@ socket engine.
.TP
.B "8 (EXIT_STATUS_ROOT)"
.br
The server exited because the user tried to start as root without \fI--runasroot\fR.
.TP
.B "9 (EXIT_STATUS_MODULE)"
.br
The server exited because it was unable to load a module on first run.
.TP
.B "10 (EXIT_STATUS_SIGTERM)"
.br
The server exited because it received SIGTERM.

.SH "SUPPORT"
IRC support for InspIRCd can be found at irc://irc.inspircd.org/inspircd.

Bug reports and feature requests can be filed at https://github.com/inspircd/inspircd/issues.
