.TH "/home/brain/inspircd-cvs/inspircd/ Directory Reference" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/brain/inspircd-cvs/inspircd/ Directory Reference \- 
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
