.TH "/home/brain/inspircd-cvs/inspircd/src/ Directory Reference" 3 "12 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/brain/inspircd-cvs/inspircd/src/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchannels.cpp\fP"
.br
.ti -1c
.RI "file \fBmodules.cpp\fP"
.br
.ti -1c
.RI "file \fBsocket.cpp\fP"
.br
.ti -1c
.RI "file \fBsocketengine.cpp\fP"
.br
.ti -1c
.RI "file \fBusers.cpp\fP"
.br
.in -1c
