.TH "Admin" 3 "30 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Admin \- Holds /ADMIN data This class contains the admin details of the local server.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <modules.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdmin\fP (std::string name, std::string email, std::string nick)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::string \fBName\fP"
.br
.ti -1c
.RI "const std::string \fBEmail\fP"
.br
.ti -1c
.RI "const std::string \fBNick\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds /ADMIN data This class contains the admin details of the local server. 

It is constructed by class \fBServer\fP, and has three read-only values, Name, Email and Nick that contain the specified values for the server where the module is running. 
.PP
Definition at line 123 of file modules.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Admin::Admin (std::string name, std::string email, std::string nick)"
.PP
Definition at line 249 of file modules.cpp.
.PP
.nf
249 : Name(name), Email(email), Nick(nick) { };
.fi
.SH "Member Data Documentation"
.PP 
.SS "const std::string \fBAdmin::Email\fP"
.PP
Definition at line 126 of file modules.h.
.SS "const std::string \fBAdmin::Name\fP"
.PP
Definition at line 126 of file modules.h.
.SS "const std::string \fBAdmin::Nick\fP"
.PP
Definition at line 126 of file modules.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
