.TH "Admin" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Admin \- Holds /ADMIN data This class contains the admin details of the local server.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <modules.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdmin\fP (\fBstd::string\fP name, \fBstd::string\fP email, \fBstd::string\fP nick)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBstd::string\fP \fBName\fP"
.br
.ti -1c
.RI "const \fBstd::string\fP \fBEmail\fP"
.br
.ti -1c
.RI "const \fBstd::string\fP \fBNick\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds /ADMIN data This class contains the admin details of the local server. 

It is constructed by class \fBServer\fP, and has three read-only values, Name, Email and Nick that contain the specified values for the server where the module is running.
.PP
Definition at line 125 of file modules.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Admin::Admin (\fBstd::string\fP name, \fBstd::string\fP email, \fBstd::string\fP nick)"
.PP
Definition at line 163 of file modules.cpp.
.PP
.nf
163 : Name(name), Email(email), Nick(nick) { };
.fi
.PP
.SH "Member Data Documentation"
.PP 
.SS "const \fBstd::string\fP \fBAdmin::Email\fP"
.PP
Definition at line 128 of file modules.h.
.SS "const \fBstd::string\fP \fBAdmin::Name\fP"
.PP
Definition at line 128 of file modules.h.
.SS "const \fBstd::string\fP \fBAdmin::Nick\fP"
.PP
Definition at line 128 of file modules.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
