.TH "aes.h" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aes.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAES\fP"
.br
.RI "\fIThe AES class is a utility class for use in modules and the core for encryption of data. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBto64frombits\fP (unsigned char *out, const unsigned char *in, int inlen)"
.br
.RI "\fIConvert from binary to base64. \fP"
.ti -1c
.RI "int \fBfrom64tobits\fP (char *out, const char *in, int maxlen)"
.br
.RI "\fIConvert from base64 to binary  Output  Input  Size of output buffer. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int from64tobits (char * out, const char * in, int maxlen)"
.PP
Convert from base64 to binary  Output  Input  Size of output buffer. 
.PP
\fBReturns:\fP
.RS 4
Number of bytes actually converted
.RE
.PP

.SS "void to64frombits (unsigned char * out, const unsigned char * in, int inlen)"
.PP
Convert from binary to base64. 
.PP
\fBParameters:\fP
.RS 4
\fIout\fP Output 
.br
\fIin\fP Input 
.br
\fIinlen\fP Number of bytes in input buffer
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
