.TH "base.h" 3 "13 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBclassbase\fP"
.br
.RI "\fIThe base class for all inspircd classes. \fP"
.ti -1c
.RI "class \fBExtensible\fP"
.br
.RI "\fIclass Extensible is the parent class of many classes such as userrec and chanrec. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBVoidPointer\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBVoidPointer\fP"
.PP
Definition at line 25 of file base.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
