.TH "base.h" 3 "30 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBBoolSet\fP"
.br
.RI "\fIBoolSet is a utility class designed to hold eight bools in a bitmask. \fP"
.ti -1c
.RI "class \fBclassbase\fP"
.br
.RI "\fIThe base class for all inspircd classes. \fP"
.ti -1c
.RI "class \fBExtensible\fP"
.br
.RI "\fIclass Extensible is the parent class of many classes such as userrec and chanrec. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBVoidPointer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBbitfields\fP [] = {1,2,4,8,16,32,64,128}"
.br
.ti -1c
.RI "const int \fBinverted_bitfields\fP [] = {~1,~2,~4,~8,~16,~32,~64,~128}"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBVoidPointer\fP"
.PP
Definition at line 25 of file base.h.
.SH "Variable Documentation"
.PP 
.SS "const int \fBbitfields\fP[] = {1,2,4,8,16,32,64,128}"
.PP
Definition at line 91 of file base.h.
.SS "const int \fBinverted_bitfields\fP[] = {~1,~2,~4,~8,~16,~32,~64,~128}"
.PP
Definition at line 92 of file base.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
