channels.cpp
NAME
channels.cpp -
SYNOPSIS
#include 'inspircd_config.h'
#include 'inspircd.h'
#include 'inspircd_io.h'
#include <unistd.h>
#include <sys/errno.h>
#include <sys/ioctl.h>
#include <sys/utsname.h>
#include <time.h>
#include <string>
#include <hash_map>
#include <map>
#include <sstream>
#include <vector>
#include <deque>
#include 'users.h'
#include 'ctables.h'
#include 'globals.h'
#include 'modules.h'
#include 'dynamic.h'
#include 'commands.h'
#include 'wildcard.h'
#include 'message.h'
#include 'mode.h'
#include 'xline.h'
#include 'inspstring.h'
#include 'helperfuncs.h'
#include 'typedefs.h'
Namespaces
namespace std
Defines
#define nspace std
Functions
chanrec * ForceChan (chanrec *Ptr, ucrec &a, userrec *user, int created)
chanrec * add_channel (userrec *user, const char *cn, const char *key, bool override)
chanrec * del_channel (userrec *user, const char *cname, const char *reason, bool local)
void kick_channel (userrec *src, userrec *user, chanrec *Ptr, char *reason)
Variables
ServerConfig * Config
int MODCOUNT = -1
std::vector< Module * > modules
std::vector< ircd_module * > factory
int WHOWAS_STALE
int WHOWAS_MAX
time_t TIME
chan_hash chanlist
std::vector< ModeParameter > custom_mode_params
Define Documentation
#define nspace std
Definition at line 54 of file channels.cpp.
Function Documentation
chanrec* add_channel (userrec * user, const char * cn, const char * key, bool override)
Definition at line 194 of file channels.cpp.
References chanrec::bans, chanrec::binarymodes, chanlist, userrec::chans, CM_INVITEONLY, CM_NOEXTERNAL, CM_TOPICLOCK, DEBUG, DEFAULT, connection::fd, FindChan(), ForceChan(), FOREACH_RESULT, userrec::GetFullHost(), has_channel(), userrec::IsInvited(), chanrec::key, chanrec::limit, log(), userrec::modes, chanrec::name, userrec::nick, userrec::RemoveInvite(), TIME, and WriteServ().
Referenced by Server::JoinUserToChannel().
{
        if ((!user) || (!cn))
        {
                log(DEFAULT,'*** BUG *** add_channel was given an invalid parameter');
                return 0;
        }
        int created = 0;
        char cname[MAXBUF];
        int MOD_RESULT = 0;
        strncpy(cname,cn,CHANMAX);
        log(DEBUG,'add_channel: %s %s',user->nick,cname);
        chanrec* Ptr = FindChan(cname);
        if (!Ptr)
        {
                if (user->fd > -1)
                {
                        MOD_RESULT = 0;
                        FOREACH_RESULT(OnUserPreJoin(user,NULL,cname));
                        if (MOD_RESULT == 1)
                                return NULL;
                }
                /* create a new one */
                chanlist[cname] = new chanrec();
                strlcpy(chanlist[cname]->name, cname,CHANMAX);
                chanlist[cname]->binarymodes = CM_TOPICLOCK | CM_NOEXTERNAL;
                chanlist[cname]->created = TIME;
                strcpy(chanlist[cname]->topic, '');
                strncpy(chanlist[cname]->setby, user->nick,NICKMAX);
                chanlist[cname]->topicset = 0;
                Ptr = chanlist[cname];
                log(DEBUG,'add_channel: created: %s',cname);
                /* set created to 2 to indicate user
                 * is the first in the channel
                 * and should be given ops */
                created = 2;
        }
        else
        {
                /* Already on the channel */
                if (has_channel(user,Ptr))
                        return NULL;
                // remote users are allowed us to bypass channel modes
                // and bans (used by servers)
                if (user->fd > -1)
                {
                        MOD_RESULT = 0;
                        FOREACH_RESULT(OnUserPreJoin(user,Ptr,cname));
                        if (MOD_RESULT == 1)
                        {
                                return NULL;
                        }
                        else
                        {
                                if (*Ptr->key)
                                {
                                        MOD_RESULT = 0;
                                        FOREACH_RESULT(OnCheckKey(user, Ptr, key ? key : ''));
                                        if (!MOD_RESULT)
                                        {
                                                if (!key)
                                                {
                                                        log(DEBUG,'add_channel: no key given in JOIN');
                                                        WriteServ(user->fd,'475 %s %s :Cannot join channel (Requires key)',user->nick, Ptr->name);
                                                        return NULL;
                                                }
                                                else
                                                {
                                                        if (strcasecmp(key,Ptr->key))
                                                        {
                                                                log(DEBUG,'add_channel: bad key given in JOIN');
                                                                WriteServ(user->fd,'475 %s %s :Cannot join channel (Incorrect key)',user->nick, Ptr->name);
                                                                return NULL;
                                                        }
                                                }
                                        }
                                }
                                if (Ptr->binarymodes & CM_INVITEONLY)
                                {
                                        MOD_RESULT = 0;
                                        irc::string xname(Ptr->name);
                                        FOREACH_RESULT(OnCheckInvite(user, Ptr));
                                        if (!MOD_RESULT)
                                        {
                                                log(DEBUG,'add_channel: channel is +i');
                                                if (user->IsInvited(xname))
                                                {
                                                        /* user was invited to channel */
                                                        /* there may be an optional channel NOTICE here */
                                                }
                                                else
                                                {
                                                        WriteServ(user->fd,'473 %s %s :Cannot join channel (Invite only)',user->nick, Ptr->name);
                                                        return NULL;
                                                }
                                        }
                                        user->RemoveInvite(xname);
                                }
                                if (Ptr->limit)
                                {
                                        MOD_RESULT = 0;
                                        FOREACH_RESULT(OnCheckLimit(user, Ptr));
                                        if (!MOD_RESULT)
                                        {
                                                if (usercount(Ptr) >= Ptr->limit)
                                                {
                                                        WriteServ(user->fd,'471 %s %s :Cannot join channel (Channel is full)',user->nick, Ptr->name);
                                                        return NULL;
                                                }
                                        }
                                }
                                if (Ptr->bans.size())
                                {
                                        log(DEBUG,'add_channel: about to walk banlist');
                                        MOD_RESULT = 0;
                                        FOREACH_RESULT(OnCheckBan(user, Ptr));
                                        if (!MOD_RESULT)
                                        {
                                                for (BanList::iterator i = Ptr->bans.begin(); i != Ptr->bans.end(); i++)
                                                {
                                                        if (match(user->GetFullHost(),i->data))
                                                        {
                                                                WriteServ(user->fd,'474 %s %s :Cannot join channel (You're banned)',user->nick, Ptr->name);
                                                                return NULL;
                                                        }
                                                }
                                        }
                                }
                        }
                }
                else
                {
                        log(DEBUG,'Overridden checks');
                }
                created = 1;
        }
        log(DEBUG,'Passed channel checks');
        for (unsigned int index =0; index < user->chans.size(); index++)
        {
                if (user->chans[index].channel == NULL)
                {
                        return ForceChan(Ptr,user->chans[index],user,created);
                }
        }
        /* XXX: If the user is an oper here, we can just extend their user->chans vector by one
         * and put the channel in here. Same for remote users which are not bound by
         * the channel limits. Otherwise, nope, youre boned.
         */
        if (user->fd < 0)
        {
                ucrec a;
                chanrec* c = ForceChan(Ptr,a,user,created);
                user->chans.push_back(a);
                return c;
        }
        else if (strchr(user->modes,'o'))
        {
                /* Oper allows extension up to the OPERMAXCHANS value */
                if (user->chans.size() < OPERMAXCHANS)
                {
                        ucrec a;
                        chanrec* c = ForceChan(Ptr,a,user,created);
                        user->chans.push_back(a);
                        return c;
                }
        }
        log(DEBUG,'add_channel: user channel max exceeded: %s %s',user->nick,cname);
        WriteServ(user->fd,'405 %s %s :You are on too many channels',user->nick, cname);
        return NULL;
}
chanrec* del_channel (userrec * user, const char * cname, const char * reason, bool local)
Definition at line 401 of file channels.cpp.
References chanlist, userrec::chans, DEBUG, DEFAULT, chanrec::DelUser(), FindChan(), FOREACH_MOD, log(), chanrec::name, userrec::nick, and WriteChannel().
Referenced by Server::PartUserFromChannel().
{
        if ((!user) || (!cname))
        {
                log(DEFAULT,'*** BUG *** del_channel was given an invalid parameter');
                return NULL;
        }
        chanrec* Ptr = FindChan(cname);
        if (!Ptr)
                return NULL;
        FOREACH_MOD OnUserPart(user,Ptr);
        log(DEBUG,'del_channel: removing: %s %s',user->nick,Ptr->name);
        for (unsigned int i =0; i < user->chans.size(); i++)
        {
                /* zap it from the channel list of the user */
                if (user->chans[i].channel == Ptr)
                {
                        if (reason)
                        {
                                WriteChannel(Ptr,user,'PART %s :%s',Ptr->name, reason);
                        }
                        else
                        {
                                WriteChannel(Ptr,user,'PART :%s',Ptr->name);
                        }
                        user->chans[i].uc_modes = 0;
                        user->chans[i].channel = NULL;
                        log(DEBUG,'del_channel: unlinked: %s %s',user->nick,Ptr->name);
                        break;
                }
        }
        Ptr->DelUser((char*)user);
        /* if there are no users left on the channel */
        if (!usercount(Ptr))
        {
                chan_hash::iterator iter = chanlist.find(Ptr->name);
                log(DEBUG,'del_channel: destroying channel: %s',Ptr->name);
                /* kill the record */
                if (iter != chanlist.end())
                {
                        log(DEBUG,'del_channel: destroyed: %s',Ptr->name);
                        delete Ptr;
                        chanlist.erase(iter);
                }
        }
        return NULL;
}
chanrec * ForceChan (chanrec * Ptr, ucrec & a, userrec * user, int created)
Definition at line 372 of file channels.cpp.
References chanrec::AddUser(), ucrec::channel, DEBUG, FOREACH_MOD, log(), chanrec::name, chanrec::setby, chanrec::topic, chanrec::topicset, ucrec::uc_modes, UCMODE_OP, WriteChannel(), and WriteServ().
Referenced by add_channel().
{
        if (created == 2)
        {
                /* first user in is given ops */
                a.uc_modes = UCMODE_OP;
        }
        else
        {
                a.uc_modes = 0;
        }
        a.channel = Ptr;
        Ptr->AddUser((char*)user);
        WriteChannel(Ptr,user,'JOIN :%s',Ptr->name);
        log(DEBUG,'Sent JOIN to client');
        if (Ptr->topicset)
        {
                WriteServ(user->fd,'332 %s %s :%s', user->nick, Ptr->name, Ptr->topic);
                WriteServ(user->fd,'333 %s %s %s %lu', user->nick, Ptr->name, Ptr->setby, (unsigned long)Ptr->topicset);
        }
        userlist(user,Ptr);
        WriteServ(user->fd,'366 %s %s :End of /NAMES list.', user->nick, Ptr->name);
        FOREACH_MOD OnUserJoin(user,Ptr);
        return Ptr;
}
void kick_channel (userrec * src, userrec * user, chanrec * Ptr, char * reason)
Definition at line 459 of file channels.cpp.
References AC_KICK, ACR_DEFAULT, ACR_DENY, chanlist, userrec::chans, cstatus(), DEBUG, DEFAULT, chanrec::DelUser(), connection::fd, FOREACH_MOD, FOREACH_RESULT, has_channel(), is_uline(), log(), chanrec::name, userrec::nick, userrec::server, STATUS_HOP, WriteChannel(), and WriteServ().
{
        if ((!src) || (!user) || (!Ptr) || (!reason))
        {
                log(DEFAULT,'*** BUG *** kick_channel was given an invalid parameter');
                return;
        }
        if ((!Ptr) || (!user) || (!src))
        {
                return;
        }
        log(DEBUG,'kick_channel: removing: %s %s %s',user->nick,Ptr->name,src->nick);
        if (!has_channel(user,Ptr))
        {
                WriteServ(src->fd,'441 %s %s %s :They are not on that channel',src->nick, user->nick, Ptr->name);
                return;
        }
        int MOD_RESULT = 0;
        FOREACH_RESULT(OnAccessCheck(src,user,Ptr,AC_KICK));
        if ((MOD_RESULT == ACR_DENY) && (!is_uline(src->server)))
                return;
        if ((MOD_RESULT == ACR_DEFAULT) || (!is_uline(src->server)))
        {
                if ((cstatus(src,Ptr) < STATUS_HOP) || (cstatus(src,Ptr) < cstatus(user,Ptr)))
                {
                        if (cstatus(src,Ptr) == STATUS_HOP)
                        {
                                WriteServ(src->fd,'482 %s %s :You must be a channel operator',src->nick, Ptr->name);
                        }
                        else
                        {
                                WriteServ(src->fd,'482 %s %s :You must be at least a half-operator to change modes on this channel',src->nick, Ptr->name);
                        }
                        return;
                }
        }
        if (!is_uline(src->server))
        {
                MOD_RESULT = 0;
                FOREACH_RESULT(OnUserPreKick(src,user,Ptr,reason));
                if (MOD_RESULT)
                        return;
        }
        FOREACH_MOD OnUserKick(src,user,Ptr,reason);
        for (unsigned int i =0; i < user->chans.size(); i++)
        {
                /* zap it from the channel list of the user */
                if (user->chans[i].channel)
                if (!strcasecmp(user->chans[i].channel->name,Ptr->name))
                {
                        WriteChannel(Ptr,src,'KICK %s %s :%s',Ptr->name, user->nick, reason);
                        user->chans[i].uc_modes = 0;
                        user->chans[i].channel = NULL;
                        log(DEBUG,'del_channel: unlinked: %s %s',user->nick,Ptr->name);
                        break;
                }
        }
        Ptr->DelUser((char*)user);
        /* if there are no users left on the channel */
        if (!usercount(Ptr))
        {
                chan_hash::iterator iter = chanlist.find(Ptr->name);
                log(DEBUG,'del_channel: destroying channel: %s',Ptr->name);
                /* kill the record */
                if (iter != chanlist.end())
                {
                        log(DEBUG,'del_channel: destroyed: %s',Ptr->name);
                        delete Ptr;
                        chanlist.erase(iter);
                }
        }
}
Variable Documentation
chan_hash chanlist
Referenced by add_channel(), del_channel(), and kick_channel().
ServerConfig* Config
std::vector<ModeParameter> custom_mode_params
Definition at line 69 of file channels.cpp.
Referenced by chanrec::GetModeParameter(), and chanrec::SetCustomModeParam().
std::vector<ircd_module*> factory
int MODCOUNT = -1
Definition at line 934 of file modules.cpp.
Referenced by Server::FindModule().
std::vector<Module*> modules
Referenced by Server::FindModule().
time_t TIME
Referenced by add_channel(), AddClient(), AddWhoWas(), FullConnectUser(), and userrec::userrec().
int WHOWAS_MAX
Referenced by AddWhoWas().
int WHOWAS_STALE
Referenced by AddWhoWas().
Author
Generated automatically by Doxygen for InspIRCd from the source code.