.TH "classbase" 3 "28 Mar 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
classbase \- The base class for all inspircd classes.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <base.h>\fP
.PP
Inherited by \fBAdmin\fP, \fBConfigReader\fP, \fBConnectClass\fP, \fBExtensible\fP, \fBExtMode\fP, \fBFileReader\fP, \fBHostItem\fP, \fBInvited\fP, \fBModeParameter\fP, \fBModule\fP, \fBModuleFactory\fP, \fBpacket\fP, \fBServer\fP, \fBucrec\fP, \fBVersion\fP, and \fBXLine\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBclassbase\fP ()"
.br
.RI "\fIConstructor, Sets the object's time. \fP"
.ti -1c
.RI "\fB~classbase\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBage\fP"
.br
.RI "\fITime that the object was instantiated (used for TS calculation etc). \fP"
.in -1c
.SH "Detailed Description"
.PP 
The base class for all inspircd classes. Definition at line 29 of file base.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "classbase::classbase ()\fC [inline]\fP"
.PP
Constructor, Sets the object's time. Definition at line 39 of file base.h.
.PP
References age.
.PP
.nf
39 { age = time(NULL); }
.fi
.SS "classbase::~\fBclassbase\fP ()\fC [inline]\fP"
.PP
Definition at line 40 of file base.h.
.PP
.nf
40 { }
.fi
.SH "Member Data Documentation"
.PP 
.SS "time_t \fBclassbase::age\fP"
.PP
Time that the object was instantiated (used for TS calculation etc). Definition at line 34 of file base.h.
.PP
Referenced by classbase().

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
