.TH "command_t" 3 "20 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_t \- A structure that defines a command.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ctables.h>\fP
.PP
Inherits \fBExtensible\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcommand\fP [MAXBUF]"
.br
.RI "\fICommand name. \fP"
.ti -1c
.RI "handlerfunc * \fBhandler_function\fP"
.br
.RI "\fIHandler function as in typedef. \fP"
.ti -1c
.RI "char \fBflags_needed\fP"
.br
.RI "\fIUser flags needed to execute the command or 0. \fP"
.ti -1c
.RI "int \fBmin_params\fP"
.br
.RI "\fIMinimum number of parameters command takes. \fP"
.ti -1c
.RI "long \fBuse_count\fP"
.br
.RI "\fIused by /stats m \fP"
.ti -1c
.RI "long \fBtotal_bytes\fP"
.br
.RI "\fIused by /stats m \fP"
.ti -1c
.RI "char \fBsource\fP [MAXBUF]"
.br
.RI "\fIused for resource tracking between modules \fP"
.in -1c
.SH "Detailed Description"
.PP 
A structure that defines a command. Definition at line 26 of file ctables.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBcommand_t::command\fP[MAXBUF]"
.PP
Command name. Definition at line 31 of file ctables.h.
.SS "char \fBcommand_t::flags_needed\fP"
.PP
User flags needed to execute the command or 0. Definition at line 37 of file ctables.h.
.SS "handlerfunc* \fBcommand_t::handler_function\fP"
.PP
Handler function as in typedef. Definition at line 34 of file ctables.h.
.SS "int \fBcommand_t::min_params\fP"
.PP
Minimum number of parameters command takes. Definition at line 40 of file ctables.h.
.SS "char \fBcommand_t::source\fP[MAXBUF]"
.PP
used for resource tracking between modules Definition at line 49 of file ctables.h.
.SS "long \fBcommand_t::total_bytes\fP"
.PP
used by /stats m Definition at line 46 of file ctables.h.
.SS "long \fBcommand_t::use_count\fP"
.PP
used by /stats m Definition at line 43 of file ctables.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
