.TH "commands.h" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commands.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'users.h'\fP
.br
\fC#include 'channels.h'\fP
.br
\fC#include 'cmd_admin.h'\fP
.br
\fC#include 'cmd_away.h'\fP
.br
\fC#include 'cmd_commands.h'\fP
.br
\fC#include 'cmd_connect.h'\fP
.br
\fC#include 'cmd_die.h'\fP
.br
\fC#include 'cmd_eline.h'\fP
.br
\fC#include 'cmd_gline.h'\fP
.br
\fC#include 'cmd_info.h'\fP
.br
\fC#include 'cmd_invite.h'\fP
.br
\fC#include 'cmd_ison.h'\fP
.br
\fC#include 'cmd_join.h'\fP
.br
\fC#include 'cmd_kick.h'\fP
.br
\fC#include 'cmd_kill.h'\fP
.br
\fC#include 'cmd_kline.h'\fP
.br
\fC#include 'cmd_links.h'\fP
.br
\fC#include 'cmd_list.h'\fP
.br
\fC#include 'cmd_loadmodule.h'\fP
.br
\fC#include 'cmd_lusers.h'\fP
.br
\fC#include 'cmd_map.h'\fP
.br
\fC#include 'cmd_modules.h'\fP
.br
\fC#include 'cmd_motd.h'\fP
.br
\fC#include 'cmd_names.h'\fP
.br
\fC#include 'cmd_nick.h'\fP
.br
\fC#include 'cmd_notice.h'\fP
.br
\fC#include 'cmd_oper.h'\fP
.br
\fC#include 'cmd_part.h'\fP
.br
\fC#include 'cmd_pass.h'\fP
.br
\fC#include 'cmd_ping.h'\fP
.br
\fC#include 'cmd_pong.h'\fP
.br
\fC#include 'cmd_privmsg.h'\fP
.br
\fC#include 'cmd_qline.h'\fP
.br
\fC#include 'cmd_quit.h'\fP
.br
\fC#include 'cmd_rehash.h'\fP
.br
\fC#include 'cmd_restart.h'\fP
.br
\fC#include 'cmd_rules.h'\fP
.br
\fC#include 'cmd_server.h'\fP
.br
\fC#include 'cmd_squit.h'\fP
.br
\fC#include 'cmd_stats.h'\fP
.br
\fC#include 'cmd_summon.h'\fP
.br
\fC#include 'cmd_time.h'\fP
.br
\fC#include 'cmd_topic.h'\fP
.br
\fC#include 'cmd_trace.h'\fP
.br
\fC#include 'cmd_unloadmodule.h'\fP
.br
\fC#include 'cmd_user.h'\fP
.br
\fC#include 'cmd_userhost.h'\fP
.br
\fC#include 'cmd_users.h'\fP
.br
\fC#include 'cmd_version.h'\fP
.br
\fC#include 'cmd_wallops.h'\fP
.br
\fC#include 'cmd_who.h'\fP
.br
\fC#include 'cmd_whois.h'\fP
.br
\fC#include 'cmd_whowas.h'\fP
.br
\fC#include 'cmd_zline.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBCleanFilename\fP (char *name)"
.br
.ti -1c
.RI "bool \fBis_uline\fP (const char *server)"
.br
.ti -1c
.RI "long \fBduration\fP (const char *str)"
.br
.ti -1c
.RI "void \fBdo_whois\fP (\fBuserrec\fP *user, \fBuserrec\fP *dest, unsigned long signon, unsigned long idle, char *nick)"
.br
.ti -1c
.RI "bool \fBhost_matches_everyone\fP (\fBstd::string\fP mask, \fBuserrec\fP *user)"
.br
.ti -1c
.RI "bool \fBip_matches_everyone\fP (\fBstd::string\fP ip, \fBuserrec\fP *user)"
.br
.ti -1c
.RI "bool \fBnick_matches_everyone\fP (\fBstd::string\fP nick, \fBuserrec\fP *user)"
.br
.ti -1c
.RI "int \fBoperstrcmp\fP (char *data, char *input)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* CleanFilename (char * name)"
.PP
.SS "void do_whois (\fBuserrec\fP * user, \fBuserrec\fP * dest, unsigned long signon, unsigned long idle, char * nick)"
.PP
.SS "long duration (const char * str)"
.PP
Referenced by Server::CalcDuration().
.SS "bool host_matches_everyone (\fBstd::string\fP mask, \fBuserrec\fP * user)"
.PP
.SS "bool ip_matches_everyone (\fBstd::string\fP ip, \fBuserrec\fP * user)"
.PP
.SS "bool is_uline (const char * server)"
.PP
Referenced by userrec::HasPermission(), Server::IsUlined(), and kick_channel().
.SS "bool nick_matches_everyone (\fBstd::string\fP nick, \fBuserrec\fP * user)"
.PP
.SS "int operstrcmp (char * data, char * input)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
