ConfigReader
NAME
ConfigReader - Allows reading of values from configuration files This class allows a module to read from either the main configuration file (inspircd.conf) or from a module-specified configuration file.
SYNOPSIS
#include <modules.h>
Inherits classbase.
Public Member Functions
ConfigReader ()
Default constructor.
ConfigReader (std::string filename)
Overloaded constructor.
~ConfigReader ()
Default destructor.
std::string ReadValue (std::string tag, std::string name, int index)
Retrieves a value from the config file.
bool ReadFlag (std::string tag, std::string name, int index)
Retrieves a boolean value from the config file.
long ReadInteger (std::string tag, std::string name, int index, bool needs_unsigned)
Retrieves an integer value from the config file.
long GetError ()
Returns the last error to occur.
int Enumerate (std::string tag)
Counts the number of times a given tag appears in the config file.
bool Verify ()
Returns true if a config file is valid.
void DumpErrors (bool bail, userrec *user)
Dumps the list of errors in a config file to an output location.
int EnumerateValues (std::string tag, int index)
Returns the number of items within a tag.
Protected Attributes
std::stringstream * cache
The contents of the configuration file This protected member should never be accessed by a module (and cannot be accessed unless the core is changed).
std::stringstream * errorlog
bool readerror
Used to store errors.
long error
Detailed Description
Allows reading of values from configuration files This class allows a module to read from either the main configuration file (inspircd.conf) or from a module-specified configuration file.
It may either be instantiated with one parameter or none. Constructing the class using one parameter allows you to specify a path to your own configuration file, otherwise, inspircd.conf is read.
Definition at line 1529 of file modules.h.
Constructor & Destructor Documentation
ConfigReader::ConfigReader ()
Default constructor.
This constructor initialises the ConfigReader class to read the inspircd.conf file as specified when running ./configure.
Definition at line 731 of file modules.cpp.
References cache, ServerConfig::ClearStack(), CONF_FILE_NOT_FOUND, error, errorlog, ServerConfig::LoadConf(), and readerror.
{
        Config->ClearStack();
        this->cache = new std::stringstream(std::stringstream::in | std::stringstream::out);
        this->errorlog = new std::stringstream(std::stringstream::in | std::stringstream::out);
        this->readerror = Config->LoadConf(CONFIG_FILE,this->cache,this->errorlog);
        if (!this->readerror)
                this->error = CONF_FILE_NOT_FOUND;
}
ConfigReader::ConfigReader (std::string filename)
Overloaded constructor.
This constructor initialises the ConfigReader class to read a user-specified config file
Definition at line 751 of file modules.cpp.
References cache, ServerConfig::ClearStack(), CONF_FILE_NOT_FOUND, error, errorlog, ServerConfig::LoadConf(), and readerror.
{
        Config->ClearStack();
        this->cache = new std::stringstream(std::stringstream::in | std::stringstream::out);
        this->errorlog = new std::stringstream(std::stringstream::in | std::stringstream::out);
        this->readerror = Config->LoadConf(filename.c_str(),this->cache,this->errorlog);
        if (!this->readerror)
                this->error = CONF_FILE_NOT_FOUND;
};
ConfigReader::~ConfigReader ()
Default destructor.
This method destroys the ConfigReader class.
Definition at line 742 of file modules.cpp.
References cache, and errorlog.
{
        if (this->cache)
                delete this->cache;
        if (this->errorlog)
                delete this->errorlog;
}
Member Function Documentation
void ConfigReader::DumpErrors (bool bail, userrec * user)
Dumps the list of errors in a config file to an output location.
If bail is true, then the program will abort. If bail is false and user points to a valid user record, the error report will be spooled to the given user by means of NOTICE. if bool is false AND user is false, the error report will be spooled to all opers by means of a NOTICE to all opers.
Definition at line 830 of file modules.cpp.
References errorlog, connection::fd, userrec::nick, WriteOpers(), and WriteServ().
{
        if (bail)
        {
                printf('There were errors in your configuration:\n%s',errorlog->str().c_str());
                exit(0);
        }
        else
        {
                char dataline[1024];
                if (user)
                {
                        WriteServ(user->fd,'NOTICE %s :There were errors in the configuration file:',user->nick);
                        while (!errorlog->eof())
                        {
                                errorlog->getline(dataline,1024);
                                WriteServ(user->fd,'NOTICE %s :%s',user->nick,dataline);
                        }
                }
                else
                {
                        WriteOpers('There were errors in the configuration file:',user->nick);
                        while (!errorlog->eof())
                        {
                                errorlog->getline(dataline,1024);
                                WriteOpers(dataline);
                        }
                }
                return;
        }
}
int ConfigReader::Enumerate (std::string tag)
Counts the number of times a given tag appears in the config file.
This method counts the number of times a tag appears in a config file, for use where there are several tags of the same kind, e.g. with opers and connect types. It can be used with the index value of ConfigReader::ReadValue to loop through all copies of a multiple instance tag.
Definition at line 863 of file modules.cpp.
References cache, and ServerConfig::EnumConf().
{
        return Config->EnumConf(cache,tag.c_str());
}
int ConfigReader::EnumerateValues (std::string tag, int index)
Returns the number of items within a tag.
For example if the tag was <test tag='blah' data='foo'> then this function would return 2. Spaces and newlines both qualify as valid seperators between values.
Definition at line 868 of file modules.cpp.
References cache, and ServerConfig::EnumValues().
{
        return Config->EnumValues(cache, tag.c_str(), index);
}
long ConfigReader::GetError ()
Returns the last error to occur.
Valid errors can be found by looking in modules.h. Any nonzero value indicates an error condition. A call to GetError() resets the error flag back to 0.
Definition at line 823 of file modules.cpp.
References error.
{
        long olderr = this->error;
        this->error = 0;
        return olderr;
}
bool ConfigReader::ReadFlag (std::string tag, std::string name, int index)
Retrieves a boolean value from the config file.
This method retrieves a boolean value from the config file. Where multiple copies of the tag exist in the config file, index indicates which of the values to retrieve. The values '1', 'yes' and 'true' in the config file count as true to ReadFlag, and any other value counts as false.
Definition at line 777 of file modules.cpp.
References cache, CONF_VALUE_NOT_FOUND, error, and ServerConfig::ReadConf().
{
        char val[MAXBUF];
        char t[MAXBUF];
        char n[MAXBUF];
        strlcpy(t,tag.c_str(),MAXBUF);
        strlcpy(n,name.c_str(),MAXBUF);
        int res = Config->ReadConf(cache,t,n,index,val);
        if (!res)
        {
                this->error = CONF_VALUE_NOT_FOUND;
                return false;
        }
        std::string s = val;
        return ((s == 'yes') || (s == 'YES') || (s == 'true') || (s == 'TRUE') || (s == '1'));
}
long ConfigReader::ReadInteger (std::string tag, std::string name, int index, bool needs_unsigned)
Retrieves an integer value from the config file.
This method retrieves an integer value from the config file. Where multiple copies of the tag exist in the config file, index indicates which of the values to retrieve. Any invalid integer values in the tag will cause the objects error value to be set, and any call to GetError() will return CONF_INVALID_NUMBER to be returned. needs_unsigned is set if the number must be unsigned. If a signed number is placed into a tag which is specified unsigned, 0 will be returned and GetError() will return CONF_NOT_UNSIGNED
Definition at line 794 of file modules.cpp.
References cache, CONF_NOT_A_NUMBER, CONF_NOT_UNSIGNED, CONF_VALUE_NOT_FOUND, error, and ServerConfig::ReadConf().
{
        char val[MAXBUF];
        char t[MAXBUF];
        char n[MAXBUF];
        strlcpy(t,tag.c_str(),MAXBUF);
        strlcpy(n,name.c_str(),MAXBUF);
        int res = Config->ReadConf(cache,t,n,index,val);
        if (!res)
        {
                this->error = CONF_VALUE_NOT_FOUND;
                return 0;
        }
        for (unsigned int i = 0; i < strlen(val); i++)
        {
                if (!isdigit(val[i]))
                {
                        this->error = CONF_NOT_A_NUMBER;
                        return 0;
                }
        }
        if ((needs_unsigned) && (atoi(val)<0))
        {
                this->error = CONF_NOT_UNSIGNED;
                return 0;
        }
        return atoi(val);
}
std::string ConfigReader::ReadValue (std::string tag, std::string name, int index)
Retrieves a value from the config file.
This method retrieves a value from the config file. Where multiple copies of the tag exist in the config file, index indicates which of the values to retrieve.
Definition at line 761 of file modules.cpp.
References cache, CONF_VALUE_NOT_FOUND, error, and ServerConfig::ReadConf().
{
        char val[MAXBUF];
        char t[MAXBUF];
        char n[MAXBUF];
        strlcpy(t,tag.c_str(),MAXBUF);
        strlcpy(n,name.c_str(),MAXBUF);
        int res = Config->ReadConf(cache,t,n,index,val);
        if (!res)
        {
                this->error = CONF_VALUE_NOT_FOUND;
                return '';
        }
        return val;
}
bool ConfigReader::Verify ()
Returns true if a config file is valid.
This method is partially implemented and will only return false if the config file does not exist or could not be opened.
Definition at line 873 of file modules.cpp.
References readerror.
{
        return this->readerror;
}
Member Data Documentation
std::stringstream* ConfigReader::cache [protected]
The contents of the configuration file This protected member should never be accessed by a module (and cannot be accessed unless the core is changed).
It will contain a pointer to the configuration file data with unneeded data (such as comments) stripped from it.
Definition at line 1537 of file modules.h.
Referenced by ConfigReader(), Enumerate(), EnumerateValues(), ReadFlag(), ReadInteger(), ReadValue(), and ~ConfigReader().
long ConfigReader::error [protected]
Definition at line 1542 of file modules.h.
Referenced by ConfigReader(), GetError(), ReadFlag(), ReadInteger(), and ReadValue().
std::stringstream* ConfigReader::errorlog [protected]
Definition at line 1538 of file modules.h.
Referenced by ConfigReader(), DumpErrors(), and ~ConfigReader().
bool ConfigReader::readerror [protected]
Used to store errors.
Definition at line 1541 of file modules.h.
Referenced by ConfigReader(), and Verify().
Author
Generated automatically by Doxygen for InspIRCd from the source code.