.TH "connection.h" 3 "9 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connection.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'base.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\fP"
.br
.RI "\fIPlease note: classes serverrec and userrec both inherit from class connection. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
