.TH "connection" 3 "12 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connection \- Please note: classes serverrec and userrec both inherit from class connection.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <connection.h>\fP
.PP
Inherits \fBExtensible\fP.
.PP
Inherited by \fBuserrec\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnection\fP ()"
.br
.RI "\fIDefault constructor. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.RI "\fIFile descriptor of the connection. \fP"
.ti -1c
.RI "char \fBhost\fP [160]"
.br
.RI "\fIHostname of connection. \fP"
.ti -1c
.RI "char \fBip\fP [16]"
.br
.RI "\fIIP of connection. \fP"
.ti -1c
.RI "int \fBbytes_in\fP"
.br
.RI "\fIStats counter for bytes inbound. \fP"
.ti -1c
.RI "int \fBbytes_out\fP"
.br
.RI "\fIStats counter for bytes outbound. \fP"
.ti -1c
.RI "int \fBcmds_in\fP"
.br
.RI "\fIStats counter for commands inbound. \fP"
.ti -1c
.RI "int \fBcmds_out\fP"
.br
.RI "\fIStats counter for commands outbound. \fP"
.ti -1c
.RI "bool \fBhaspassed\fP"
.br
.RI "\fITrue if server/user has authenticated, false if otherwise. \fP"
.ti -1c
.RI "int \fBport\fP"
.br
.RI "\fIPort number For a userrec, this is the port they connected to the network on. \fP"
.ti -1c
.RI "char \fBregistered\fP"
.br
.RI "\fIUsed by userrec to indicate the registration status of the connection. \fP"
.ti -1c
.RI "time_t \fBlastping\fP"
.br
.RI "\fITime the connection was last pinged. \fP"
.ti -1c
.RI "time_t \fBsignon\fP"
.br
.RI "\fITime the connection was created, set in the constructor. \fP"
.ti -1c
.RI "time_t \fBidle_lastmsg\fP"
.br
.RI "\fITime that the connection last sent data, used to calculate idle time. \fP"
.ti -1c
.RI "time_t \fBnping\fP"
.br
.RI "\fIUsed by PING checks with clients. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Please note: classes serverrec and userrec both inherit from class connection. 
.PP
Definition at line 37 of file connection.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "connection::connection ()\fC [inline]\fP"
.PP
Default constructor. 
.PP
Definition at line 100 of file connection.h.
.PP
References fd.
.PP
.nf
101         {
102                 this->fd = -1;
103         }
.fi
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBconnection::bytes_in\fP"
.PP
Stats counter for bytes inbound. 
.PP
Definition at line 54 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "int \fBconnection::bytes_out\fP"
.PP
Stats counter for bytes outbound. 
.PP
Definition at line 58 of file connection.h.
.PP
Referenced by userrec::FlushWriteBuf(), and userrec::userrec().
.SS "int \fBconnection::cmds_in\fP"
.PP
Stats counter for commands inbound. 
.PP
Definition at line 62 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "int \fBconnection::cmds_out\fP"
.PP
Stats counter for commands outbound. 
.PP
Definition at line 66 of file connection.h.
.PP
Referenced by userrec::FlushWriteBuf(), and userrec::userrec().
.SS "int \fBconnection::fd\fP"
.PP
File descriptor of the connection. 
.PP
Definition at line 42 of file connection.h.
.PP
Referenced by connection(), ConfigReader::DumpErrors(), Server::PseudoToUser(), Server::SendTo(), userrec::userrec(), and Server::UserToPseudo().
.SS "bool \fBconnection::haspassed\fP"
.PP
True if server/user has authenticated, false if otherwise. 
.PP
Definition at line 70 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "char \fBconnection::host\fP[160]"
.PP
Hostname of connection. 
.PP
Not used if this is a serverrec
.PP
Definition at line 46 of file connection.h.
.PP
Referenced by userrec::GetFullRealHost(), Server::PseudoToUser(), userrec::userrec(), and Server::UserToPseudo().
.SS "time_t \fBconnection::idle_lastmsg\fP"
.PP
Time that the connection last sent data, used to calculate idle time. 
.PP
Definition at line 92 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "char \fBconnection::ip\fP[16]"
.PP
IP of connection. 
.PP
Definition at line 50 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "time_t \fBconnection::lastping\fP"
.PP
Time the connection was last pinged. 
.PP
Definition at line 84 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "time_t \fBconnection::nping\fP"
.PP
Used by PING checks with clients. 
.PP
Definition at line 96 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "int \fBconnection::port\fP"
.PP
Port number For a userrec, this is the port they connected to the network on. 
.PP
For a serverrec this is the current listening port of the serverrec object.
.PP
Definition at line 76 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "char \fBconnection::registered\fP"
.PP
Used by userrec to indicate the registration status of the connection. 
.PP
Definition at line 80 of file connection.h.
.PP
Referenced by userrec::userrec().
.SS "time_t \fBconnection::signon\fP"
.PP
Time the connection was created, set in the constructor. 
.PP
Definition at line 88 of file connection.h.
.PP
Referenced by userrec::userrec().

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
