.TH "ConnectClass" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectClass \- Holds information relevent to <connect allow> and <connect deny> tags in the config file.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <users.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectClass\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBtype\fP"
.br
.RI "\fIType of line, either CC_ALLOW or CC_DENY. \fP"
.ti -1c
.RI "int \fBregistration_timeout\fP"
.br
.RI "\fIMax time to register the connection in seconds. \fP"
.ti -1c
.RI "int \fBflood\fP"
.br
.RI "\fINumber of lines in buffer before excess flood is triggered. \fP"
.ti -1c
.RI "char \fBhost\fP [MAXBUF]"
.br
.RI "\fIHost mask for this line. \fP"
.ti -1c
.RI "int \fBpingtime\fP"
.br
.RI "\fINumber of seconds between pings for this line. \fP"
.ti -1c
.RI "char \fBpass\fP [MAXBUF]"
.br
.RI "\fI(Optional) Password for this line \fP"
.ti -1c
.RI "int \fBthreshold\fP"
.br
.RI "\fIThreshold value for flood disconnect. \fP"
.ti -1c
.RI "long \fBsendqmax\fP"
.br
.RI "\fIMaximum size of sendq for users in this class (bytes). \fP"
.ti -1c
.RI "long \fBrecvqmax\fP"
.br
.RI "\fIMaximum size of recvq for users in this class (bytes). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Holds information relevent to <connect allow> and <connect deny> tags in the config file. 
.PP
Definition at line 52 of file users.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConnectClass::ConnectClass ()\fC [inline]\fP"
.PP
Definition at line 86 of file users.h.
.PP
References flood, host, pass, pingtime, recvqmax, registration_timeout, sendqmax, and threshold.
.PP
.nf
87         {
88                 registration_timeout = 0;
89                 flood = 0;
90                 pingtime = 0;
91                 threshold = 0;
92                 sendqmax = 0;
93                 recvqmax = 0;
94                 strlcpy(host,'',MAXBUF);
95                 strlcpy(pass,'',MAXBUF);
96         }
.fi
.PP
.SH "Member Data Documentation"
.PP 
.SS "int \fBConnectClass::flood\fP"
.PP
Number of lines in buffer before excess flood is triggered. 
.PP
Definition at line 63 of file users.h.
.PP
Referenced by ConnectClass().
.SS "char \fBConnectClass::host\fP[MAXBUF]"
.PP
Host mask for this line. 
.PP
Definition at line 66 of file users.h.
.PP
Referenced by ConnectClass().
.SS "char \fBConnectClass::pass\fP[MAXBUF]"
.PP
(Optional) Password for this line 
.PP
Definition at line 72 of file users.h.
.PP
Referenced by ConnectClass().
.SS "int \fBConnectClass::pingtime\fP"
.PP
Number of seconds between pings for this line. 
.PP
Definition at line 69 of file users.h.
.PP
Referenced by ConnectClass().
.SS "long \fBConnectClass::recvqmax\fP"
.PP
Maximum size of recvq for users in this class (bytes). 
.PP
Definition at line 84 of file users.h.
.PP
Referenced by ConnectClass().
.SS "int \fBConnectClass::registration_timeout\fP"
.PP
Max time to register the connection in seconds. 
.PP
Definition at line 60 of file users.h.
.PP
Referenced by ConnectClass().
.SS "long \fBConnectClass::sendqmax\fP"
.PP
Maximum size of sendq for users in this class (bytes). 
.PP
Definition at line 80 of file users.h.
.PP
Referenced by ConnectClass().
.SS "int \fBConnectClass::threshold\fP"
.PP
Threshold value for flood disconnect. 
.PP
Definition at line 76 of file users.h.
.PP
Referenced by ConnectClass().
.SS "char \fBConnectClass::type\fP"
.PP
Type of line, either CC_ALLOW or CC_DENY. 
.PP
Definition at line 57 of file users.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
