.TH "cull_list.h" 3 "15 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cull_list.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'users.h'\fP
.br
\fC#include 'channels.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCullItem\fP"
.br
.RI "\fIThe CullItem class holds a user and their quitmessage, and is used internally by the \fBCullList\fP class to compile a list of users which are to be culled when a long operation (such as a netsplit) has completed. \fP"
.ti -1c
.RI "class \fBCullList\fP"
.br
.RI "\fIThe CullList class can be used by modules, and is used by the core, to compile large lists of users in preperation to quitting them all at once. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
