.TH "dns.h" 3 "14 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dns.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBDNS\fP"
.br
.RI "\fIThe DNS class allows fast nonblocking resolution of hostnames and ip addresses. \fP"
.ti -1c
.RI "struct \fBdns_ip4list\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
