.TH "dns.h" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dns.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdns_ip4list\fP"
.br
.ti -1c
.RI "class \fBDNS\fP"
.br
.RI "\fIThe DNS class allows fast nonblocking resolution of hostnames and ip addresses. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBdns_task\fP (void *arg)"
.br
.RI "\fIThis is the handler function for multi-threaded \fBDNS\fP. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* dns_task (void * arg)"
.PP
This is the handler function for multi-threaded \fBDNS\fP. 
.PP
It cannot be a class member as pthread will not let us create a thread whos handler function is a member of a class (ugh).
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
