.TH "ELine" 3 "24 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELine \- 
.SH SYNOPSIS
.br
.PP
\fC#include <xline.h>\fP
.PP
Inherits \fBXLine\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBhostmask\fP [200]"
.br
.RI "\fIHostmask (ident) to match against May contain wildcards. \fP"
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char \fBELine::hostmask\fP[200]"
.PP
Hostmask (ident) to match against May contain wildcards. Definition at line 88 of file xline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
