.TH "ExtMode" 3 "9 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtMode \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtMode\fP (char mc, int ty, bool oper, int p_on, int p_off)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBmodechar\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "bool \fBneedsoper\fP"
.br
.ti -1c
.RI "int \fBparams_when_on\fP"
.br
.ti -1c
.RI "int \fBparams_when_off\fP"
.br
.ti -1c
.RI "bool \fBlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file modules.cpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExtMode::ExtMode (char mc, int ty, bool oper, int p_on, int p_off)\fC [inline]\fP"
.PP
Definition at line 148 of file modules.cpp.
.PP
.nf
148 : modechar(mc), type(ty), needsoper(oper), params_when_on(p_on), params_when_off(p_off) { };
.fi
.PP
.SH "Member Data Documentation"
.PP 
.SS "bool \fBExtMode::list\fP"
.PP
Definition at line 147 of file modules.cpp.
.SS "char \fBExtMode::modechar\fP"
.PP
Definition at line 142 of file modules.cpp.
.SS "bool \fBExtMode::needsoper\fP"
.PP
Definition at line 144 of file modules.cpp.
.SS "int \fBExtMode::params_when_off\fP"
.PP
Definition at line 146 of file modules.cpp.
.SS "int \fBExtMode::params_when_on\fP"
.PP
Definition at line 145 of file modules.cpp.
.SS "int \fBExtMode::type\fP"
.PP
Definition at line 143 of file modules.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
