.TH "GLine" 3 "16 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLine \- GLine class.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <xline.h>\fP
.PP
Inherits \fBXLine\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBhostmask\fP [MAXBUF]"
.br
.RI "\fIHostmask (ident) to match against May contain wildcards. \fP"
.in -1c
.SH "Detailed Description"
.PP 
GLine class. Definition at line 73 of file xline.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBGLine::hostmask\fP[MAXBUF]"
.PP
Hostmask (ident) to match against May contain wildcards. Definition at line 79 of file xline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
