globals.h
NAME
globals.h -
SYNOPSIS
#include <typeinfo>
#include <iostream>
#include <string>
#include <deque>
#include 'users.h'
#include 'channels.h'
Typedefs
typedef std::deque< std::string > file_cache
Functions
void WriteOpers (char *text,...)
void log (int level, char *text,...)
void Write (int sock, char *text,...)
void WriteServ (int sock, char *text,...)
void WriteFrom (int sock, userrec *user, char *text,...)
void WriteTo (userrec *source, userrec *dest, char *data,...)
void WriteChannel (chanrec *Ptr, userrec *user, char *text,...)
void ChanExceptSender (chanrec *Ptr, userrec *user, char *text,...)
int common_channels (userrec *u, userrec *u2)
void WriteCommon (userrec *u, char *text,...)
void WriteCommonExcept (userrec *u, char *text,...)
void WriteWallOps (userrec *source, bool local_only, char *text,...)
int isnick (const char *n)
userrec * Find (std::string nick)
chanrec * FindChan (const char *chan)
char * cmode (userrec *user, chanrec *chan)
std::string getservername ()
std::string getnetworkname ()
std::string getadminname ()
std::string getadminemail ()
std::string getadminnick ()
void readfile (file_cache &F, const char *fname)
int ModeDefiend (char c, int i)
Typedef Documentation
typedef std::deque<std::string> file_cache
Definition at line 29 of file globals.h.
Function Documentation
void ChanExceptSender (chanrec * Ptr, userrec * user, char * text, ...)
Referenced by Server::SendChannel().
char* cmode (userrec * user, chanrec * chan)
Referenced by Server::ChanMode().
int common_channels (userrec * u, userrec * u2)
Referenced by Server::CommonChannels().
userrec* Find (std::string nick)
Referenced by Server::FindNick().
chanrec* FindChan (const char * chan)
Referenced by add_channel(), del_channel(), and Server::FindChannel().
std::string getadminemail ()
std::string getadminname ()
std::string getadminnick ()
std::string getnetworkname ()
std::string getservername ()
int isnick (const char * n)
Referenced by Server::IsNick().
void log (int level, char * text, ...)
Referenced by add_channel(), AddClient(), Server::AddExtendedMode(), SocketEngine::AddFd(), AddOper(), chanrec::AddUser(), AddWhoWas(), del_channel(), DeleteOper(), SocketEngine::DelFd(), chanrec::DelUser(), ForceChan(), FullConnectUser(), InspSocket::InspSocket(), kick_channel(), kill_link(), kill_link_silent(), Server::Log(), InspSocket::Read(), ReHashNick(), userrec::RemoveInvite(), chanrec::SetCustomMode(), chanrec::SetCustomModeParam(), InspSocket::SetState(), userrec::SetWriteError(), SocketEngine::SocketEngine(), and SocketEngine::~SocketEngine().
int ModeDefiend (char c, int i)
void readfile (file_cache & F, const char * fname)
Referenced by FileReader::FileReader(), and FileReader::LoadFile().
void Write (int sock, char * text, ...)
Referenced by kill_link(), kill_link_silent(), Server::PseudoToUser(), Server::Send(), Server::SendTo(), and Server::UserToPseudo().
void WriteChannel (chanrec * Ptr, userrec * user, char * text, ...)
Referenced by del_channel(), ForceChan(), kick_channel(), and Server::SendChannel().
void WriteCommon (userrec * u, char * text, ...)
Referenced by Server::SendCommon().
void WriteCommonExcept (userrec * u, char * text, ...)
Referenced by kill_link(), kill_link_silent(), and Server::SendCommon().
void WriteFrom (int sock, userrec * user, char * text, ...)
Referenced by Server::PseudoToUser(), and Server::SendFrom().
void WriteOpers (char * text, ...)
Referenced by userrec::AddBuffer(), userrec::AddWriteBuf(), ConfigReader::DumpErrors(), FullConnectUser(), kill_link(), Server::RehashServer(), and Server::SendOpers().
void WriteServ (int sock, char * text, ...)
Referenced by add_channel(), ConfigReader::DumpErrors(), ForceChan(), FullConnectUser(), kick_channel(), Server::PseudoToUser(), and Server::SendServ().
void WriteTo (userrec * source, userrec * dest, char * data, ...)
Referenced by Server::SendTo().
void WriteWallOps (userrec * source, bool local_only, char * text, ...)
Referenced by Server::SendWallops().
Author
Generated automatically by Doxygen for InspIRCd from the source code.