.TH "hashcomp.h" 3 "25 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hashcomp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include <ext/hash_map>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBirc\fP"
.br
.ti -1c
.RI "namespace \fBnspace\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBnspace\fP   __gnu_cxx"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define nspace   __gnu_cxx"
.PP
Definition at line 44 of file hashcomp.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
