.TH "HostItem" 3 "25 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HostItem \- Holds an entry for a ban list, exemption list, or invite list.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <channels.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
Inherited by \fBBanItem\fP, \fBExemptItem\fP, and \fBInviteItem\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHostItem\fP ()"
.br
.ti -1c
.RI "virtual \fB~HostItem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBset_time\fP"
.br
.ti -1c
.RI "char \fBset_by\fP [NICKMAX]"
.br
.ti -1c
.RI "char \fBdata\fP [MAXBUF]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds an entry for a ban list, exemption list, or invite list. 

This class contains a single element in a channel list, such as a banlist. 
.PP
Definition at line 36 of file channels.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HostItem::HostItem ()\fC [inline]\fP"
.PP
Definition at line 43 of file channels.h.
.PP
.nf
43 { /* stub */ }
.fi
.SS "virtual HostItem::~\fBHostItem\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 44 of file channels.h.
.PP
.nf
44 { /* stub */ }
.fi
.SH "Member Data Documentation"
.PP 
.SS "char \fBHostItem::data\fP[MAXBUF]"
.PP
Definition at line 41 of file channels.h.
.SS "char \fBHostItem::set_by\fP[NICKMAX]"
.PP
Definition at line 40 of file channels.h.
.SS "time_t \fBHostItem::set_time\fP"
.PP
Definition at line 39 of file channels.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
