.TH "InAddr_HashComp" 3 "13 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InAddr_HashComp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const in_addr &s1, const in_addr &s2) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool InAddr_HashComp::operator() (const in_addr & s1, const in_addr & s2) const\fC [inline]\fP"
.PP
Definition at line 171 of file modules.cpp.
.PP
.nf
172         {
173                 size_t q;
174                 size_t p;
175                 
176                 memcpy(&q,&s1,sizeof(size_t));
177                 memcpy(&p,&s2,sizeof(size_t));
178                 
179                 return (q == p);
180         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
