.TH "InAddr_HashComp" 3 "4 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InAddr_HashComp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const in_addr &s1, const in_addr &s2) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool InAddr_HashComp::operator() (const in_addr & s1, const in_addr & s2) const\fC [inline]\fP"
.PP
Definition at line 157 of file modules.cpp.
.PP
.nf
158         {
159                 size_t q;
160                 size_t p;
161                 
162                 memcpy(&q,&s1,sizeof(size_t));
163                 memcpy(&p,&s2,sizeof(size_t));
164                 
165                 return (q == p);
166         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
