inspircd.h
NAME
inspircd.h -
SYNOPSIS
#include 'inspircd_config.h'
#include <string>
#include <stdio.h>
#include <unistd.h>
#include <signal.h>
#include <time.h>
#include <netdb.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <deque>
#include 'inspircd_io.h'
#include 'inspircd_util.h'
#include 'users.h'
#include 'channels.h'
#include 'socket.h'
Classes
class serverstats
class InspIRCd
Defines
#define ERROR -1
#define TRUE 1
#define FALSE 0
#define MAXSOCKS 64
#define MAXCOMMAND 32
#define WM_AND 1
#define WM_OR 2
#define TYPE_USER 1
#define TYPE_CHANNEL 2
#define TYPE_SERVER 3
#define IS_LOCAL(x) (x->fd > -1)
#define IS_REMOTE(x) (x->fd < 0)
#define IS_MODULE_CREATED(x) (x->fd == FD_MAGIC_NUMBER)
Typedefs
typedef void( handlerfunc )(char **, int, userrec *)
Functions
void force_nickchange (userrec *user, const char *newnick)
void kill_link (userrec *user, const char *r)
void kill_link_silent (userrec *user, const char *r)
void call_handler (const char *commandname, char **parameters, int pcnt, userrec *user)
bool is_valid_cmd (const char *commandname, int pcnt, userrec *user)
std::string GetRevision ()
int loop_call (handlerfunc fn, char **parameters, int pcnt, userrec *u, int start, int end, int joins)
void AddWhoWas (userrec *u)
void ConnectUser (userrec *user)
userrec * ReHashNick (char *Old, char *New)
char * ModuleError ()
void AddOper (userrec *user)
void DeleteOper (userrec *user)
void handle_version (char **parameters, int pcnt, userrec *user)
void AddServerName (std::string servername)
const char * FindServerNamePtr (std::string servername)
std::string GetVersionString ()
void * dns_task (void *arg)
void process_buffer (const char *cmdbuf, userrec *user)
void FullConnectUser (userrec *user)
Define Documentation
#define ERROR -1
Definition at line 49 of file inspircd.h.
Referenced by InspSocket::InspSocket().
#define FALSE 0
Definition at line 51 of file inspircd.h.
#define IS_LOCAL(x) (x->fd > -1)
Definition at line 66 of file inspircd.h.
#define IS_MODULE_CREATED(x) (x->fd == FD_MAGIC_NUMBER)
Definition at line 68 of file inspircd.h.
#define IS_REMOTE(x) (x->fd < 0)
Definition at line 67 of file inspircd.h.
#define MAXCOMMAND 32
Definition at line 53 of file inspircd.h.
#define MAXSOCKS 64
Definition at line 52 of file inspircd.h.
#define TRUE 1
Definition at line 50 of file inspircd.h.
#define TYPE_CHANNEL 2
Definition at line 63 of file inspircd.h.
#define TYPE_SERVER 3
Definition at line 64 of file inspircd.h.
#define TYPE_USER 1
Definition at line 62 of file inspircd.h.
#define WM_AND 1
Definition at line 57 of file inspircd.h.
#define WM_OR 2
Definition at line 58 of file inspircd.h.
Typedef Documentation
typedef void( handlerfunc)(char **, int, userrec *)
Definition at line 70 of file inspircd.h.
Function Documentation
void AddOper (userrec * user)
void AddServerName (std::string servername)
void AddWhoWas (userrec * u)
void call_handler (const char * commandname, char ** parameters, int pcnt, userrec * user)
Referenced by Server::CallCommandHandler().
void ConnectUser (userrec * user)
void DeleteOper (userrec * user)
void* dns_task (void * arg)
const char* FindServerNamePtr (std::string servername)
Referenced by userrec::userrec().
void force_nickchange (userrec * user, const char * newnick)
Referenced by Server::ChangeUserNick().
void FullConnectUser (userrec * user)
std::string GetRevision ()
std::string GetVersionString ()
void handle_version (char ** parameters, int pcnt, userrec * user)
bool is_valid_cmd (const char * commandname, int pcnt, userrec * user)
Referenced by Server::IsValidModuleCommand().
void kill_link (userrec * user, const char * r)
Referenced by Server::PseudoToUser(), and Server::QuitUser().
void kill_link_silent (userrec * user, const char * r)
int loop_call (handlerfunc fn, char ** parameters, int pcnt, userrec * u, int start, int end, int joins)
char* ModuleError ()
void process_buffer (const char * cmdbuf, userrec * user)
userrec* ReHashNick (char * Old, char * New)
Author
Generated automatically by Doxygen for InspIRCd from the source code.