InspSocket
NAME
InspSocket - InspSocket is an extendable socket class which modules can use for TCP socket support.
SYNOPSIS
#include <socket.h>
Public Member Functions
InspSocket ()
The default constructor does nothing and should not be used.
InspSocket (int newfd, char *ip)
This constructor is used to associate an existing connecting with an InspSocket class.
InspSocket (std::string host, int port, bool listening, unsigned long maxtime)
This constructor is used to create a new socket, either listening for connections, or an outbound connection to another host.
virtual bool OnConnected ()
This method is called when an outbound connection on your socket is completed.
virtual void OnError (InspSocketError e)
This method is called when an error occurs.
virtual int OnDisconnect ()
When an established connection is terminated, the OnDisconnect method is triggered.
virtual bool OnDataReady ()
When there is data waiting to be read on a socket, the OnDataReady() method is called.
virtual void OnTimeout ()
When an outbound connection fails, and the attempt times out, you will receive this event.
virtual void OnClose ()
Whenever close() is called, OnClose() will be called first.
virtual char * Read ()
Reads all pending bytes from the socket into a char* array which can be up to 16 kilobytes in length.
std::string GetIP ()
Returns the IP address associated with this connection, or an empty string if no IP address exists.
bool Timeout (time_t current)
This function checks if the socket has timed out yet, given the current time in the parameter.
virtual int Write (std::string data)
Writes a std::string to the socket.
virtual int OnIncomingConnection (int newfd, char *ip)
If your socket is a listening socket, when a new connection comes in on the socket this method will be called.
void SetState (InspSocketState s)
Changes the socket's state.
InspSocketState GetState ()
Returns the current socket state.
bool Poll ()
Only the core should call this function.
int GetFd ()
This method returns the socket's file descriptor as assigned by the operating system, or -1 if no descriptor has been assigned.
virtual void Close ()
This method causes the socket to close, and may also be triggered by other methods such as OnTimeout and OnError.
virtual ~InspSocket ()
The destructor may implicitly call OnClose(), and will close() and shutdown() the file descriptor used for this socket.
Private Member Functions
void FlushWriteBuffer ()
Flushes the write buffer.
Private Attributes
int fd
The file descriptor of this socket.
std::string host
The hostname connected to.
int port
The port connected to, or the port this socket is listening on.
InspSocketState state
The state for this socket, either listening, connecting, connected or error.
sockaddr_in addr
The host being connected to, in sockaddr form.
in_addr addy
The host being connected to, in in_addr form.
time_t timeout_end
When this time is reached, the socket times out if it is in the CONNECTING state.
bool timeout
This value is true if the socket has timed out.
char ibuf [65535]
Socket input buffer, used by read().
std::string Buffer
The output buffer for this socket.
std::string IP
The IP address being connected to stored in string form for easy retrieval by accessors.
sockaddr_in client
Client sockaddr structure used by accept().
sockaddr_in server
Server sockaddr structure used by accept().
socklen_t length
Used by accept() to indicate the sizes of the sockaddr_in structures.
Detailed Description
InspSocket is an extendable socket class which modules can use for TCP socket support.
It is fully integrated into InspIRCds socket loop and attaches its sockets to the core's instance of the SocketEngine class, meaning that any sockets you create have the same power and abilities as a socket created by the core itself. To use InspSocket, you must inherit a class from it, and use the InspSocket constructors to establish connections and bindings.
Definition at line 47 of file socket.h.
Constructor & Destructor Documentation
InspSocket::InspSocket ()
The default constructor does nothing and should not be used.
Definition at line 45 of file socket.cpp.
References I_DISCONNECTED, and state.
{
        this->state = I_DISCONNECTED;
}
InspSocket::InspSocket (int newfd, char * ip)
This constructor is used to associate an existing connecting with an InspSocket class.
The given file descriptor must be valid, and when initialized, the InspSocket will be set with the given IP address and placed in CONNECTED state.
Definition at line 50 of file socket.cpp.
References SocketEngine::AddFd(), fd, I_CONNECTED, IP, InspIRCd::SE, state, and X_ESTAB_MODULE.
{
        this->fd = newfd;
        this->state = I_CONNECTED;
        this->IP = ip;
        ServerInstance->SE->AddFd(this->fd,true,X_ESTAB_MODULE);
        socket_ref[this->fd] = this;
}
InspSocket::InspSocket (std::string host, int port, bool listening, unsigned long maxtime)
This constructor is used to create a new socket, either listening for connections, or an outbound connection to another host.
Parameters:
host The hostname to connect to, or bind to
port The port number to connect to, or bind to
listening true to listen on the given host:port pair, or false to connect to them
maxtime Number of seconds to wait, if connecting, before the connection times out and an OnTimeout() event is generated
Definition at line 59 of file socket.cpp.
References SocketEngine::AddFd(), addr, addy, BindSocket(), Close(), DEBUG, ERROR, fd, I_CONNECTING, I_ERR_BIND, I_ERR_CONNECT, I_ERR_SOCKET, I_ERROR, I_LISTENING, IP, log(), OnError(), OpenTCPSocket(), InspIRCd::SE, state, timeout, timeout_end, and X_ESTAB_MODULE.
{
        if (listening) {
                if ((this->fd = OpenTCPSocket()) == ERROR)
                {
                        this->fd = -1;
                        this->state = I_ERROR;
                        this->OnError(I_ERR_SOCKET);
                        log(DEBUG,'OpenTCPSocket() error');
                        return;
                }
                else
                {
                        if (BindSocket(this->fd,this->client,this->server,port,(char*)host.c_str()) == ERROR)
                        {
                                this->Close();
                                this->fd = -1;
                                this->state = I_ERROR;
                                this->OnError(I_ERR_BIND);
                                log(DEBUG,'BindSocket() error %s',strerror(errno));
                                return;
                        }
                        else
                        {
                                this->state = I_LISTENING;
                                ServerInstance->SE->AddFd(this->fd,true,X_ESTAB_MODULE);
                                socket_ref[this->fd] = this;
                                log(DEBUG,'New socket now in I_LISTENING state');
                                return;
                        }
                }
        } else {
                char* ip;
                this->host = host;
                hostent* hoste = gethostbyname(host.c_str());
                if (!hoste) {
                        ip = (char*)host.c_str();
                } else {
                        struct in_addr* ia = (in_addr*)hoste->h_addr;
                        ip = inet_ntoa(*ia);
                }
                this->IP = ip;
                timeout_end = time(NULL)+maxtime;
                timeout = false;
                if ((this->fd = socket(AF_INET, SOCK_STREAM, 0)) == -1)
                {
                        this->state = I_ERROR;
                        this->OnError(I_ERR_SOCKET);
                        return;
                }
                this->port = port;
                inet_aton(ip,&addy);
                addr.sin_family = AF_INET;
                addr.sin_addr = addy;
                addr.sin_port = htons(this->port);
                int flags;
                flags = fcntl(this->fd, F_GETFL, 0);
                fcntl(this->fd, F_SETFL, flags | O_NONBLOCK);
                if(connect(this->fd, (sockaddr*)&this->addr,sizeof(this->addr)) == -1)
                {
                        if (errno != EINPROGRESS)
                        {
                                this->Close();
                                this->OnError(I_ERR_CONNECT);
                                this->state = I_ERROR;
                                return;
                        }
                }
                this->state = I_CONNECTING;
                ServerInstance->SE->AddFd(this->fd,false,X_ESTAB_MODULE);
                socket_ref[this->fd] = this;
                return;
        }
}
InspSocket::~InspSocket () [virtual]
The destructor may implicitly call OnClose(), and will close() and shutdown() the file descriptor used for this socket.
Definition at line 271 of file socket.cpp.
References Close().
{
        this->Close();
}
Member Function Documentation
void InspSocket::Close () [virtual]
This method causes the socket to close, and may also be triggered by other methods such as OnTimeout and OnError.
Definition at line 138 of file socket.cpp.
References fd, and OnClose().
Referenced by InspSocket(), and ~InspSocket().
{
        if (this->fd != -1)
        {
                this->OnClose();
                shutdown(this->fd,2);
                close(this->fd);
                socket_ref[this->fd] = NULL;
                this->fd = -1;
        }
}
void InspSocket::FlushWriteBuffer () [private]
Flushes the write buffer.
Definition at line 181 of file socket.cpp.
References Buffer.
Referenced by Timeout(), and Write().
{
        int result = 0;
        if (this->Buffer.length())
        {
                result = send(this->fd,this->Buffer.c_str(),this->Buffer.length(),0);
                if (result > 0)
                {
                        /* If we wrote some, advance the buffer forwards */
                        char* n = (char*)this->Buffer.c_str();
                        n += result;
                        this->Buffer = n;
                }
        }
}
int InspSocket::GetFd ()
This method returns the socket's file descriptor as assigned by the operating system, or -1 if no descriptor has been assigned.
Definition at line 258 of file socket.cpp.
References fd.
{
        return this->fd;
}
std::string InspSocket::GetIP ()
Returns the IP address associated with this connection, or an empty string if no IP address exists.
Definition at line 150 of file socket.cpp.
References IP.
{
        return this->IP;
}
InspSocketState InspSocket::GetState ()
Returns the current socket state.
Definition at line 253 of file socket.cpp.
References state.
{
        return this->state;
}
void InspSocket::OnClose () [virtual]
Whenever close() is called, OnClose() will be called first.
Please note that this means OnClose will be called alongside OnError(), OnTimeout(), and Close(), and also when cancelling a listening socket by calling the destructor indirectly.
Definition at line 269 of file socket.cpp.
Referenced by Close().
{ return; }
bool InspSocket::OnConnected () [virtual]
This method is called when an outbound connection on your socket is completed.
Returns:
false to abort the connection, true to continue
Definition at line 263 of file socket.cpp.
Referenced by Poll().
{ return true; }
bool InspSocket::OnDataReady () [virtual]
When there is data waiting to be read on a socket, the OnDataReady() method is called.
Within this method, you *MUST* call the Read() method to read any pending data. At its lowest level, this event is signalled by the core via the socket engine. If you return false from this function, the core removes your socket from its list and erases it from the socket engine, then calls InspSocket::Close() and deletes it.
Returns:
false to close the socket
Definition at line 267 of file socket.cpp.
Referenced by Poll().
{ return true; }
int InspSocket::OnDisconnect () [virtual]
When an established connection is terminated, the OnDisconnect method is triggered.
Definition at line 265 of file socket.cpp.
{ return 0; }
void InspSocket::OnError (InspSocketError e) [virtual]
This method is called when an error occurs.
A closed socket in itself is not an error, however errors also generate close events.
Parameters:
e The error type which occured
Definition at line 264 of file socket.cpp.
Referenced by InspSocket(), and Timeout().
{ return; }
int InspSocket::OnIncomingConnection (int newfd, char * ip) [virtual]
If your socket is a listening socket, when a new connection comes in on the socket this method will be called.
Given the new file descriptor in the parameters, and the IP, it is recommended you copy them to a new instance of your socket class, e.g.:
MySocket* newsocket = new MySocket(newfd,ip);
Once you have done this, you can then associate the new socket with the core using Server::AddSocket().
Definition at line 266 of file socket.cpp.
Referenced by Poll().
{ return 0; }
void InspSocket::OnTimeout () [virtual]
When an outbound connection fails, and the attempt times out, you will receive this event.
The mthod will trigger once maxtime secons are reached (as given in the constructor) just before the socket's descriptor is closed.
Definition at line 268 of file socket.cpp.
Referenced by Timeout().
{ return; }
bool InspSocket::Poll ()
Only the core should call this function.
When called, it is assumed the socket is ready to read data, and the method call routes the event to the various methods of InspSocket for you to handle. This can also cause the socket's state to change.
Definition at line 216 of file socket.cpp.
References SocketEngine::AddFd(), client, SocketEngine::DelFd(), I_CONNECTED, I_CONNECTING, I_LISTENING, length, OnConnected(), OnDataReady(), OnIncomingConnection(), InspIRCd::SE, SetState(), and X_ESTAB_MODULE.
{
        int incoming = -1;
        
        switch (this->state)
        {
                case I_CONNECTING:
                        this->SetState(I_CONNECTED);
                        /* Our socket was in write-state, so delete it and re-add it
                         * in read-state.
                         */
                        ServerInstance->SE->DelFd(this->fd);
                        ServerInstance->SE->AddFd(this->fd,true,X_ESTAB_MODULE);
                        return this->OnConnected();
                break;
                case I_LISTENING:
                        length = sizeof (client);
                        incoming = accept (this->fd, (sockaddr*)&client,&length);
                        this->OnIncomingConnection(incoming,inet_ntoa(client.sin_addr));
                        return true;
                break;
                case I_CONNECTED:
                        return this->OnDataReady();
                break;
                default:
                break;
        }
        return true;
}
char * InspSocket::Read () [virtual]
Reads all pending bytes from the socket into a char* array which can be up to 16 kilobytes in length.
Definition at line 155 of file socket.cpp.
References DEBUG, ibuf, and log().
{
        int n = recv(this->fd,this->ibuf,sizeof(this->ibuf),0);
        if (n > 0)
        {
                ibuf[n] = 0;
                return ibuf;
        }
        else
        {
                log(DEBUG,'EOF or error on socket');
                return NULL;
        }
}
void InspSocket::SetState (InspSocketState s)
Changes the socket's state.
The core uses this to change socket states, and you should not call it directly.
Definition at line 247 of file socket.cpp.
References DEBUG, log(), and state.
Referenced by Poll().
{
        log(DEBUG,'Socket state change');
        this->state = s;
}
bool InspSocket::Timeout (time_t current)
This function checks if the socket has timed out yet, given the current time in the parameter.
Returns:
true if timed out, false if not timed out
Definition at line 197 of file socket.cpp.
References FlushWriteBuffer(), I_CONNECTING, I_ERR_TIMEOUT, I_ERROR, OnError(), OnTimeout(), state, timeout, and timeout_end.
{
        if ((this->state == I_CONNECTING) && (current > timeout_end))
        {
                // for non-listening sockets, the timeout can occur
                // which causes termination of the connection after
                // the given number of seconds without a successful
                // connection.
                this->OnTimeout();
                this->OnError(I_ERR_TIMEOUT);
                timeout = true;
                this->state = I_ERROR;
                return true;
        }
        if (this->Buffer.length())
                this->FlushWriteBuffer();
        return false;
}
int InspSocket::Write (std::string data) [virtual]
Writes a std::string to the socket.
No carriage returns or linefeeds are appended to the string.
Parameters:
data The data to send
Definition at line 174 of file socket.cpp.
References Buffer, and FlushWriteBuffer().
{
        this->Buffer = this->Buffer + data;
        this->FlushWriteBuffer();
        return data.length();
}
Member Data Documentation
sockaddr_in InspSocket::addr [private]
The host being connected to, in sockaddr form.
Definition at line 78 of file socket.h.
Referenced by InspSocket().
in_addr InspSocket::addy [private]
The host being connected to, in in_addr form.
Definition at line 84 of file socket.h.
Referenced by InspSocket().
std::string InspSocket::Buffer [private]
The output buffer for this socket.
Definition at line 111 of file socket.h.
Referenced by FlushWriteBuffer(), and Write().
sockaddr_in InspSocket::client [private]
Client sockaddr structure used by accept().
Definition at line 124 of file socket.h.
Referenced by Poll().
int InspSocket::fd [private]
The file descriptor of this socket.
Definition at line 54 of file socket.h.
Referenced by Close(), GetFd(), and InspSocket().
std::string InspSocket::host [private]
The hostname connected to.
Definition at line 59 of file socket.h.
char InspSocket::ibuf[65535] [private]
Socket input buffer, used by read().
The class which extends InspSocket is expected to implement an extendable buffer which can grow much larger than 64k, this buffer is just designed to be temporary storage. space.
Definition at line 106 of file socket.h.
Referenced by Read().
std::string InspSocket::IP [private]
The IP address being connected to stored in string form for easy retrieval by accessors.
Definition at line 118 of file socket.h.
Referenced by GetIP(), and InspSocket().
socklen_t InspSocket::length [private]
Used by accept() to indicate the sizes of the sockaddr_in structures.
Definition at line 136 of file socket.h.
Referenced by Poll().
int InspSocket::port [private]
The port connected to, or the port this socket is listening on.
Definition at line 65 of file socket.h.
sockaddr_in InspSocket::server [private]
Server sockaddr structure used by accept().
Definition at line 130 of file socket.h.
InspSocketState InspSocket::state [private]
The state for this socket, either listening, connecting, connected or error.
Definition at line 72 of file socket.h.
Referenced by GetState(), InspSocket(), SetState(), and Timeout().
bool InspSocket::timeout [private]
This value is true if the socket has timed out.
Definition at line 97 of file socket.h.
Referenced by InspSocket(), and Timeout().
time_t InspSocket::timeout_end [private]
When this time is reached, the socket times out if it is in the CONNECTING state.
Definition at line 91 of file socket.h.
Referenced by InspSocket(), and Timeout().
Author
Generated automatically by Doxygen for InspIRCd from the source code.