.TH "inspircd.h" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inspircd.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <netdb.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <arpa/inet.h>\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'inspircd_io.h'\fP
.br
\fC#include 'users.h'\fP
.br
\fC#include 'channels.h'\fP
.br
\fC#include 'socket.h'\fP
.br
\fC#include 'mode.h'\fP
.br
\fC#include 'socketengine.h'\fP
.br
\fC#include 'command_parse.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBserverstats\fP"
.br
.ti -1c
.RI "class \fBInspIRCd\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBERROR\fP   -1"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.ti -1c
.RI "#define \fBMAXSOCKS\fP   64"
.br
.ti -1c
.RI "#define \fBMAXCOMMAND\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAddServerName\fP (\fBstd::string\fP servername)"
.br
.ti -1c
.RI "const char * \fBFindServerNamePtr\fP (\fBstd::string\fP servername)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ERROR   -1"
.PP
Definition at line 51 of file inspircd.h.
.PP
Referenced by InspSocket::InspSocket().
.SS "#define FALSE   0"
.PP
Definition at line 53 of file inspircd.h.
.SS "#define MAXCOMMAND   32"
.PP
Definition at line 55 of file inspircd.h.
.SS "#define MAXSOCKS   64"
.PP
Definition at line 54 of file inspircd.h.
.SS "#define TRUE   1"
.PP
Definition at line 52 of file inspircd.h.
.SH "Function Documentation"
.PP 
.SS "void AddServerName (\fBstd::string\fP servername)"
.PP
.SS "const char* FindServerNamePtr (\fBstd::string\fP servername)"
.PP
Referenced by AddClient(), and userrec::userrec().
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
