.TH "InviteItem" 3 "12 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InviteItem \- A subclass of \fBHostItem\fP designed to hold channel invites (+I).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <channels.h>\fP
.PP
Inherits \fBHostItem\fP.
.PP
.SH "Detailed Description"
.PP 
A subclass of \fBHostItem\fP designed to hold channel invites (+I). 
.PP
Definition at line 68 of file channels.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
