.TH "Invited" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Invited \- Holds a channel name to which a user has been invited.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <users.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBirc::string\fP \fBchannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds a channel name to which a user has been invited. 
.PP
Definition at line 43 of file users.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBirc::string\fP \fBInvited::channel\fP"
.PP
Definition at line 46 of file users.h.
.PP
Referenced by userrec::InviteTo().

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
