.TH "Invited" 3 "2 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Invited \- Holds a channel name to which a user has been invited.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <users.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBchannel\fP [CHANMAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds a channel name to which a user has been invited. Definition at line 36 of file users.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBInvited::channel\fP[CHANMAX]"
.PP
Definition at line 39 of file users.h.
.PP
Referenced by userrec::InviteTo().

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
