.TH "irc" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc \- The irc namespace contains a number of helper classes.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStrHashComp\fP"
.br
.RI "\fIThis class returns true if two strings match. \fP"
.ti -1c
.RI "struct \fBInAddr_HashComp\fP"
.br
.RI "\fIThis class returns true if two in_addr structs match. \fP"
.ti -1c
.RI "struct \fBirc_char_traits\fP"
.br
.RI "\fIThe \fBirc_char_traits\fP class is used for RFC-style comparison of strings. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef basic_string< char, \fBirc_char_traits\fP, allocator< char > > \fBstring\fP"
.br
.RI "\fIThis typedef declares \fBirc::string\fP based upon \fBirc_char_traits\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The irc namespace contains a number of helper classes. 
.SH "Typedef Documentation"
.PP 
.SS "typedef basic_string<char, \fBirc_char_traits\fP, allocator<char> > \fBirc::string\fP"
.PP
This typedef declares \fBirc::string\fP based upon \fBirc_char_traits\fP. 
.PP
Definition at line 129 of file hashcomp.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
