.TH "irc::StrHashComp" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc::StrHashComp \- This class returns true if two strings match.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <hashcomp.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBstd::string\fP &s1, const \fBstd::string\fP &s2) const "
.br
.RI "\fIThe operator () does the actual comparison in hash_map. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class returns true if two strings match. 

Case sensitivity is ignored, and the RFC 'character set' is adhered to
.PP
Definition at line 80 of file hashcomp.h.
.SH "Member Function Documentation"
.PP 
.SS "bool irc::StrHashComp::operator() (const \fBstd::string\fP & s1, const \fBstd::string\fP & s2) const"
.PP
The operator () does the actual comparison in hash_map. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
