.TH "KLine" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KLine \- KLine class.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <xline.h>\fP
.PP
Inherits \fBXLine\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBhostmask\fP [200]"
.br
.RI "\fIHostmask (ident) to match against May contain wildcards. \fP"
.in -1c
.SH "Detailed Description"
.PP 
KLine class. 
.PP
Definition at line 67 of file xline.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBKLine::hostmask\fP[200]"
.PP
Hostmask (ident) to match against May contain wildcards. 
.PP
Definition at line 73 of file xline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
