message.h
NAME
message.h -
SYNOPSIS
#include <typeinfo>
#include <iostream>
#include <string>
#include <deque>
#include <sstream>
#include <vector>
#include 'users.h'
#include 'channels.h'
Functions
int common_channels (userrec *u, userrec *u2)
void chop (char *str)
void tidystring (char *str)
void Blocking (int s)
void NonBlocking (int s)
int CleanAndResolve (char *resolvedHost, const char *unresolvedHost)
int c_count (userrec *u)
bool hasumode (userrec *user, char mode)
void ChangeName (userrec *user, const char *gecos)
void ChangeDisplayedHost (userrec *user, const char *host)
int isident (const char *n)
int isnick (const char *n)
char * cmode (userrec *user, chanrec *chan)
int cstatus (userrec *user, chanrec *chan)
int has_channel (userrec *u, chanrec *c)
void TidyBan (char *ban)
std::string chlist (userrec *user, userrec *source)
void send_network_quit (const char *nick, const char *reason)
Function Documentation
void Blocking (int s)
int c_count (userrec * u)
void ChangeDisplayedHost (userrec * user, const char * host)
Referenced by Server::ChangeHost().
void ChangeName (userrec * user, const char * gecos)
Referenced by Server::ChangeGECOS().
std::string chlist (userrec * user, userrec * source)
void chop (char * str)
int CleanAndResolve (char * resolvedHost, const char * unresolvedHost)
char* cmode (userrec * user, chanrec * chan)
Referenced by Server::ChanMode().
int common_channels (userrec * u, userrec * u2)
Referenced by Server::CommonChannels().
int cstatus (userrec * user, chanrec * chan)
int has_channel (userrec * u, chanrec * c)
Referenced by Server::IsOnChannel().
bool hasumode (userrec * user, char mode)
int isident (const char * n)
int isnick (const char * n)
Referenced by Server::IsNick().
void NonBlocking (int s)
void send_network_quit (const char * nick, const char * reason)
void TidyBan (char * ban)
void tidystring (char * str)
Author
Generated automatically by Doxygen for InspIRCd from the source code.