.TH "mode.h" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <typeinfo>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'users.h'\fP
.br
\fC#include 'channels.h'\fP
.br
\fC#include 'ctables.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModeParser\fP"
.br
.ti -1c
.RI "class \fBcmd_mode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
