.TH "ModeParameter" 3 "15 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModeParameter \- Holds a custom parameter to a module-defined channel mode e.g.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <channels.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBmode\fP"
.br
.ti -1c
.RI "char \fBparameter\fP [MAXBUF]"
.br
.ti -1c
.RI "char \fBchannel\fP [CHANMAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds a custom parameter to a module-defined channel mode e.g. 

for +L this would hold the channel name. 
.PP
Definition at line 77 of file channels.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBModeParameter::channel\fP[CHANMAX]"
.PP
Definition at line 82 of file channels.h.
.PP
Referenced by chanrec::SetCustomModeParam().
.SS "char \fBModeParameter::mode\fP"
.PP
Definition at line 80 of file channels.h.
.PP
Referenced by chanrec::SetCustomModeParam().
.SS "char \fBModeParameter::parameter\fP[MAXBUF]"
.PP
Definition at line 81 of file channels.h.
.PP
Referenced by chanrec::SetCustomModeParam().

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
