.TH "ModuleMessage" 3 "13 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModuleMessage \- The ModuleMessage class is the base class of \fBRequest\fP and \fBEvent\fP This class is used to represent a basic data structure which is passed between modules for safe inter-module communications.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <modules.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
Inherited by \fBEvent\fP, and \fBRequest\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual char * \fBSend\fP ()=0"
.br
.RI "\fIThis class is pure virtual and must be inherited. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The ModuleMessage class is the base class of \fBRequest\fP and \fBEvent\fP This class is used to represent a basic data structure which is passed between modules for safe inter-module communications. Definition at line 141 of file modules.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual char* ModuleMessage::Send ()\fC [pure virtual]\fP"
.PP
This class is pure virtual and must be inherited. Implemented in \fBRequest\fP, and \fBEvent\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
