modules.cpp
NAME
modules.cpp -
SYNOPSIS
#include 'inspircd_config.h'
#include 'inspircd.h'
#include 'inspircd_io.h'
#include 'inspircd_util.h'
#include <unistd.h>
#include <sys/errno.h>
#include <time.h>
#include <string>
#include <hash_map>
#include <map>
#include <sstream>
#include <vector>
#include <deque>
#include 'users.h'
#include 'ctables.h'
#include 'globals.h'
#include 'modules.h'
#include 'dynamic.h'
#include 'wildcard.h'
#include 'message.h'
#include 'mode.h'
#include 'xline.h'
#include 'commands.h'
#include 'inspstring.h'
#include 'helperfuncs.h'
#include 'hashcomp.h'
#include 'socket.h'
#include 'socketengine.h'
Classes
class ExtMode
Typedefs
typedef nspace::hash_map< std::string, userrec *, nspace::hash< string >, irc::StrHashComp > user_hash
typedef nspace::hash_map< std::string, chanrec *, nspace::hash< string >, irc::StrHashComp > chan_hash
typedef nspace::hash_map< in_addr, string *, nspace::hash< in_addr >, irc::InAddr_HashComp > address_cache
typedef nspace::hash_map< std::string, WhoWasUser *, nspace::hash< string >, irc::StrHashComp > whowas_hash
typedef std::deque< command_t > command_table
typedef std::vector< ExtMode > ExtModeList
typedef ExtModeList::iterator ExtModeListIter
Functions
bool ModeDefined (char modechar, int type)
bool ModeIsListMode (char modechar, int type)
bool ModeDefinedOper (char modechar, int type)
int ModeDefinedOn (char modechar, int type)
int ModeDefinedOff (char modechar, int type)
bool DoAddExtendedMode (char modechar, int type, bool requires_oper, int params_on, int params_off)
void ModeMakeList (char modechar)
std::vector< Module * > modules (255)
std::vector< ircd_module * > factory (255)
Variables
SocketEngine * SE
int MODCOUNT = -1
std::vector< Module * > modules
std::vector< ircd_module * > factory
std::vector< std::string > include_stack
std::vector< InspSocket * > module_sockets
time_t TIME
int LogLevel
char ServerName [MAXBUF]
char Network [MAXBUF]
char ServerDesc [MAXBUF]
char AdminName [MAXBUF]
char AdminEmail [MAXBUF]
char AdminNick [MAXBUF]
char diepass [MAXBUF]
char restartpass [MAXBUF]
char motd [MAXBUF]
char rules [MAXBUF]
char list [MAXBUF]
char PrefixQuit [MAXBUF]
char DieValue [MAXBUF]
int debugging
int WHOWAS_STALE
int WHOWAS_MAX
int DieDelay
time_t startup_time
int NetBufferSize
int MaxWhoResults
time_t nb_start
std::vector< std::string > module_names
int boundPortCount
int portCount
int ports [MAXSOCKS]
std::stringstream config_f
FILE * log_file
userrec * fd_ref_table [65536]
user_hash clientlist
chan_hash chanlist
whowas_hash whowas
command_table cmdlist
file_cache MOTD
file_cache RULES
address_cache IP
ExtModeList EMode
Typedef Documentation
typedef nspace::hash_map<in_addr,string*, nspace::hash<in_addr>, irc::InAddr_HashComp> address_cache
Definition at line 117 of file modules.cpp.
typedef nspace::hash_map<std::string, chanrec*, nspace::hash<string>, irc::StrHashComp> chan_hash
Definition at line 116 of file modules.cpp.
typedef std::deque<command_t> command_table
Definition at line 119 of file modules.cpp.
typedef std::vector<ExtMode> ExtModeList
Definition at line 145 of file modules.cpp.
typedef ExtModeList::iterator ExtModeListIter
Definition at line 146 of file modules.cpp.
typedef nspace::hash_map<std::string, userrec*, nspace::hash<string>, irc::StrHashComp> user_hash
Definition at line 115 of file modules.cpp.
typedef nspace::hash_map<std::string, WhoWasUser*, nspace::hash<string>, irc::StrHashComp> whowas_hash
Definition at line 118 of file modules.cpp.
Function Documentation
bool DoAddExtendedMode (char modechar, int type, bool requires_oper, int params_on, int params_off)
Definition at line 215 of file modules.cpp.
References EMode, and ModeDefined().
Referenced by Server::AddExtendedListMode(), and Server::AddExtendedMode().
{
        if (ModeDefined(modechar,type)) {
                return false;
        }
        EMode.push_back(ExtMode(modechar,type,requires_oper,params_on,params_off));
        return true;
}
std::vector<ircd_module*> factory (255)
bool ModeDefined (char modechar, int type)
Definition at line 152 of file modules.cpp.
References EMode.
Referenced by DoAddExtendedMode().
{
        for (ExtModeListIter i = EMode.begin(); i < EMode.end(); i++)
        {
                if ((i->modechar == modechar) && (i->type == type))
                {
                        return true;
                }
        }
        return false;
}
int ModeDefinedOff (char modechar, int type)
Definition at line 202 of file modules.cpp.
References EMode.
{
        for (ExtModeListIter i = EMode.begin(); i < EMode.end(); i++)
        {
                if ((i->modechar == modechar) && (i->type == type))
                {
                        return i->params_when_off;
                }
        }
        return 0;
}
int ModeDefinedOn (char modechar, int type)
Definition at line 189 of file modules.cpp.
References EMode.
{
        for (ExtModeListIter i = EMode.begin(); i < EMode.end(); i++)
        {
                if ((i->modechar == modechar) && (i->type == type))
                {
                        return i->params_when_on;
                }
        }
        return 0;
}
bool ModeDefinedOper (char modechar, int type)
Definition at line 176 of file modules.cpp.
References EMode.
{
        for (ExtModeListIter i = EMode.begin(); i < EMode.end(); i++)
        {
                if ((i->modechar == modechar) && (i->type == type) && (i->needsoper == true))
                {
                        return true;
                }
        }
        return false;
}
bool ModeIsListMode (char modechar, int type)
Definition at line 164 of file modules.cpp.
References EMode.
{
        for (ExtModeListIter i = EMode.begin(); i < EMode.end(); i++)
        {
                if ((i->modechar == modechar) && (i->type == type) && (i->list == true))
                {
                        return true;
                }
        }
        return false;
}
void ModeMakeList (char modechar)
Definition at line 225 of file modules.cpp.
References EMode, and MT_CHANNEL.
Referenced by Server::AddExtendedListMode().
{
        for (ExtModeListIter i = EMode.begin(); i < EMode.end(); i++)
        {
                if ((i->modechar == modechar) && (i->type == MT_CHANNEL))
                {
                        i->list = true;
                        return;
                }
        }
        return;
}
std::vector<Module*> modules (255)
Variable Documentation
char AdminEmail[MAXBUF]
char AdminName[MAXBUF]
char AdminNick[MAXBUF]
int boundPortCount
chan_hash chanlist
user_hash clientlist
command_table cmdlist
std::stringstream config_f
int debugging
int DieDelay
char diepass[MAXBUF]
char DieValue[MAXBUF]
ExtModeList EMode
Definition at line 149 of file modules.cpp.
Referenced by DoAddExtendedMode(), ModeDefined(), ModeDefinedOff(), ModeDefinedOn(), ModeDefinedOper(), ModeIsListMode(), and ModeMakeList().
std::vector<ircd_module*> factory
userrec* fd_ref_table[65536]
std::vector<std::string> include_stack
Referenced by ConfigReader::ConfigReader().
address_cache IP
char list[MAXBUF]
FILE* log_file
int LogLevel
int MaxWhoResults
Definition at line 81 of file channels.cpp.
int MODCOUNT = -1
Definition at line 1005 of file modules.cpp.
std::vector<std::string> module_names
std::vector<InspSocket*> module_sockets
Referenced by Server::AddSocket(), and Server::DelSocket().
std::vector<Module*> modules
file_cache MOTD
char motd[MAXBUF]
time_t nb_start
int NetBufferSize
char Network[MAXBUF]
int portCount
int ports[MAXSOCKS]
char PrefixQuit[MAXBUF]
char restartpass[MAXBUF]
file_cache RULES
char rules[MAXBUF]
SocketEngine* SE
char ServerDesc[MAXBUF]
char ServerName[MAXBUF]
time_t startup_time
time_t TIME
whowas_hash whowas
int WHOWAS_MAX
int WHOWAS_STALE
Author
Generated automatically by Doxygen for InspIRCd from the source code.