.TH "ModuleMessage" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModuleMessage \- The ModuleMessage class is the base class of \fBRequest\fP and \fBEvent\fP This class is used to represent a basic data structure which is passed between modules for safe inter-module communications.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <modules.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
Inherited by \fBEvent\fP, and \fBRequest\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual char * \fBSend\fP ()=0"
.br
.RI "\fIThis class is pure virtual and must be inherited. \fP"
.ti -1c
.RI "virtual \fB~ModuleMessage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The ModuleMessage class is the base class of \fBRequest\fP and \fBEvent\fP This class is used to represent a basic data structure which is passed between modules for safe inter-module communications. 
.PP
Definition at line 143 of file modules.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ModuleMessage::~ModuleMessage ()\fC [inline, virtual]\fP"
.PP
Definition at line 149 of file modules.h.
.PP
.nf
149 {};
.fi
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual char* ModuleMessage::Send ()\fC [pure virtual]\fP"
.PP
This class is pure virtual and must be inherited. 
.PP
Implemented in \fBRequest\fP, and \fBEvent\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
