.TH "nspace::nspace::hash< in_addr >" 3 "7 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nspace::nspace::hash< in_addr > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const struct in_addr &a) const"
.br
.in -1c

.SS "template<> struct nspace::hash< in_addr >"

.SH "Member Function Documentation"
.PP 
.SS "size_t nspace::hash< in_addr >::operator() (const struct in_addr & a) const\fC [inline]\fP"
.PP
Definition at line 119 of file modules.cpp.
.PP
.nf
120                 {
121                         size_t q;
122                         memcpy(&q,&a,sizeof(size_t));
123                         return q;
124                 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
