.TH "nspace" 3 "7 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nspace \- 
.SH SYNOPSIS
.br
.PP
.SS "Compounds"

.in +1c
.ti -1c
.RI "struct \fBnspace.hash< in_addr >\fP"
.br
.ti -1c
.RI "struct \fBnspace.hash< string >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
