.TH "nspace::hash< string >" 3 "19 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nspace::hash< string > \- 
.SH SYNOPSIS
.br
.PP
\fC#include <hashcomp.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const \fBstring\fP &s) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct nspace::hash< string >"

.PP
Definition at line 62 of file hashcomp.h.
.SH "Member Function Documentation"
.PP 
.SS "size_t nspace::hash< \fBstring\fP >::operator() (const \fBstring\fP & s) const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
