.TH "nspace::nspace::hash< string >" 3 "2 May 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nspace::nspace::hash< string > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const string &s) const"
.br
.in -1c

.SS "template<> struct nspace::hash< string >"

.SH "Member Function Documentation"
.PP 
.SS "size_t nspace::hash< string >::operator() (const string & s) const\fC [inline]\fP"
.PP
Definition at line 107 of file modules.cpp.
.PP
.nf
108                 {
109                         char a[MAXBUF];
110                         static struct hash<const char *> strhash;
111                         strcpy(a,s.c_str());
112                         strlower(a);
113                         return strhash(a);
114                 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
