.TH "nspace::hash< in_addr >" 3 "12 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nspace::hash< in_addr > \- 
.SH SYNOPSIS
.br
.PP
\fC#include <hashcomp.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const struct in_addr &a) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct nspace::hash< in_addr >"

.PP
Definition at line 54 of file hashcomp.h.
.SH "Member Function Documentation"
.PP 
.SS "size_t nspace::hash< in_addr >::operator() (const struct in_addr & a) const"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
