.TH "nspace::nspace::hash< string >" 3 "14 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nspace::nspace::hash< string > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const string &s) const"
.br
.in -1c

.SS "template<> struct nspace::hash< string >"

.SH "Member Function Documentation"
.PP 
.SS "size_t nspace::hash< string >::operator() (const string & s) const\fC [inline]\fP"
.PP
Definition at line 132 of file modules.cpp.
.PP
.nf
133                 {
134                         char a[MAXBUF];
135                         static struct hash<const char *> strhash;
136                         strlcpy(a,s.c_str(),MAXBUF);
137                         strlower(a);
138                         return strhash(a);
139                 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
