.TH "QLine" 3 "27 Nov 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QLine \- QLine class.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <xline.h>\fP
.PP
Inherits \fBXLine\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBnick\fP [64]"
.br
.RI "\fINickname to match against. \fP"
.ti -1c
.RI "bool \fBis_global\fP"
.br
.RI "\fISet if this is a global Z:line (e.g. \fP"
.in -1c
.SH "Detailed Description"
.PP 
QLine class. 
.PP
Definition at line 108 of file xline.h.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBQLine::is_global\fP"
.PP
Set if this is a global Z:line (e.g. 
.PP
it came from another server)
.PP
Definition at line 118 of file xline.h.
.SS "char \fBQLine::nick\fP[64]"
.PP
Nickname to match against. 
.PP
May contain wildcards.
.PP
Definition at line 114 of file xline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
