.TH "QLine" 3 "25 Mar 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QLine \- QLine class.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <xline.h>\fP
.PP
Inherits \fBXLine\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBnick\fP [MAXBUF]"
.br
.RI "\fINickname to match against. \fP"
.ti -1c
.RI "bool \fBis_global\fP"
.br
.RI "\fISet if this is a global Z:line (e.g. \fP"
.in -1c
.SH "Detailed Description"
.PP 
QLine class. Definition at line 99 of file xline.h.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBQLine::is_global\fP"
.PP
Set if this is a global Z:line (e.g. it came from another server)Definition at line 109 of file xline.h.
.SS "char \fBQLine::nick\fP[MAXBUF]"
.PP
Nickname to match against. May contain wildcards.Definition at line 105 of file xline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
