servers.cpp
NAME
servers.cpp -
SYNOPSIS
#include 'inspircd_config.h'
#include 'servers.h'
#include 'inspircd.h'
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <sys/errno.h>
#include <sys/ioctl.h>
#include <sys/utsname.h>
#include <vector>
#include <string>
#include <deque>
#include <sstream>
#include <map>
#include 'inspstring.h'
#include 'helperfuncs.h'
#include 'connection.h'
Functions
bool IsRoutable (std::string servername)
bool already_have_sum (std::string sum)
Variables
time_t TIME
int MaxConn
serverrec * me [32]
bool has_been_netsplit
std::deque< std::string > xsums
Function Documentation
bool already_have_sum (std::string sum)
Definition at line 411 of file servers.cpp.
References xsums.
Referenced by serverrec::RecvPacket().
{
        for (int i = 0; i < xsums.size(); i++)
        {
                if (xsums[i] == sum)
                {
                        return true;
                }
        }
        if (xsums.size() >= 128)
        {
                xsums.pop_front();
        }
        xsums.push_back(sum);
        return false;
}
bool IsRoutable (std::string servername)
Definition at line 256 of file servers.cpp.
References serverrec::connectors, serverrec::FindHost(), ircd_connector::GetState(), me, and STATE_DISCONNECTED.
Referenced by serverrec::FlushWriteBuffers(), and serverrec::RecvPacket().
{
        for (int x = 0; x < 32; x++) if (me[x])
        {
                ircd_connector* cn = me[x]->FindHost(servername.c_str());
                if (cn)
                {
                        if (cn->GetState() == STATE_DISCONNECTED)
                        {
                                for (int k = 0; k < me[x]->connectors.size(); k++)
                                {
                                        for (int m = 0; m < me[x]->connectors[k].routes.size(); m++)
                                        {
                                                if (!strcasecmp(me[x]->connectors[k].routes[m].c_str(),servername.c_str()))
                                                {
                                                        return true;
                                                }
                                        }
                                }
                                return false;
                        }
                        else return true;
                }
        }
        return false;
}
Variable Documentation
bool has_been_netsplit
Definition at line 42 of file servers.cpp.
Referenced by serverrec::FlushWriteBuffers(), and serverrec::RecvPacket().
int MaxConn
Definition at line 38 of file servers.cpp.
Referenced by serverrec::CreateListener().
serverrec* me[32]
Definition at line 40 of file servers.cpp.
time_t TIME
Definition at line 37 of file servers.cpp.
std::deque<std::string> xsums
Definition at line 44 of file servers.cpp.
Referenced by already_have_sum().
Author
Generated automatically by Doxygen for InspIRCd from the source code.