.TH "servers.h" 3 "25 Mar 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
servers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'connection.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br

.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBserverrec\fP"
.br
.RI "\fIA class that defines the local server or a remote server. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLINK_ACTIVE\fP   1"
.br
.ti -1c
.RI "#define \fBLINK_INACTIVE\fP   0"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define LINK_ACTIVE   1"
.PP
Definition at line 25 of file servers.h.
.SS "#define LINK_INACTIVE   0"
.PP
Definition at line 26 of file servers.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
