Server
NAME
Server - Allows server output and query functions This class contains methods which allow a module to query the state of the irc server, and produce output to users and other servers.
SYNOPSIS
#include <modules.h>
Inherits classbase.
Public Member Functions
Server ()
Default constructor.
virtual ~Server ()
Default destructor.
virtual void SendOpers (std::string s)
Sends text to all opers.
virtual void Log (int level, std::string s)
Writes a log string.
virtual void Send (int Socket, std::string s)
Sends a line of text down a TCP/IP socket.
virtual void SendServ (int Socket, std::string s)
Sends text from the server to a socket.
virtual void SendChannelServerNotice (std::string ServName, chanrec *Channel, std::string text)
Writes text to a channel, but from a server, including all.
virtual void SendFrom (int Socket, userrec *User, std::string s)
Sends text from a user to a socket.
virtual void SendTo (userrec *Source, userrec *Dest, std::string s)
Sends text from a user to another user.
virtual void SendChannel (userrec *User, chanrec *Channel, std::string s, bool IncludeSender)
Sends text from a user to a channel (mulicast).
virtual bool CommonChannels (userrec *u1, userrec *u2)
Returns true if two users share a common channel.
virtual void SendCommon (userrec *User, std::string text, bool IncludeSender)
Sends text from a user to one or more channels (mulicast).
virtual void SendWallops (userrec *User, std::string text)
Sends a WALLOPS message.
virtual bool IsNick (std::string nick)
Returns true if a nick is valid.
virtual int CountUsers (chanrec *c)
Returns a count of the number of users on a channel.
virtual userrec * FindNick (std::string nick)
Attempts to look up a nick and return a pointer to it.
virtual userrec * FindDescriptor (int socket)
Attempts to look up a nick using the file descriptor associated with that nick.
virtual chanrec * FindChannel (std::string channel)
Attempts to look up a channel and return a pointer to it.
virtual std::string ChanMode (userrec *User, chanrec *Chan)
Attempts to look up a user's privilages on a channel.
virtual bool IsOnChannel (userrec *User, chanrec *Chan)
Checks if a user is on a channel.
virtual std::string GetServerName ()
Returns the server name of the server where the module is loaded.
virtual std::string GetNetworkName ()
Returns the network name, global to all linked servers.
virtual std::string GetServerDescription ()
Returns the server description string of the local server.
virtual Admin GetAdmin ()
Returns the information of the server as returned by the /ADMIN command.
virtual bool AddExtendedMode (char modechar, int type, bool requires_oper, int params_when_on, int params_when_off)
Adds an extended mode letter which is parsed by a module.
virtual bool AddExtendedListMode (char modechar)
Adds an extended mode letter which is parsed by a module and handled in a list fashion.
virtual void AddCommand (char *cmd, handlerfunc f, char flags, int minparams, char *source)
Adds a command to the command table.
virtual void SendMode (char **parameters, int pcnt, userrec *user)
Sends a servermode.
virtual void SendToModeMask (std::string modes, int flags, std::string text)
Sends to all users matching a mode mask You must specify one or more usermodes as the first parameter.
virtual chanrec * JoinUserToChannel (userrec *user, std::string cname, std::string key)
Forces a user to join a channel.
virtual chanrec * PartUserFromChannel (userrec *user, std::string cname, std::string reason)
Forces a user to part a channel.
virtual void ChangeUserNick (userrec *user, std::string nickname)
Forces a user nickchange.
virtual void QuitUser (userrec *user, std::string reason)
Forces a user to quit with the specified reason.
virtual bool MatchText (std::string sliteral, std::string spattern)
Matches text against a glob pattern.
virtual void CallCommandHandler (std::string commandname, char **parameters, int pcnt, userrec *user)
Calls the handler for a command, either implemented by the core or by another module.
virtual void ChangeHost (userrec *user, std::string host)
Change displayed hostname of a user.
virtual void ChangeGECOS (userrec *user, std::string gecos)
Change GECOS (fullname) of a user.
virtual bool IsUlined (std::string server)
Returns true if the servername you give is ulined.
virtual chanuserlist GetUsers (chanrec *chan)
Fetches the userlist of a channel.
virtual bool UserToPseudo (userrec *user, std::string message)
Remove a user's connection to the irc server, but leave their client in existence in the user hash.
virtual bool PseudoToUser (userrec *alive, userrec *zombie, std::string message)
This user takes one user, and switches their file descriptor with another user, so that one user 'becomes' the other.
virtual void AddGLine (long duration, std::string source, std::string reason, std::string hostmask)
Adds a G-line The G-line is propogated to all of the servers in the mesh and enforced as soon as it is added.
virtual void AddQLine (long duration, std::string source, std::string reason, std::string nickname)
Adds a Q-line The Q-line is propogated to all of the servers in the mesh and enforced as soon as it is added.
virtual void AddZLine (long duration, std::string source, std::string reason, std::string ipaddr)
Adds a Z-line The Z-line is propogated to all of the servers in the mesh and enforced as soon as it is added.
virtual void AddKLine (long duration, std::string source, std::string reason, std::string hostmask)
Adds a K-line The K-line is enforced as soon as it is added.
virtual void AddELine (long duration, std::string source, std::string reason, std::string hostmask)
Adds a E-line The E-line is enforced as soon as it is added.
virtual bool DelGLine (std::string hostmask)
Deletes a G-Line from all servers on the mesh.
virtual bool DelQLine (std::string nickname)
Deletes a Q-Line from all servers on the mesh.
virtual bool DelZLine (std::string ipaddr)
Deletes a Z-Line from all servers on the mesh.
virtual bool DelKLine (std::string hostmask)
Deletes a local K-Line.
virtual bool DelELine (std::string hostmask)
Deletes a local E-Line.
virtual long CalcDuration (std::string duration)
Calculates a duration This method will take a string containing a formatted duration (e.g.
virtual bool IsValidMask (std::string mask)
Returns true if a nick!ident string is correctly formatted, false if otherwise.
virtual void MeshSendAll (std::string text)
Sends a line of text to all connected servers.
virtual void MeshSendCommon (userrec *user, std::string text)
This method sends a line of text to all servers who have users which share common channels with the user you provide.
virtual void MeshSendAllAlive (std::string text)
This function is equivalent to Server::MeshSendToAll except it will only route to servers which are directly routable.
virtual void MeshSendUnicast (std::string destination, std::string text)
This function sends a line of text directly to a server.
virtual void MeshSendAllExcept (std::string target, std::string text)
This function sends to all servers EXCEPT the one you specify.
virtual bool MeshCheckChan (chanrec *c, std::string servername)
This function is used to check if any users on channel c are on server servername.
virtual bool MeshCheckCommon (userrec *u, std::string servername)
This function is used to check if user u has any channels in common with users on servername.
virtual Module * FindModule (std::string name)
This function finds a module by name.
Detailed Description
Allows server output and query functions This class contains methods which allow a module to query the state of the irc server, and produce output to users and other servers.
All modules should instantiate at least one copy of this class, and use its member functions to perform their tasks.
Definition at line 694 of file modules.h.
Constructor & Destructor Documentation
Server::Server ()
Default constructor. Creates a Server object.Definition at line 366 of file modules.cpp.
{
}
Server::~Server () [virtual]
Default destructor. Destroys a Server object.Definition at line 370 of file modules.cpp.
{
}
Member Function Documentation
void Server::AddCommand (char * cmd, handlerfunc f, char flags, int minparams, char * source) [virtual]
Adds a command to the command table. This allows modules to add extra commands into the command table. You must place a function within your module which is is of type handlerfunc:
typedef void (handlerfunc) (char**, int, userrec*); ... void handle_kill(char **parameters, int pcnt, userrec *user)
When the command is typed, the parameters will be placed into the parameters array (similar to argv) and the parameter count will be placed into pcnt (similar to argv). There will never be any less parameters than the 'minparams' value you specified when creating the command. The *user parameter is the class of the user which caused the command to trigger, who will always have the flag you specified in 'flags' when creating the initial command. For example to create an oper only command create the commands with flags='o'. The source parameter is used for resource tracking, and should contain the name of your module (with file extension) e.g. 'm_blarp.so'. If you place the wrong identifier here, you can cause crashes if your module is unloaded.Definition at line 439 of file modules.cpp.
References createcommand().
{
        createcommand(cmd,f,flags,minparams,source);
}
void Server::AddELine (long duration, std::string source, std::string reason, std::string hostmask) [virtual]
Adds a E-line The E-line is enforced as soon as it is added. The duration must be in seconds, however you can use the Server::CalcDuration method to convert durations into the 1w2d3h3m6s format used by /GLINE etc. The source is an arbitary string used to indicate who or what sent the data, usually this is the nickname of a person, or a server name. Definition at line 701 of file modules.cpp.
References add_eline(), and duration().
{
        add_eline(duration, source.c_str(), reason.c_str(), hostmask.c_str());
}
bool Server::AddExtendedListMode (char modechar) [virtual]
Adds an extended mode letter which is parsed by a module and handled in a list fashion. This call is used to implement modes like +q and +a. The characteristics of these modes are as follows:
(1) They are ALWAYS on channels, not on users, therefore their type is MT_CHANNEL
(2) They always take exactly one parameter when being added or removed
(3) They can be set multiple times, usually on users in channels
(4) The mode and its parameter are NOT stored in the channels modes structure
It is down to the module handling the mode to maintain state and determine what 'items' (e.g. users, or a banlist) have the mode set on them, and process the modes at the correct times, e.g. during access checks on channels, etc. When the extended mode is triggered the OnExtendedMode method will be triggered as above. Note that the target you are given will be a channel, if for example your mode is set 'on a user' (in for example +a) you must use Server::Find to locate the user the mode is operating on. Your mode handler may return 1 to handle the mode AND tell the core to display the mode change, e.g. '+aaa one two three' in the case of the mode for 'two', or it may return -1 to 'eat' the mode change, so the above example would become '+aa one three' after processing.Definition at line 607 of file modules.cpp.
References DoAddExtendedMode(), ModeMakeList(), and MT_CHANNEL.
{
        bool res = DoAddExtendedMode(modechar,MT_CHANNEL,false,1,1);
        if (res)
                ModeMakeList(modechar);
        return res;
}
bool Server::AddExtendedMode (char modechar, int type, bool requires_oper, int params_when_on, int params_when_off) [virtual]
Adds an extended mode letter which is parsed by a module. This allows modules to add extra mode letters, e.g. +x for hostcloak. the 'type' parameter is either MT_CHANNEL, MT_CLIENT, or MT_SERVER, to indicate wether the mode is a channel mode, a client mode, or a server mode. requires_oper is used with MT_CLIENT type modes only to indicate the mode can only be set or unset by an oper. If this is used for MT_CHANNEL type modes it is ignored. params_when_on is the number of modes to expect when the mode is turned on (for type MT_CHANNEL only), e.g. with mode +k, this would have a value of 1. the params_when_off value has a similar value to params_when_on, except it indicates the number of parameters to expect when the mode is disabled. Modes which act in a similar way to channel mode +l (e.g. require a parameter to enable, but not to disable) should use this parameter. The function returns false if the mode is unavailable, and will not attempt to allocate another character, as this will confuse users. This also means that as only one module can claim a specific mode character, the core does not need to keep track of which modules own which modes, which speeds up operation of the server. In this version, a mode can have at most one parameter, attempting to use more parameters will have undefined effects.Definition at line 579 of file modules.cpp.
References DEBUG, DoAddExtendedMode(), MT_CLIENT, and MT_SERVER.
{
        if (((modechar >= 'A') && (modechar <= 'Z')) || ((modechar >= 'a') && (modechar <= 'z')))
        {
                if (type == MT_SERVER)
                {
                        log(DEBUG,'*** API ERROR *** Modes of type MT_SERVER are reserved for future expansion');
                        return false;
                }
                if (((params_when_on>0) || (params_when_off>0)) && (type == MT_CLIENT))
                {
                        log(DEBUG,'*** API ERROR *** Parameters on MT_CLIENT modes are not supported');
                        return false;
                }
                if ((params_when_on>1) || (params_when_off>1))
                {
                        log(DEBUG,'*** API ERROR *** More than one parameter for an MT_CHANNEL mode is not yet supported');
                        return false;
                }
                return DoAddExtendedMode(modechar,type,requires_oper,params_when_on,params_when_off);
        }
        else
        {
                log(DEBUG,'*** API ERROR *** Muppet modechar detected.');
        }
        return false;
}
void Server::AddGLine (long duration, std::string source, std::string reason, std::string hostmask) [virtual]
Adds a G-line The G-line is propogated to all of the servers in the mesh and enforced as soon as it is added. The duration must be in seconds, however you can use the Server::CalcDuration method to convert durations into the 1w2d3h3m6s format used by /GLINE etc. The source is an arbitary string used to indicate who or what sent the data, usually this is the nickname of a person, or a server name.Definition at line 681 of file modules.cpp.
References add_gline(), and duration().
{
        add_gline(duration, source.c_str(), reason.c_str(), hostmask.c_str());
}
void Server::AddKLine (long duration, std::string source, std::string reason, std::string hostmask) [virtual]
Adds a K-line The K-line is enforced as soon as it is added. The duration must be in seconds, however you can use the Server::CalcDuration method to convert durations into the 1w2d3h3m6s format used by /GLINE etc. The source is an arbitary string used to indicate who or what sent the data, usually this is the nickname of a person, or a server name. Definition at line 696 of file modules.cpp.
References add_kline(), and duration().
{
        add_kline(duration, source.c_str(), reason.c_str(), hostmask.c_str());
}
void Server::AddQLine (long duration, std::string source, std::string reason, std::string nickname) [virtual]
Adds a Q-line The Q-line is propogated to all of the servers in the mesh and enforced as soon as it is added. The duration must be in seconds, however you can use the Server::CalcDuration method to convert durations into the 1w2d3h3m6s format used by /GLINE etc. The source is an arbitary string used to indicate who or what sent the data, usually this is the nickname of a person, or a server name. Definition at line 686 of file modules.cpp.
References add_qline(), and duration().
{
        add_qline(duration, source.c_str(), reason.c_str(), nickname.c_str());
}
void Server::AddZLine (long duration, std::string source, std::string reason, std::string ipaddr) [virtual]
Adds a Z-line The Z-line is propogated to all of the servers in the mesh and enforced as soon as it is added. The duration must be in seconds, however you can use the Server::CalcDuration method to convert durations into the 1w2d3h3m6s format used by /GLINE etc. The source is an arbitary string used to indicate who or what sent the data, usually this is the nickname of a person, or a server name. Definition at line 691 of file modules.cpp.
References add_zline(), and duration().
{
        add_zline(duration, source.c_str(), reason.c_str(), ipaddr.c_str());
}
long Server::CalcDuration (std::string duration) [virtual]
Calculates a duration This method will take a string containing a formatted duration (e.g. '1w2d') and return its value as a total number of seconds. This is the same function used internally by /GLINE etc to set the ban times.Definition at line 731 of file modules.cpp.
References duration().
{
        return duration(delta.c_str());
}
void Server::CallCommandHandler (std::string commandname, char ** parameters, int pcnt, userrec * user) [virtual]
Calls the handler for a command, either implemented by the core or by another module. You can use this function to trigger other commands in the ircd, such as PRIVMSG, JOIN, KICK etc, or even as a method of callback. By defining command names that are untypeable for users on irc (e.g. those which contain a or
) you may use them as callback identifiers. The first parameter to this method is the name of the command handler you wish to call, e.g. PRIVMSG. This will be a command handler previously registered by the core or wih AddCommand(). The second parameter is an array of parameters, and the third parameter is a count of parameters in the array. If you do not pass enough parameters to meet the minimum needed by the handler, the functiom will silently ignore it. The final parameter is the user executing the command handler, used for privilage checks, etc.Definition at line 429 of file modules.cpp.
{
        call_handler(commandname.c_str(),parameters,pcnt,user);
}
void Server::ChangeGECOS (userrec * user, std::string gecos) [virtual]
Change GECOS (fullname) of a user. You should always call this method to change a user's GECOS rather than writing directly to the fullname member of userrec, as any change applied via this method will be propogated to any linked servers.Definition at line 522 of file modules.cpp.
References ChangeName().
{
        ChangeName(user,gecos.c_str());
}
void Server::ChangeHost (userrec * user, std::string host) [virtual]
Change displayed hostname of a user. You should always call this method to change a user's host rather than writing directly to the dhost member of userrec, as any change applied via this method will be propogated to any linked servers.Definition at line 517 of file modules.cpp.
References ChangeDisplayedHost().
{
        ChangeDisplayedHost(user,host.c_str());
}
void Server::ChangeUserNick (userrec * user, std::string nickname) [virtual]
Forces a user nickchange. This command works similarly to SVSNICK, and can be used to implement Q-lines etc. If you specify an invalid nickname, the nick change will be dropped and the target user will receive the error numeric for it.Definition at line 414 of file modules.cpp.
{
        force_nickchange(user,nickname.c_str());
}
std::string Server::ChanMode (userrec * User, chanrec * Chan) [virtual]
Attempts to look up a user's privilages on a channel. This function will return a string containing either @, , +, or an empty string, representing the user's privilages upon the channel you specify.Definition at line 547 of file modules.cpp.
References cmode().
{
        return cmode(User,Chan);
}
bool Server::CommonChannels (userrec * u1, userrec * u2) [virtual]
Returns true if two users share a common channel. This method is used internally by the NICK and QUIT commands, and the Server::SendCommon method.Definition at line 495 of file modules.cpp.
References common_channels().
{
        return (common_channels(u1,u2) != 0);
}
int Server::CountUsers (chanrec * c) [virtual]
Returns a count of the number of users on a channel. This will NEVER be 0, as if the chanrec exists, it will have at least one user in the channel.Definition at line 615 of file modules.cpp.
{
        return usercount(c);
}
bool Server::DelELine (std::string hostmask) [virtual]
Deletes a local E-Line. Definition at line 726 of file modules.cpp.
References del_eline().
{
        del_eline(hostmask.c_str());
}
bool Server::DelGLine (std::string hostmask) [virtual]
Deletes a G-Line from all servers on the mesh. Definition at line 706 of file modules.cpp.
References del_gline().
{
        del_gline(hostmask.c_str());
}
bool Server::DelKLine (std::string hostmask) [virtual]
Deletes a local K-Line. Definition at line 721 of file modules.cpp.
References del_kline().
{
        del_kline(hostmask.c_str());
}
bool Server::DelQLine (std::string nickname) [virtual]
Deletes a Q-Line from all servers on the mesh. Definition at line 711 of file modules.cpp.
References del_qline().
{
        del_qline(nickname.c_str());
}
bool Server::DelZLine (std::string ipaddr) [virtual]
Deletes a Z-Line from all servers on the mesh. Definition at line 716 of file modules.cpp.
References del_zline().
{
        del_zline(ipaddr.c_str());
}
chanrec * Server::FindChannel (std::string channel) [virtual]
Attempts to look up a channel and return a pointer to it. This function will return NULL if the channel does not exist.Definition at line 542 of file modules.cpp.
{
        return FindChan(channel.c_str());
}
userrec * Server::FindDescriptor (int socket) [virtual]
Attempts to look up a nick using the file descriptor associated with that nick. This function will return NULL if the file descriptor is not associated with a valid user.Definition at line 537 of file modules.cpp.
References fd_ref_table.
{
        return (socket < 65536 ? fd_ref_table[socket] : NULL);
}
Module * Server::FindModule (std::string name) [virtual]
This function finds a module by name. You must provide the filename of the module. If the module cannot be found (is not loaded) the function will return NULL.Definition at line 809 of file modules.cpp.
References MODCOUNT, module_names, and modules.
{
        for (int i = 0; i <= MODCOUNT; i++)
        {
                if (module_names[i] == name)
                {
                        return modules[i];
                }
        }
        return NULL;
}
userrec * Server::FindNick (std::string nick) [virtual]
Attempts to look up a nick and return a pointer to it. This function will return NULL if the nick does not exist.Definition at line 532 of file modules.cpp.
{
        return Find(nick);
}
Admin Server::GetAdmin () [virtual]
Returns the information of the server as returned by the /ADMIN command. See the Admin class for further information of the return value. The members Admin::Nick, Admin::Email and Admin::Name contain the information for the server where the module is loaded.Definition at line 572 of file modules.cpp.
{
        return Admin(getadminname(),getadminemail(),getadminnick());
}
std::string Server::GetNetworkName () [virtual]
Returns the network name, global to all linked servers. Definition at line 562 of file modules.cpp.
{
        return getnetworkname();
}
std::string Server::GetServerDescription () [virtual]
Returns the server description string of the local server. Definition at line 567 of file modules.cpp.
{
        return getserverdesc();
}
std::string Server::GetServerName () [virtual]
Returns the server name of the server where the module is loaded. Definition at line 557 of file modules.cpp.
{
        return getservername();
}
chanuserlist Server::GetUsers (chanrec * chan) [virtual]
Fetches the userlist of a channel. This function must be here and not a member of userrec or chanrec due to include constraints.Definition at line 402 of file modules.cpp.
References chanuserlist, chanrec::GetUsers(), and list.
{
        chanuserlist userl;
        userl.clear();
        std::vector<char*> *list = chan->GetUsers();
        for (std::vector<char*>::iterator i = list->begin(); i != list->end(); i++)
        {
                char* o = *i;
                userl.push_back((userrec*)o);
        }
        return userl;
}
bool Server::IsNick (std::string nick) [virtual]
Returns true if a nick is valid. Nicks for unregistered connections will return false.Definition at line 527 of file modules.cpp.
References isnick().
{
        return (isnick(nick.c_str()) != 0);
}
bool Server::IsOnChannel (userrec * User, chanrec * Chan) [virtual]
Checks if a user is on a channel. This function will return true or false to indicate if user 'User' is on channel 'Chan'.Definition at line 552 of file modules.cpp.
References has_channel().
{
        return has_channel(User,Chan);
}
bool Server::IsUlined (std::string server) [virtual]
Returns true if the servername you give is ulined. ULined servers have extra privilages. They are allowed to change nicknames on remote servers, change modes of clients which are on remote servers and set modes of channels where there are no channel operators for that channel on the ulined server, amongst other things. Ulined server data is also broadcast across the mesh at all times as opposed to selectively messaged in the case of normal servers, as many ulined server types (such as services) do not support meshed links and must operate in this manner.Definition at line 424 of file modules.cpp.
References is_uline().
{
        return is_uline(server.c_str());
}
bool Server::IsValidMask (std::string mask) [virtual]
Returns true if a nick!ident string is correctly formatted, false if otherwise. Definition at line 736 of file modules.cpp.
{
        const char* dest = mask.c_str();
        if (strchr(dest,'!')==0)
                return false;
        if (strchr(dest,'@')==0)
                return false;
        for (int i = 0; i < strlen(dest); i++)
                if (dest[i] < 32)
                        return false;
        for (int i = 0; i < strlen(dest); i++)
                if (dest[i] > 126)
                        return false;
        int c = 0;
        for (int i = 0; i < strlen(dest); i++)
                if (dest[i] == '!')
                        c++;
        if (c>1)
                return false;
        c = 0;
        for (int i = 0; i < strlen(dest); i++)
                if (dest[i] == '@')
                        c++;
        if (c>1)
                return false;
        return true;
}
chanrec * Server::JoinUserToChannel (userrec * user, std::string cname, std::string key) [virtual]
Forces a user to join a channel. This is similar to svsjoin and can be used to implement redirection, etc. On success, the return value is a valid pointer to a chanrec* of the channel the user was joined to. On failure, the result is NULL.Definition at line 392 of file modules.cpp.
{
        return add_channel(user,cname.c_str(),key.c_str(),false);
}
void Server::Log (int level, std::string s) [virtual]
Writes a log string. This method writes a line of text to the log. If the level given is lower than the level given in the configuration, this command has no effect.Definition at line 434 of file modules.cpp.
{
        log(level,'%s',s.c_str());
}
bool Server::MatchText (std::string sliteral, std::string spattern) [virtual]
Matches text against a glob pattern. Uses the ircd's internal matching function to match string against a globbing pattern, e.g. *!*@*.com Returns true if the literal successfully matches the pattern, false if otherwise.Definition at line 379 of file modules.cpp.
{
        char literal[MAXBUF],pattern[MAXBUF];
        strlcpy(literal,sliteral.c_str(),MAXBUF);
        strlcpy(pattern,spattern.c_str(),MAXBUF);
        return match(literal,pattern);
}
bool Server::MeshCheckChan (chanrec * c, std::string servername) [virtual]
This function is used to check if any users on channel c are on server servername. This is used internally by PRIVMSG etc. You should not need to use it.Definition at line 791 of file modules.cpp.
{
        if (c)
        {
                return ChanAnyOnThisServer(c,(char*)servername.c_str());
        }
        else return false;
}
bool Server::MeshCheckCommon (userrec * u, std::string servername) [virtual]
This function is used to check if user u has any channels in common with users on servername. This is used internally by Server::MeshSendCommon. You should very rarely need to use it.Definition at line 800 of file modules.cpp.
{
        if (u)
        {
                return CommonOnThisServer(u,(char*)servername.c_str());
        }
        else return false;
}
void Server::MeshSendAll (std::string text) [virtual]
Sends a line of text to all connected servers. If a server is not directly reachable, the core deals with routing the message, and will also deal with failures transparently.Definition at line 765 of file modules.cpp.
{
        NetSendToAll((char*)text.c_str());
}
void Server::MeshSendAllAlive (std::string text) [virtual]
This function is equivalent to Server::MeshSendToAll except it will only route to servers which are directly routable. Definition at line 776 of file modules.cpp.
{
        NetSendToAllAlive((char*)text.c_str());
}
void Server::MeshSendAllExcept (std::string target, std::string text) [virtual]
This function sends to all servers EXCEPT the one you specify. You should usually use this function to send messages, specifying the SENDER of your message as 'target'. This will prevent message loops.Definition at line 786 of file modules.cpp.
{
        NetSendToAllExcept(target.c_str(),(char*)text.c_str());
}
void Server::MeshSendCommon (userrec * user, std::string text) [virtual]
This method sends a line of text to all servers who have users which share common channels with the user you provide. For example, if user A is on server A, and they are on channels #one and #two, and user B is on server B, and also on channel #one, but user C is on server C and on neither #one or #two, this function will cause the text to only be sent to server B. However, if server B is only reachable via C, it will route it to C (you do not have to worry about this routing, it is done transparently, but its good to know how things work!)Definition at line 770 of file modules.cpp.
{
        if (user)
                NetSendToCommon(user,(char*)text.c_str());
}
void Server::MeshSendUnicast (std::string destination, std::string text) [virtual]
This function sends a line of text directly to a server. If the server is not directly routable at this time, the server attempts to route text through the mesh.Definition at line 781 of file modules.cpp.
{
        NetSendToOne((char*)destination.c_str(),(char*)text.c_str());
}
chanrec * Server::PartUserFromChannel (userrec * user, std::string cname, std::string reason) [virtual]
Forces a user to part a channel. This is similar to svspart and can be used to implement redirection, etc. Although the return value of this function is a pointer to a channel record, the returned data is undefined and should not be read or written to. This behaviour may be changed in a future version.Definition at line 397 of file modules.cpp.
{
        return del_channel(user,cname.c_str(),reason.c_str(),false);
}
bool Server::PseudoToUser (userrec * alive, userrec * zombie, std::string message) [virtual]
This user takes one user, and switches their file descriptor with another user, so that one user 'becomes' the other. The user in 'alive' is booted off the server with the given message. The user referred to by 'zombie' should have previously been locked with Server::ZombifyUser, otherwise stale sockets and file descriptor leaks can occur. After this call, the pointer to alive will be invalid, and the pointer to zombie will be equivalent in effect to the old pointer to alive.Definition at line 651 of file modules.cpp.
References ucrec::channel, userrec::chans, userrec::ClearBuffer(), connection::fd, FD_MAGIC_NUMBER, fd_ref_table, connection::host, userrec::ident, chanrec::name, userrec::nick, chanrec::setby, chanrec::topic, and chanrec::topicset.
{
        zombie->fd = alive->fd;
        alive->fd = FD_MAGIC_NUMBER;
        alive->ClearBuffer();
        Write(zombie->fd,':%s!%s@%s NICK %s',alive->nick,alive->ident,alive->host,zombie->nick);
        kill_link(alive,message.c_str());
        fd_ref_table[zombie->fd] = zombie;
        for (int i = 0; i != MAXCHANS; i++)
        {
                if (zombie->chans[i].channel != NULL)
                {
                        if (zombie->chans[i].channel->name)
                        {
                                chanrec* Ptr = zombie->chans[i].channel;
                                WriteFrom(zombie->fd,zombie,'JOIN %s',Ptr->name);
                                if (Ptr->topicset)
                                {
                                        WriteServ(zombie->fd,'332 %s %s :%s', zombie->nick, Ptr->name, Ptr->topic);
                                        WriteServ(zombie->fd,'333 %s %s %s %d', zombie->nick, Ptr->name, Ptr->setby, Ptr->topicset);
                                }
                                userlist(zombie,Ptr);
                                WriteServ(zombie->fd,'366 %s %s :End of /NAMES list.', zombie->nick, Ptr->name);
                        }
                }
        }
}
void Server::QuitUser (userrec * user, std::string reason) [virtual]
Forces a user to quit with the specified reason. To the user, it will appear as if they typed /QUIT themselves, except for the fact that this function may bypass the quit prefix specified in the config file.
WARNING!
Once you call this function, userrec* user will immediately become INVALID. You MUST NOT write to, or read from this pointer after calling the QuitUser method UNDER ANY CIRCUMSTANCES! The best course of action after calling this method is to immediately bail from your handler.Definition at line 419 of file modules.cpp.
{
        kill_link(user,reason.c_str());
}
void Server::Send (int Socket, std::string s) [virtual]
Sends a line of text down a TCP/IP socket. This method writes a line of text to an established socket, cutting it to 510 characters plus a carriage return and linefeed if required.Definition at line 449 of file modules.cpp.
{
        Write(Socket,'%s',s.c_str());
}
void Server::SendChannel (userrec * User, chanrec * Channel, std::string s, bool IncludeSender) [virtual]
Sends text from a user to a channel (mulicast). This method writes a line of text to a channel, with the given user's nick/ident /host combination prepended, as used in PRIVMSG etc commands (see RFC 1459). If the IncludeSender flag is set, then the text is also sent back to the user from which it originated, as seen in MODE (see RFC 1459).Definition at line 483 of file modules.cpp.
{
        if (IncludeSender)
        {
                WriteChannel(Channel,User,'%s',s.c_str());
        }
        else
        {
                ChanExceptSender(Channel,User,'%s',s.c_str());
        }
}
void Server::SendChannelServerNotice (std::string ServName, chanrec * Channel, std::string text) [virtual]
Writes text to a channel, but from a server, including all. This can be used to send server notices to a group of users.Definition at line 478 of file modules.cpp.
{
        WriteChannelWithServ((char*)ServName.c_str(), Channel, '%s', text.c_str());
}
void Server::SendCommon (userrec * User, std::string text, bool IncludeSender) [virtual]
Sends text from a user to one or more channels (mulicast). This method writes a line of text to all users which share a common channel with a given user, with the user's nick/ident/host combination prepended, as used in PRIVMSG etc commands (see RFC 1459). If the IncludeSender flag is set, then the text is also sent back to the user from which it originated, as seen in NICK (see RFC 1459). Otherwise, it is only sent to the other recipients, as seen in QUIT.Definition at line 500 of file modules.cpp.
{
        if (IncludeSender)
        {
                WriteCommon(User,'%s',text.c_str());
        }
        else
        {
                WriteCommonExcept(User,'%s',text.c_str());
        }
}
void Server::SendFrom (int Socket, userrec * User, std::string s) [virtual]
Sends text from a user to a socket. This method writes a line of text to an established socket, with the given user's nick/ident /host combination prepended, as used in PRIVSG etc commands (see RFC 1459)Definition at line 459 of file modules.cpp.
{
        WriteFrom(Socket,User,'%s',s.c_str());
}
void Server::SendMode (char ** parameters, int pcnt, userrec * user) [virtual]
Sends a servermode. you must format the parameters array with the target, modes and parameters for those modes.
For example:
char *modes[3];
modes[0] = ChannelName;
modes[1] = '+o';
modes[2] = user->nick;
Srv->SendMode(modes,3,user);
The modes will originate from the server where the command was issued, however responses (e.g. numerics) will be sent to the user you provide as the third parameter. You must be sure to get the number of parameters correct in the pcnt parameter otherwise you could leave your server in an unstable state!Definition at line 444 of file modules.cpp.
References server_mode().
{
        server_mode(parameters,pcnt,user);
}
void Server::SendOpers (std::string s) [virtual]
Sends text to all opers. This method sends a server notice to all opers with the usermode +s.Definition at line 374 of file modules.cpp.
{
        WriteOpers('%s',s.c_str());
}
void Server::SendServ (int Socket, std::string s) [virtual]
Sends text from the server to a socket. This method writes a line of text to an established socket, with the servername prepended as used by numerics (see RFC 1459)Definition at line 454 of file modules.cpp.
{
        WriteServ(Socket,'%s',s.c_str());
}
void Server::SendTo (userrec * Source, userrec * Dest, std::string s) [virtual]
Sends text from a user to another user. This method writes a line of text to a user, with a user's nick/ident /host combination prepended, as used in PRIVMSG etc commands (see RFC 1459) If you specify NULL as the source, then the data will originate from the local server, e.g. instead of:
:user!ident TEXT
The format will become:
:localserver TEXT
Which is useful for numerics and server notices to single users, etc.Definition at line 464 of file modules.cpp.
References connection::fd.
{
        if (!Source)
        {
                // if source is NULL, then the message originates from the local server
                Write(Dest->fd,':%s %s',this->GetServerName().c_str(),s.c_str());
        }
        else
        {
                // otherwise it comes from the user specified
                WriteTo(Source,Dest,'%s',s.c_str());
        }
}
void Server::SendToModeMask (std::string modes, int flags, std::string text) [virtual]
Sends to all users matching a mode mask You must specify one or more usermodes as the first parameter. These can be RFC specified modes such as +i, or module provided modes, including ones provided by your own module. In the second parameter you must place a flag value which indicates wether the modes you have given will be logically ANDed or OR'ed. You may use one of either WM_AND or WM_OR. for example, if you were to use:
Serv->SendToModeMask('xi', WM_OR, 'm00');
Then the text 'm00' will be sent to all users with EITHER mode x or i. Conversely if you used WM_AND, the user must have both modes set to receive the message.Definition at line 387 of file modules.cpp.
{
        WriteMode(modes.c_str(),flags,'%s',text.c_str());
}
void Server::SendWallops (userrec * User, std::string text) [virtual]
Sends a WALLOPS message. This method writes a WALLOPS message to all users with the +w flag, originating from the specified user.Definition at line 512 of file modules.cpp.
{
        WriteWallOps(User,false,'%s',text.c_str());
}
bool Server::UserToPseudo (userrec * user, std::string message) [virtual]
Remove a user's connection to the irc server, but leave their client in existence in the user hash. When you call this function, the user's file descriptor will be replaced with the value of FD_MAGIC_NUMBER and their old file descriptor will be closed. This idle client will remain until it is restored with a valid file descriptor, or is removed from IRC by an operator After this call, the pointer to user will be invalid.Definition at line 621 of file modules.cpp.
References userrec::ClearBuffer(), DEBUG, connection::fd, FD_MAGIC_NUMBER, connection::host, and userrec::ident.
{
        unsigned int old_fd = user->fd;
        user->fd = FD_MAGIC_NUMBER;
        user->ClearBuffer();
        Write(old_fd,'ERROR :Closing link (%s@%s) [%s]',user->ident,user->host,message.c_str());
#ifdef USE_KQUEUE
        struct kevent ke;
        EV_SET(&ke, old_fd, EVFILT_READ, EV_DELETE, 0, 0, NULL);
        int i = kevent(kq, &ke, 1, 0, 0, NULL);
        if (i == -1)
        {
                log(DEBUG,'kqueue: Failed to remove user from queue!');
        }
#endif
#ifdef USE_EPOLL
        struct epoll_event ev;
        ev.events = EPOLLIN | EPOLLET;
        ev.data.fd = old_fd;
        int i = epoll_ctl(ep, EPOLL_CTL_DEL, old_fd, &ev);
        if (i < 0)
        {
                log(DEBUG,'epoll: List deletion failure!');
        }
#endif
        shutdown(old_fd,2);
        close(old_fd);
}
Author
Generated automatically by Doxygen for InspIRCd from the source code.