.TH "serverrec" 3 "26 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serverrec \- A class that defines the local server or a remote server.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <servers.h>\fP
.PP
Inherits \fBconnection\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBserverrec\fP ()"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "\fBserverrec\fP (char *n, long ver, bool jupe)"
.br
.RI "\fIConstructor which initialises some of the main variables. \fP"
.ti -1c
.RI "\fB~serverrec\fP ()"
.br
.RI "\fIDestructor. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [MAXBUF]"
.br
.RI "\fIserver name \fP"
.ti -1c
.RI "long \fBpingtime\fP"
.br
.RI "\fIlast ping response (ms) \fP"
.ti -1c
.RI "long \fBusercount_i\fP"
.br
.RI "\fIinvisible users on server \fP"
.ti -1c
.RI "long \fBusercount\fP"
.br
.RI "\fInon-invisible users on server \fP"
.ti -1c
.RI "long \fBopercount\fP"
.br
.RI "\fIopers on server \fP"
.ti -1c
.RI "int \fBhops_away\fP"
.br
.RI "\fInumber of hops away (for quick access) \fP"
.ti -1c
.RI "long \fBversion\fP"
.br
.RI "\fIircd version \fP"
.ti -1c
.RI "bool \fBjupiter\fP"
.br
.RI "\fIis a JUPE server (faked to enforce a server ban) \fP"
.ti -1c
.RI "char \fBdescription\fP [MAXBUF]"
.br
.RI "\fIDescription of the server. \fP"
.ti -1c
.RI "char \fBnickserv\fP [NICKMAX]"
.br
.RI "\fIHolds nickserv's name on U:lined (services) servers (this is a kludge for ircservices which ASSUMES things :/). \fP"
.ti -1c
.RI "bool \fBsync_soon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class that defines the local server or a remote server. Definition at line 30 of file servers.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "serverrec::serverrec ()"
.PP
Constructor. Definition at line 26 of file servers.cpp.
.PP
References connection::fd, hops_away, jupiter, connection::lastping, name, nickserv, opercount, pingtime, connection::signon, sync_soon, TIME, usercount, usercount_i, and version.
.PP
.nf
27 {
28         strlcpy(name,'',256);
29         pingtime = 0;
30         lastping = TIME;
31         usercount_i = usercount = opercount = version = 0;
32         hops_away = 1;
33         signon = TIME;
34         jupiter = false;
35         fd = 0;
36         sync_soon = false;
37         strlcpy(nickserv,'',NICKMAX);
38 }
.fi
.SS "serverrec::serverrec (char * n, long ver, bool jupe)"
.PP
Constructor which initialises some of the main variables. Definition at line 45 of file servers.cpp.
.PP
References connection::fd, hops_away, jupiter, connection::lastping, name, nickserv, opercount, connection::signon, sync_soon, TIME, usercount, usercount_i, and version.
.PP
.nf
46 {
47         strlcpy(name,n,256);
48         lastping = TIME;
49         usercount_i = usercount = opercount = 0;
50         version = ver;
51         hops_away = 1;
52         signon = TIME;
53         jupiter = jupe;
54         fd = 0;
55         sync_soon = false;
56         strlcpy(nickserv,'',NICKMAX);
57 }
.fi
.SS "serverrec::~\fBserverrec\fP ()"
.PP
Destructor. Definition at line 41 of file servers.cpp.
.PP
.nf
42 {
43 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "char \fBserverrec::description\fP[MAXBUF]"
.PP
Description of the server. Definition at line 61 of file servers.h.
.SS "int \fBserverrec::hops_away\fP"
.PP
number of hops away (for quick access) Definition at line 51 of file servers.h.
.PP
Referenced by serverrec().
.SS "bool \fBserverrec::jupiter\fP"
.PP
is a JUPE server (faked to enforce a server ban) Definition at line 57 of file servers.h.
.PP
Referenced by serverrec().
.SS "char \fBserverrec::name\fP[MAXBUF]"
.PP
server name Definition at line 36 of file servers.h.
.PP
Referenced by serverrec().
.SS "char \fBserverrec::nickserv\fP[NICKMAX]"
.PP
Holds nickserv's name on U:lined (services) servers (this is a kludge for ircservices which ASSUMES things :/). Definition at line 65 of file servers.h.
.PP
Referenced by serverrec().
.SS "long \fBserverrec::opercount\fP"
.PP
opers on server Definition at line 48 of file servers.h.
.PP
Referenced by serverrec().
.SS "long \fBserverrec::pingtime\fP"
.PP
last ping response (ms) Definition at line 39 of file servers.h.
.PP
Referenced by serverrec().
.SS "bool \fBserverrec::sync_soon\fP"
.PP
Definition at line 67 of file servers.h.
.PP
Referenced by serverrec().
.SS "long \fBserverrec::usercount\fP"
.PP
non-invisible users on server Definition at line 45 of file servers.h.
.PP
Referenced by serverrec().
.SS "long \fBserverrec::usercount_i\fP"
.PP
invisible users on server Definition at line 42 of file servers.h.
.PP
Referenced by serverrec().
.SS "long \fBserverrec::version\fP"
.PP
ircd version Definition at line 54 of file servers.h.
.PP
Referenced by serverrec().

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
