.TH "socket.h" 3 "12 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <netinet/in.h>\fP
.br
\fC#include <poll.h>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInspSocket\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBInspSocketState\fP { \fBI_DISCONNECTED\fP, \fBI_CONNECTING\fP, \fBI_CONNECTED\fP, \fBI_LISTENING\fP, \fBI_ERROR\fP }"
.br
.ti -1c
.RI "enum \fBInspSocketError\fP { \fBI_ERR_TIMEOUT\fP, \fBI_ERR_SOCKET\fP, \fBI_ERR_CONNECT\fP, \fBI_ERR_BIND\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBInspSocketError\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fII_ERR_TIMEOUT \fP\fP
.TP
\fB\fII_ERR_SOCKET \fP\fP
.TP
\fB\fII_ERR_CONNECT \fP\fP
.TP
\fB\fII_ERR_BIND \fP\fP

.PP
Definition at line 28 of file socket.h.
.PP
.nf
28 { I_ERR_TIMEOUT, I_ERR_SOCKET, I_ERR_CONNECT, I_ERR_BIND };
.fi
.PP
.SS "enum \fBInspSocketState\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fII_DISCONNECTED \fP\fP
.TP
\fB\fII_CONNECTING \fP\fP
.TP
\fB\fII_CONNECTED \fP\fP
.TP
\fB\fII_LISTENING \fP\fP
.TP
\fB\fII_ERROR \fP\fP

.PP
Definition at line 27 of file socket.h.
.PP
.nf
27 { I_DISCONNECTED, I_CONNECTING, I_CONNECTED, I_LISTENING, I_ERROR };
.fi
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
