SocketEngine
NAME
SocketEngine - The actual socketengine class presents the same interface on all operating systems, but its private members and internal behaviour should be treated as blackboxed, and vary from system to system and upon the config settings chosen by the server admin.
SYNOPSIS
#include <socketengine.h>
Public Member Functions
SocketEngine ()
Constructor The constructor transparently initializes the socket engine which the ircd is using.
~SocketEngine ()
Destructor The destructor transparently tidies up any resources used by the socket engine.
bool AddFd (int fd, bool readable, char type)
Add a file descriptor to the engine Use AddFd to add a file descriptor to the engine and have the socket engine monitor it.
char GetType (int fd)
Returns the type value for this file descriptor This function masks off the X_READBIT value so that the type of the socket can be obtained.
bool DelFd (int fd)
Delete a file descriptor f rom the engine This function call deletes a file descriptor from the engine, returning true if it succeeded and false if it failed.
bool Wait (std::vector< int > &fdlist)
Waits for an event.
std::string GetName ()
Returns the socket engines name This returns the name of the engine for use in /VERSION responses.
Private Attributes
std::vector< int > fds
int EngineHandle
kevent ke_list [65535]
timespec ts
Detailed Description
The actual socketengine class presents the same interface on all operating systems, but its private members and internal behaviour should be treated as blackboxed, and vary from system to system and upon the config settings chosen by the server admin.
The current version supports select, epoll and kqueue.
Definition at line 66 of file socketengine.h.
Constructor & Destructor Documentation
SocketEngine::SocketEngine ()
Constructor The constructor transparently initializes the socket engine which the ircd is using.
Please note that if there is a catastrophic failure (for example, you try and enable epoll on a 2.4 linux kernel) then this function may bail back to the shell.
Definition at line 35 of file socketengine.cpp.
References DEBUG, EngineHandle, and log().
{
        log(DEBUG,'SocketEngine::SocketEngine()');
#ifdef USE_EPOLL
        EngineHandle = epoll_create(65535);
#endif
#ifdef USE_KQUEUE
        EngineHandle = kqueue();
#endif
}
SocketEngine::~SocketEngine ()
Destructor The destructor transparently tidies up any resources used by the socket engine.
Definition at line 46 of file socketengine.cpp.
References DEBUG, EngineHandle, and log().
{
        log(DEBUG,'SocketEngine::~SocketEngine()');
#ifdef USE_EPOLL
        close(EngineHandle);
#endif
#ifdef USE_KQUEUE
        close(EngineHandle);
#endif
}
Member Function Documentation
bool SocketEngine::AddFd (int fd, bool readable, char type)
Add a file descriptor to the engine Use AddFd to add a file descriptor to the engine and have the socket engine monitor it.
You must provide a type (see the consts in socketengine.h) and a boolean flag to indicate wether to watch this fd for read or write events (there is currently no need for support of both).
Definition at line 65 of file socketengine.cpp.
References DEBUG, EngineHandle, fds, log(), ref, and X_READBIT.
Referenced by InspSocket::InspSocket(), and InspSocket::Poll().
{
        if ((fd < 0) || (fd > 65535))
                return false;
        this->fds.push_back(fd);
        ref[fd] = type;
        if (readable)
        {
                log(DEBUG,'Set readbit');
                ref[fd] |= X_READBIT;
        }
        log(DEBUG,'Add socket %d',fd);
#ifdef USE_EPOLL
        struct epoll_event ev;
        log(DEBUG,'epoll: Add socket to events, ep=%d socket=%d',EngineHandle,fd);
        readable ? ev.events = EPOLLIN | EPOLLET : ev.events = EPOLLOUT | EPOLLET;
        ev.data.fd = fd;
        int i = epoll_ctl(EngineHandle, EPOLL_CTL_ADD, fd, &ev);
        if (i < 0)
        {
                log(DEBUG,'epoll: List insertion failure!');
                return false;
        }
#endif
#ifdef USE_KQUEUE
        struct kevent ke;
        log(DEBUG,'kqueue: Add socket to events, kq=%d socket=%d',EngineHandle,fd);
        EV_SET(&ke, fd, readable ? EVFILT_READ : EVFILT_WRITE, EV_ADD, 0, 0, NULL);
        int i = kevent(EngineHandle, &ke, 1, 0, 0, NULL);
        if (i == -1)
        {
                log(DEBUG,'kqueue: List insertion failure!');
                return false;
        }
#endif
return true;
}
bool SocketEngine::DelFd (int fd)
Delete a file descriptor f rom the engine This function call deletes a file descriptor from the engine, returning true if it succeeded and false if it failed.
Definition at line 103 of file socketengine.cpp.
References DEBUG, EngineHandle, fds, log(), ref, and X_READBIT.
Referenced by InspSocket::Poll(), and Server::UserToPseudo().
{
        log(DEBUG,'SocketEngine::DelFd(%d)',fd);
        if ((fd < 0) || (fd > 65535))
                return false;
        bool found = false;
        for (std::vector<int>::iterator i = fds.begin(); i != fds.end(); i++)
        {
                if (*i == fd)
                {
                        fds.erase(i);
                        log(DEBUG,'Deleted fd %d',fd);
                        found = true;
                        break;
                }
        }
#ifdef USE_KQUEUE
        struct kevent ke;
        EV_SET(&ke, fd, ref[fd] & X_READBIT ? EVFILT_READ : EVFILT_WRITE, EV_DELETE, 0, 0, NULL);
        int i = kevent(EngineHandle, &ke, 1, 0, 0, NULL);
        if (i == -1)
        {
                log(DEBUG,'kqueue: Failed to remove socket from queue!');
                return false;
        }
#endif
#ifdef USE_EPOLL
        struct epoll_event ev;
        ref[fd] && X_READBIT ? ev.events = EPOLLIN | EPOLLET : ev.events = EPOLLOUT | EPOLLET;
        ev.data.fd = fd;
        int i = epoll_ctl(EngineHandle, EPOLL_CTL_DEL, fd, &ev);
        if (i < 0)
        {
                log(DEBUG,'epoll: List deletion failure!');
                return false;
        }
#endif
        ref[fd] = 0;
        return found;
}
std::string SocketEngine::GetName ()
Returns the socket engines name This returns the name of the engine for use in /VERSION responses.
Definition at line 193 of file socketengine.cpp.
{
#ifdef USE_SELECT
        return 'select';
#endif
#ifdef USE_KQUEUE
        return 'kqueue';
#endif
#ifdef USE_EPOLL
        return 'epoll';
#endif
        return 'misconfigured';
}
char SocketEngine::GetType (int fd)
Returns the type value for this file descriptor This function masks off the X_READBIT value so that the type of the socket can be obtained.
The core uses this to decide where to dispatch the event to. Please note that some engines such as select() have an upper limit of 1024 descriptors which may be active at any one time, where others such as kqueue have no practical limits at all.
Definition at line 57 of file socketengine.cpp.
References ref, and X_EMPTY_SLOT.
{
        if ((fd < 0) || (fd > 65535))
                return X_EMPTY_SLOT;
        /* Mask off the top bit used for 'read/write' state */
        return (ref[fd] & ~0x80);
}
bool SocketEngine::Wait (std::vector< int > & fdlist)
Waits for an event.
Please note that this doesnt wait long, only a couple of milliseconds. It returns a list of active file descriptors in the vector fdlist which the core may then act upon.
Definition at line 146 of file socketengine.cpp.
References EngineHandle, fds, ke_list, ref, ts, and X_READBIT.
{
        fdlist.clear();
#ifdef USE_SELECT
        FD_ZERO(&wfdset);
        FD_ZERO(&rfdset);
        timeval tval;
        int sresult;
        for (unsigned int a = 0; a < fds.size(); a++)
        {
                if (ref[fds[a]] & X_READBIT)
                {
                        FD_SET (fds[a], &rfdset);
                }
                else
                {
                        FD_SET (fds[a], &wfdset);
                }
                
        }
        tval.tv_sec = 0;
        tval.tv_usec = 100L;
        sresult = select(FD_SETSIZE, &rfdset, &wfdset, NULL, &tval);
        if (sresult > 0)
        {
                for (unsigned int a = 0; a < fds.size(); a++)
                {
                        if ((FD_ISSET (fds[a], &rfdset)) || (FD_ISSET (fds[a], &wfdset)))
                                fdlist.push_back(fds[a]);
                }
        }
#endif
#ifdef USE_KQUEUE
        ts.tv_nsec = 10000L;
        ts.tv_sec = 0;
        int i = kevent(EngineHandle, NULL, 0, &ke_list[0], 65535, &ts);
        for (int j = 0; j < i; j++)
                fdlist.push_back(ke_list[j].ident);
#endif
#ifdef USE_EPOLL
        int i = epoll_wait(EngineHandle, events, 65535, 100);
        for (int j = 0; j < i; j++)
                fdlist.push_back(events[j].data.fd);
#endif
        return true;
}
Member Data Documentation
int SocketEngine::EngineHandle [private]
Definition at line 69 of file socketengine.h.
Referenced by AddFd(), DelFd(), SocketEngine(), Wait(), and ~SocketEngine().
std::vector<int> SocketEngine::fds [private]
Definition at line 68 of file socketengine.h.
Referenced by AddFd(), DelFd(), and Wait().
struct kevent SocketEngine::ke_list[65535] [private]
Definition at line 74 of file socketengine.h.
Referenced by Wait().
struct timespec SocketEngine::ts [private]
Definition at line 75 of file socketengine.h.
Referenced by Wait().
Author
Generated automatically by Doxygen for InspIRCd from the source code.