.TH "socketengine.cpp" 3 "15 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socketengine.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'globals.h'\fP
.br
\fC#include 'inspircd.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'socketengine.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBref\fP [65535]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "char \fBref\fP[65535]"
.PP
Definition at line 33 of file socketengine.cpp.
.PP
Referenced by SocketEngine::AddFd(), SocketEngine::DelFd(), SocketEngine::GetType(), and SocketEngine::Wait().
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
