.TH "StrHashComp" 3 "16 Apr 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StrHashComp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const string &s1, const string &s2) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool StrHashComp::operator() (const string & s1, const string & s2) const\fC [inline]\fP"
.PP
Definition at line 146 of file modules.cpp.
.PP
.nf
147         {
148                 char a[MAXBUF],b[MAXBUF];
149                 strlcpy(a,s1.c_str(),MAXBUF);
150                 strlcpy(b,s2.c_str(),MAXBUF);
151                 return (strcasecmp(a,b) == 0);
152         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
