.TH "StrHashComp" 3 "2 May 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StrHashComp \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const string &s1, const string &s2) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool StrHashComp::operator() (const string & s1, const string & s2) const\fC [inline]\fP"
.PP
Definition at line 122 of file modules.cpp.
.PP
.nf
123         {
124                 char a[MAXBUF],b[MAXBUF];
125                 strcpy(a,s1.c_str());
126                 strcpy(b,s2.c_str());
127                 return (strcasecmp(a,b) == 0);
128         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
