.TH "typedefs.h" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typedefs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'users.h'\fP
.br
\fC#include 'channels.h'\fP
.br
\fC#include 'hashcomp.h'\fP
.br
\fC#include 'inspstring.h'\fP
.br
\fC#include 'ctables.h'\fP
.br
\fC#include 'inspircd.h'\fP
.br
\fC#include 'modules.h'\fP
.br
\fC#include 'globals.h'\fP
.br
\fC#include 'inspircd_config.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <ext/hash_map>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef nspace::hash_map< \fBstd::string\fP, \fBuserrec\fP *, nspace::hash< \fBstring\fP >, \fBirc::StrHashComp\fP > \fBuser_hash\fP"
.br
.ti -1c
.RI "typedef nspace::hash_map< \fBstd::string\fP, \fBchanrec\fP *, nspace::hash< \fBstring\fP >, \fBirc::StrHashComp\fP > \fBchan_hash\fP"
.br
.ti -1c
.RI "typedef nspace::hash_map< in_addr, \fBstring\fP *, nspace::hash< in_addr >, \fBirc::InAddr_HashComp\fP > \fBaddress_cache\fP"
.br
.ti -1c
.RI "typedef nspace::hash_map< \fBstd::string\fP, \fBWhoWasUser\fP *, nspace::hash< \fBstring\fP >, \fBirc::StrHashComp\fP > \fBwhowas_hash\fP"
.br
.ti -1c
.RI "typedef std::deque< \fBcommand_t\fP > \fBcommand_table\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBstd::string\fP > \fBservernamelist\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBExtMode\fP > \fBExtModeList\fP"
.br
.ti -1c
.RI "typedef ExtModeList::iterator \fBExtModeListIter\fP"
.br
.ti -1c
.RI "typedef std::deque< \fBstd::string\fP > \fBfile_cache\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef nspace::hash_map<in_addr,\fBstring\fP*, nspace::hash<in_addr>, \fBirc::InAddr_HashComp\fP> \fBaddress_cache\fP"
.PP
Definition at line 22 of file typedefs.h.
.SS "typedef nspace::hash_map<\fBstd::string\fP, \fBchanrec\fP*, nspace::hash<\fBstring\fP>, \fBirc::StrHashComp\fP> \fBchan_hash\fP"
.PP
Definition at line 21 of file typedefs.h.
.SS "typedef std::deque<\fBcommand_t\fP> \fBcommand_table\fP"
.PP
Definition at line 24 of file typedefs.h.
.SS "typedef std::vector<\fBExtMode\fP> \fBExtModeList\fP"
.PP
Definition at line 26 of file typedefs.h.
.SS "typedef ExtModeList::iterator \fBExtModeListIter\fP"
.PP
Definition at line 27 of file typedefs.h.
.SS "typedef std::deque<\fBstd::string\fP> \fBfile_cache\fP"
.PP
Definition at line 28 of file typedefs.h.
.SS "typedef std::vector<\fBstd::string\fP> \fBservernamelist\fP"
.PP
Definition at line 25 of file typedefs.h.
.SS "typedef nspace::hash_map<\fBstd::string\fP, \fBuserrec\fP*, nspace::hash<\fBstring\fP>, \fBirc::StrHashComp\fP> \fBuser_hash\fP"
.PP
Definition at line 20 of file typedefs.h.
.SS "typedef nspace::hash_map<\fBstd::string\fP, \fBWhoWasUser\fP*, nspace::hash<\fBstring\fP>, \fBirc::StrHashComp\fP> \fBwhowas_hash\fP"
.PP
Definition at line 23 of file typedefs.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
