.TH "userprocess.h" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userprocess.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'users.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCheckDie\fP ()"
.br
.ti -1c
.RI "void \fBLoadAllModules\fP ()"
.br
.ti -1c
.RI "void \fBCheckRoot\fP ()"
.br
.ti -1c
.RI "void \fBOpenLog\fP (char **argv, int argc)"
.br
.ti -1c
.RI "bool \fBDoBackgroundUserStuff\fP (time_t \fBTIME\fP)"
.br
.ti -1c
.RI "void \fBProcessUser\fP (\fBuserrec\fP *cu)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void CheckDie ()"
.PP
.SS "void CheckRoot ()"
.PP
.SS "bool DoBackgroundUserStuff (time_t TIME)"
.PP
.SS "void LoadAllModules ()"
.PP
.SS "void OpenLog (char ** argv, int argc)"
.PP
.SS "void ProcessUser (\fBuserrec\fP * cu)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
