.TH "users.cpp" 3 "14 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
users.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'channels.h'\fP
.br
\fC#include 'connection.h'\fP
.br
\fC#include 'users.h'\fP
.br
\fC#include 'inspircd.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'inspstring.h'\fP
.br
\fC#include 'commands.h'\fP
.br
\fC#include 'helperfuncs.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBServerConfig\fP * \fBConfig\fP"
.br
.ti -1c
.RI "time_t \fBTIME\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBServerConfig\fP* \fBConfig\fP"
.PP
.SS "time_t \fBTIME\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
