users.cpp
NAME
users.cpp -
SYNOPSIS
#include 'inspircd_config.h'
#include 'channels.h'
#include 'connection.h'
#include 'users.h'
#include 'inspircd.h'
#include <stdio.h>
#include 'inspstring.h'
#include 'commands.h'
#include 'helperfuncs.h'
#include 'typedefs.h'
#include 'socketengine.h'
#include 'hashcomp.h'
#include 'message.h'
#include 'wildcard.h'
#include 'xline.h'
Functions
template<typename T> string ConvToStr (const T &in)
void AddOper (userrec *user)
void DeleteOper (userrec *user)
void kill_link (userrec *user, const char *r)
void kill_link_silent (userrec *user, const char *r)
void AddWhoWas (userrec *u)
void AddClient (int socket, char *host, int port, bool iscached, char *ip)
void FullConnectUser (userrec *user)
void ConnectUser (userrec *user)
userrec * ReHashNick (char *Old, char *New)
void force_nickchange (userrec *user, const char *newnick)
Variables
InspIRCd * ServerInstance
int WHOWAS_STALE
int WHOWAS_MAX
std::vector< Module * > modules
std::vector< ircd_module * > factory
std::vector< InspSocket * > module_sockets
int MODCOUNT
InspSocket * socket_ref [65535]
time_t TIME
userrec * fd_ref_table [65536]
ServerConfig * Config
user_hash clientlist
whowas_hash whowas
std::vector< userrec * > local_users
std::vector< userrec * > all_opers
Function Documentation
void AddClient (int socket, char * host, int port, bool iscached, char * ip)
Definition at line 524 of file users.cpp.
References SocketEngine::AddFd(), CC_ALLOW, ucrec::channel, ServerConfig::Classes, clientlist, ConvToStr(), DEBUG, ServerConfig::dns_timeout, FindServerNamePtr(), kill_link(), local_users, log(), matches_exception(), matches_zline(), InspIRCd::SE, ServerConfig::ServerName, ServerConfig::SoftLimit, TIME, ucrec::uc_modes, and X_ESTAB_CLIENT.
{
        string tempnick;
        char tn2[MAXBUF];
        user_hash::iterator iter;
        tempnick = ConvToStr(socket) + '-unknown';
        sprintf(tn2,'%lu-unknown',(unsigned long)socket);
        iter = clientlist.find(tempnick);
        // fix by brain.
        // as these nicknames are 'RFC impossible', we can be sure nobody is going to be
        // using one as a registered connection. As theyre per fd, we can also safely assume
        // that we wont have collisions. Therefore, if the nick exists in the list, its only
        // used by a dead socket, erase the iterator so that the new client may reclaim it.
        // this was probably the cause of 'server ignores me when i hammer it with reconnects'
        // issue in earlier alphas/betas
        if (iter != clientlist.end())
        {
                userrec* goner = iter->second;
                delete goner;
                clientlist.erase(iter);
        }
        /*
         * It is OK to access the value here this way since we know
         * it exists, we just created it above.
         *
         * At NO other time should you access a value in a map or a
         * hash_map this way.
         */
        clientlist[tempnick] = new userrec();
        log(DEBUG,'AddClient: %lu %s %d %s',(unsigned long)socket,host,port,ip);
        clientlist[tempnick]->fd = socket;
        strlcpy(clientlist[tempnick]->nick, tn2,NICKMAX);
        strlcpy(clientlist[tempnick]->host, host,160);
        strlcpy(clientlist[tempnick]->dhost, host,160);
        clientlist[tempnick]->server = (char*)FindServerNamePtr(Config->ServerName);
        strlcpy(clientlist[tempnick]->ident, 'unknown',IDENTMAX);
        clientlist[tempnick]->registered = 0;
        clientlist[tempnick]->signon = TIME + Config->dns_timeout;
        clientlist[tempnick]->lastping = 1;
        clientlist[tempnick]->port = port;
        strlcpy(clientlist[tempnick]->ip,ip,16);
        // set the registration timeout for this user
        unsigned long class_regtimeout = 90;
        int class_flood = 0;
        long class_threshold = 5;
        long class_sqmax = 262144; // 256kb
        long class_rqmax = 4096; // 4k
        for (ClassVector::iterator i = Config->Classes.begin(); i != Config->Classes.end(); i++)
        {
                if (match(clientlist[tempnick]->host,i->host) && (i->type == CC_ALLOW))
                {
                        class_regtimeout = (unsigned long)i->registration_timeout;
                        class_flood = i->flood;
                        clientlist[tempnick]->pingmax = i->pingtime;
                        class_threshold = i->threshold;
                        class_sqmax = i->sendqmax;
                        class_rqmax = i->recvqmax;
                        break;
                }
        }
        clientlist[tempnick]->nping = TIME+clientlist[tempnick]->pingmax + Config->dns_timeout;
        clientlist[tempnick]->timeout = TIME+class_regtimeout;
        clientlist[tempnick]->flood = class_flood;
        clientlist[tempnick]->threshold = class_threshold;
        clientlist[tempnick]->sendqmax = class_sqmax;
        clientlist[tempnick]->recvqmax = class_rqmax;
        ucrec a;
        a.channel = NULL;
        a.uc_modes = 0;
        for (int i = 0; i < MAXCHANS; i++)
                clientlist[tempnick]->chans.push_back(a);
        if (clientlist.size() > Config->SoftLimit)
        {
                kill_link(clientlist[tempnick],'No more connections allowed');
                return;
        }
        if (clientlist.size() >= MAXCLIENTS)
        {
                kill_link(clientlist[tempnick],'No more connections allowed');
                return;
        }
        // this is done as a safety check to keep the file descriptors within range of fd_ref_table.
        // its a pretty big but for the moment valid assumption:
        // file descriptors are handed out starting at 0, and are recycled as theyre freed.
        // therefore if there is ever an fd over 65535, 65536 clients must be connected to the
        // irc server at once (or the irc server otherwise initiating this many connections, files etc)
        // which for the time being is a physical impossibility (even the largest networks dont have more
        // than about 10,000 users on ONE server!)
        if ((unsigned)socket > 65534)
        {
                kill_link(clientlist[tempnick],'Server is full');
                return;
        }
        char* e = matches_exception(ip);
        if (!e)
        {
                char* r = matches_zline(ip);
                if (r)
                {
                        char reason[MAXBUF];
                        snprintf(reason,MAXBUF,'Z-Lined: %s',r);
                        kill_link(clientlist[tempnick],reason);
                        return;
                }
        }
        fd_ref_table[socket] = clientlist[tempnick];
        local_users.push_back(clientlist[tempnick]);
        ServerInstance->SE->AddFd(socket,true,X_ESTAB_CLIENT);
}
void AddOper (userrec * user)
Definition at line 330 of file users.cpp.
References all_opers, DEBUG, and log().
{
        log(DEBUG,'Oper added to optimization list');
        all_opers.push_back(user);
}
void AddWhoWas (userrec * u)
Definition at line 471 of file users.cpp.
References DEBUG, WhoWasUser::dhost, userrec::dhost, WhoWasUser::fullname, userrec::fullname, WhoWasUser::host, connection::host, WhoWasUser::ident, userrec::ident, log(), userrec::nick, WhoWasUser::nick, WhoWasUser::server, userrec::server, WhoWasUser::signon, connection::signon, TIME, whowas, WHOWAS_MAX, and WHOWAS_STALE.
Referenced by kill_link().
{
        whowas_hash::iterator iter = whowas.find(u->nick);
        WhoWasUser *a = new WhoWasUser();
        strlcpy(a->nick,u->nick,NICKMAX);
        strlcpy(a->ident,u->ident,IDENTMAX);
        strlcpy(a->dhost,u->dhost,160);
        strlcpy(a->host,u->host,160);
        strlcpy(a->fullname,u->fullname,MAXGECOS);
        strlcpy(a->server,u->server,256);
        a->signon = u->signon;
        /* MAX_WHOWAS: max number of /WHOWAS items
         * WHOWAS_STALE: number of hours before a WHOWAS item is marked as stale and
         * can be replaced by a newer one
         */
        if (iter == whowas.end())
        {
                if (whowas.size() >= (unsigned)WHOWAS_MAX)
                {
                        for (whowas_hash::iterator i = whowas.begin(); i != whowas.end(); i++)
                        {
                                // 3600 seconds in an hour ;)
                                if ((i->second->signon)<(TIME-(WHOWAS_STALE*3600)))
                                {
                                        // delete the old one
                                        if (i->second) delete i->second;
                                        // replace with new one
                                        i->second = a;
                                        log(DEBUG,'added WHOWAS entry, purged an old record');
                                        return;
                                }
                        }
                        // no space left and user doesnt exist. Don't leave ram in use!
                        log(DEBUG,'Not able to update whowas (list at WHOWAS_MAX entries and trying to add new?), freeing excess ram');
                        delete a;
                }
                else
                {
                        log(DEBUG,'added fresh WHOWAS entry');
                        whowas[a->nick] = a;
                }
        }
        else
        {
                log(DEBUG,'updated WHOWAS entry');
                if (iter->second) delete iter->second;
                iter->second = a;
        }
}
void ConnectUser (userrec * user)
Definition at line 731 of file users.cpp.
References userrec::dns_done, FullConnectUser(), and connection::registered.
{
        // dns is already done, things are fast. no need to wait for dns to complete just pass them straight on
        if ((user->dns_done) && (user->registered >= 3) && (AllModulesReportReady(user)))
        {
                FullConnectUser(user);
        }
}
template<typename T> string ConvToStr (const T & in) [inline]
Definition at line 56 of file users.cpp.
Referenced by AddClient().
{
        stringstream tmp;
        if (!(tmp << in)) return string();
        return tmp.str();
}
void DeleteOper (userrec * user)
Definition at line 336 of file users.cpp.
References all_opers, DEBUG, and log().
{
        for (std::vector<userrec*>::iterator a = all_opers.begin(); a < all_opers.end(); a++)
        {
                if (*a == user)
                {
                        log(DEBUG,'Oper removed from optimization list');
                        all_opers.erase(a);
                        return;
                }
        }
}
void force_nickchange (userrec * user, const char * newnick)
Definition at line 769 of file users.cpp.
References FOREACH_RESULT, kill_link(), matches_qline(), InspIRCd::Parser, connection::registered, InspIRCd::stats, and serverstats::statsCollisions.
Referenced by Server::ChangeUserNick().
{
        char nick[MAXBUF];
        int MOD_RESULT = 0;
        strcpy(nick,'');
        FOREACH_RESULT(OnUserPreNick(user,newnick));
        if (MOD_RESULT) {
                ServerInstance->stats->statsCollisions++;
                kill_link(user,'Nickname collision');
                return;
        }
        if (matches_qline(newnick))
        {
                ServerInstance->stats->statsCollisions++;
                kill_link(user,'Nickname collision');
                return;
        }
        if (user)
        {
                if (newnick)
                {
                        strncpy(nick,newnick,MAXBUF);
                }
                if (user->registered == 7)
                {
                        char* pars[1];
                        pars[0] = nick;
                        std::string cmd = 'NICK';
                        ServerInstance->Parser->CallHandler(cmd,pars,1,user);
                }
        }
}
void FullConnectUser (userrec * user)
Definition at line 647 of file users.cpp.
References DEBUG, connection::fd, FOREACH_MOD, connection::haspassed, connection::host, userrec::ident, connection::idle_lastmsg, connection::ip, kill_link(), kill_link_silent(), log(), matches_exception(), matches_gline(), matches_kline(), ServerConfig::Network, userrec::nick, connection::port, connection::registered, ServerConfig::ServerName, InspIRCd::stats, serverstats::statsConnects, TIME, WriteOpers(), and WriteServ().
Referenced by ConnectUser().
{
        ServerInstance->stats->statsConnects++;
        user->idle_lastmsg = TIME;
        log(DEBUG,'ConnectUser: %s',user->nick);
        if ((strcmp(Passwd(user),'')) && (!user->haspassed))
        {
                kill_link(user,'Invalid password');
                return;
        }
        if (IsDenied(user))
        {
                kill_link(user,'Unauthorised connection');
                return;
        }
        char match_against[MAXBUF];
        snprintf(match_against,MAXBUF,'%s@%s',user->ident,user->host);
        char* e = matches_exception(match_against);
        if (!e)
        {
                char* r = matches_gline(match_against);
                if (r)
                {
                        char reason[MAXBUF];
                        snprintf(reason,MAXBUF,'G-Lined: %s',r);
                        kill_link_silent(user,reason);
                        return;
                }
                r = matches_kline(user->host);
                if (r)
                {
                        char reason[MAXBUF];
                        snprintf(reason,MAXBUF,'K-Lined: %s',r);
                        kill_link_silent(user,reason);
                        return;
                }
        }
        WriteServ(user->fd,'NOTICE Auth :Welcome to \002%s\002!',Config->Network);
        WriteServ(user->fd,'001 %s :Welcome to the %s IRC Network %s!%s@%s',user->nick,Config->Network,user->nick,user->ident,user->host);
        WriteServ(user->fd,'002 %s :Your host is %s, running version %s',user->nick,Config->ServerName,VERSION);
        WriteServ(user->fd,'003 %s :This server was created %s %s',user->nick,__TIME__,__DATE__);
        WriteServ(user->fd,'004 %s %s %s iowghraAsORVSxNCWqBzvdHtGI lvhopsmntikrRcaqOALQbSeKVfHGCuzN',user->nick,Config->ServerName,VERSION);
        // the neatest way to construct the initial 005 numeric, considering the number of configure constants to go in it...
        std::stringstream v;
        v << 'WALLCHOPS MODES=13 CHANTYPES=# PREFIX=(ohv)@%+ MAP SAFELIST MAXCHANNELS=' << MAXCHANS;
        v << ' MAXBANS=60 NICKLEN=' << NICKMAX;
        v << ' TOPICLEN=' << MAXTOPIC << ' KICKLEN=' << MAXKICK << ' MAXTARGETS=20 AWAYLEN=' << MAXAWAY << ' CHANMODES=ohvb,k,l,psmnti NETWORK=';
        v << Config->Network;
        std::string data005 = v.str();
        FOREACH_MOD On005Numeric(data005);
        // anfl @ #ratbox, efnet reminded me that according to the RFC this cant contain more than 13 tokens per line...
        // so i'd better split it :)
        std::stringstream out(data005);
        std::string token = '';
        std::string line5 = '';
        int token_counter = 0;
        while (!out.eof())
        {
                out >> token;
                line5 = line5 + token + ' ';
                token_counter++;
                if ((token_counter >= 13) || (out.eof() == true))
                {
                        WriteServ(user->fd,'005 %s %s:are supported by this server',user->nick,line5.c_str());
                        line5 = '';
                        token_counter = 0;
                }
        }
        ShowMOTD(user);
        // fix 3 by brain, move registered = 7 below these so that spurious modes and host changes dont go out
        // onto the network and produce 'fake direction'
        FOREACH_MOD OnUserConnect(user);
        FOREACH_MOD OnGlobalConnect(user);
        user->registered = 7;
        WriteOpers('*** Client connecting on port %lu: %s!%s@%s [%s]',(unsigned long)user->port,user->nick,user->ident,user->host,user->ip);
}
void kill_link (userrec * user, const char * r)
Definition at line 349 of file users.cpp.
References AddWhoWas(), clientlist, userrec::CloseSocket(), DEBUG, SocketEngine::DelFd(), connection::fd, userrec::FlushWriteBuf(), FOREACH_MOD, ServerConfig::GetIOHook(), connection::host, userrec::ident, local_users, log(), userrec::nick, Module::OnRawSocketClose(), connection::port, connection::registered, InspIRCd::SE, Write(), WriteCommonExcept(), and WriteOpers().
Referenced by AddClient(), force_nickchange(), FullConnectUser(), Server::PseudoToUser(), and Server::QuitUser().
{
        user_hash::iterator iter = clientlist.find(user->nick);
        char reason[MAXBUF];
        strncpy(reason,r,MAXBUF);
        if (strlen(reason)>MAXQUIT)
        {
                reason[MAXQUIT-1] = '\0';
        }
        log(DEBUG,'kill_link: %s '%s'',user->nick,reason);
        Write(user->fd,'ERROR :Closing link (%s@%s) [%s]',user->ident,user->host,reason);
        log(DEBUG,'closing fd %lu',(unsigned long)user->fd);
        if (user->registered == 7) {
                FOREACH_MOD OnUserQuit(user,reason);
                WriteCommonExcept(user,'QUIT :%s',reason);
        }
        user->FlushWriteBuf();
        FOREACH_MOD OnUserDisconnect(user);
        if (user->fd > -1)
        {
                if (Config->GetIOHook(user->port))
                {
                        Config->GetIOHook(user->port)->OnRawSocketClose(user->fd);
                }
                ServerInstance->SE->DelFd(user->fd);
                user->CloseSocket();
        }
        // this must come before the WriteOpers so that it doesnt try to fill their buffer with anything
        // if they were an oper with +s.
        if (user->registered == 7) {
                purge_empty_chans(user);
                // fix by brain: only show local quits because we only show local connects (it just makes SENSE)
                if (user->fd > -1)
                        WriteOpers('*** Client exiting: %s!%s@%s [%s]',user->nick,user->ident,user->host,reason);
                AddWhoWas(user);
        }
        if (iter != clientlist.end())
        {
                log(DEBUG,'deleting user hash value %lu',(unsigned long)user);
                if (user->fd > -1)
                {
                        fd_ref_table[user->fd] = NULL;
                        if (find(local_users.begin(),local_users.end(),user) != local_users.end())
                        {
                                local_users.erase(find(local_users.begin(),local_users.end(),user));
                                log(DEBUG,'Delete local user');
                        }
                }
                clientlist.erase(iter);
        }
        delete user;
}
void kill_link_silent (userrec * user, const char * r)
Definition at line 412 of file users.cpp.
References clientlist, userrec::CloseSocket(), DEBUG, SocketEngine::DelFd(), connection::fd, userrec::FlushWriteBuf(), FOREACH_MOD, ServerConfig::GetIOHook(), connection::host, userrec::ident, local_users, log(), userrec::nick, Module::OnRawSocketClose(), connection::port, connection::registered, InspIRCd::SE, Write(), and WriteCommonExcept().
Referenced by FullConnectUser().
{
        user_hash::iterator iter = clientlist.find(user->nick);
        char reason[MAXBUF];
        strncpy(reason,r,MAXBUF);
        if (strlen(reason)>MAXQUIT)
        {
                reason[MAXQUIT-1] = '\0';
        }
        log(DEBUG,'kill_link: %s '%s'',user->nick,reason);
        Write(user->fd,'ERROR :Closing link (%s@%s) [%s]',user->ident,user->host,reason);
        log(DEBUG,'closing fd %lu',(unsigned long)user->fd);
        user->FlushWriteBuf();
        if (user->registered == 7) {
                FOREACH_MOD OnUserQuit(user,reason);
                WriteCommonExcept(user,'QUIT :%s',reason);
        }
        FOREACH_MOD OnUserDisconnect(user);
        if (user->fd > -1)
        {
                if (Config->GetIOHook(user->port))
                {
                        Config->GetIOHook(user->port)->OnRawSocketClose(user->fd);
                }
                ServerInstance->SE->DelFd(user->fd);
                user->CloseSocket();
        }
        if (user->registered == 7) {
                purge_empty_chans(user);
        }
        if (iter != clientlist.end())
        {
                log(DEBUG,'deleting user hash value %lu',(unsigned long)user);
                if (user->fd > -1)
                {
                        fd_ref_table[user->fd] = NULL;
                        if (find(local_users.begin(),local_users.end(),user) != local_users.end())
                        {
                                log(DEBUG,'Delete local user');
                                local_users.erase(find(local_users.begin(),local_users.end(),user));
                        }
                }
                clientlist.erase(iter);
        }
        delete user;
}
userrec* ReHashNick (char * Old, char * New)
Definition at line 743 of file users.cpp.
References clientlist, DEBUG, and log().
{
        //user_hash::iterator newnick;
        user_hash::iterator oldnick = clientlist.find(Old);
        log(DEBUG,'ReHashNick: %s %s',Old,New);
        if (!strcasecmp(Old,New))
        {
                log(DEBUG,'old nick is new nick, skipping');
                return oldnick->second;
        }
        if (oldnick == clientlist.end()) return NULL; /* doesnt exist */
        log(DEBUG,'ReHashNick: Found hashed nick %s',Old);
        userrec* olduser = oldnick->second;
        clientlist[New] = olduser;
        clientlist.erase(oldnick);
        log(DEBUG,'ReHashNick: Nick rehashed as %s',New);
        return clientlist[New];
}
Variable Documentation
std::vector<userrec*> all_opers
Definition at line 54 of file users.cpp.
Referenced by AddOper(), and DeleteOper().
user_hash clientlist
ServerConfig* Config
std::vector<ircd_module*> factory
userrec* fd_ref_table[65536]
std::vector<userrec*> local_users
Definition at line 52 of file users.cpp.
Referenced by AddClient(), kill_link(), and kill_link_silent().
int MODCOUNT
std::vector<InspSocket*> module_sockets
std::vector<Module*> modules
InspIRCd* ServerInstance
InspSocket* socket_ref[65535]
Definition at line 43 of file socket.cpp.
time_t TIME
whowas_hash whowas
Referenced by AddWhoWas().
int WHOWAS_MAX
int WHOWAS_STALE
Author
Generated automatically by Doxygen for InspIRCd from the source code.