.TH "users.cpp" 3 "12 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
users.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'channels.h'\fP
.br
\fC#include 'users.h'\fP
.br
\fC#include 'inspircd.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include 'inspstring.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "std::stringstream \fBconfig_f\fP"
.br
.ti -1c
.RI "time_t \fBTIME\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::stringstream \fBconfig_f\fP"
.PP
Definition at line 24 of file users.cpp.
.SS "time_t \fBTIME\fP"
.PP
Definition at line 26 of file users.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
