.TH "Version" 3 "24 May 2005" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version \- Holds a module's Version information The four members (set by the constructor only) indicate details as to the version number of a module.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <modules.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersion\fP (int major, int minor, int revision, int build, int flags)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBMajor\fP"
.br
.ti -1c
.RI "const int \fBMinor\fP"
.br
.ti -1c
.RI "const int \fBRevision\fP"
.br
.ti -1c
.RI "const int \fBBuild\fP"
.br
.ti -1c
.RI "const int \fBFlags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds a module's Version information The four members (set by the constructor only) indicate details as to the version number of a module. 

A class of type Version is returned by the GetVersion method of the \fBModule\fP class. 
.PP
Definition at line 111 of file modules.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Version::Version (int major, int minor, int revision, int build, int flags)"
.PP
Definition at line 243 of file modules.cpp.
.PP
.nf
243 : Major(major), Minor(minor), Revision(revision), Build(build), Flags(flags) { };
.fi
.SH "Member Data Documentation"
.PP 
.SS "const int \fBVersion::Build\fP"
.PP
Definition at line 114 of file modules.h.
.SS "const int \fBVersion::Flags\fP"
.PP
Definition at line 114 of file modules.h.
.SS "const int \fBVersion::Major\fP"
.PP
Definition at line 114 of file modules.h.
.SS "const int \fBVersion::Minor\fP"
.PP
Definition at line 114 of file modules.h.
.SS "const int \fBVersion::Revision\fP"
.PP
Definition at line 114 of file modules.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
