.TH "WhoWasUser" 3 "15 Dec 2005" "Version 1.0Betareleases" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WhoWasUser \- A lightweight userrec used by WHOWAS.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <users.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBnick\fP [NICKMAX]"
.br
.ti -1c
.RI "char \fBident\fP [IDENTMAX+1]"
.br
.ti -1c
.RI "char \fBdhost\fP [160]"
.br
.ti -1c
.RI "char \fBhost\fP [160]"
.br
.ti -1c
.RI "char \fBfullname\fP [MAXGECOS+1]"
.br
.ti -1c
.RI "char \fBserver\fP [256]"
.br
.ti -1c
.RI "time_t \fBsignon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A lightweight userrec used by WHOWAS. 
.PP
Definition at line 332 of file users.h.
.SH "Member Data Documentation"
.PP 
.SS "char \fBWhoWasUser::dhost\fP[160]"
.PP
Definition at line 337 of file users.h.
.SS "char \fBWhoWasUser::fullname\fP[MAXGECOS+1]"
.PP
Definition at line 339 of file users.h.
.SS "char \fBWhoWasUser::host\fP[160]"
.PP
Definition at line 338 of file users.h.
.SS "char \fBWhoWasUser::ident\fP[IDENTMAX+1]"
.PP
Definition at line 336 of file users.h.
.SS "char \fBWhoWasUser::nick\fP[NICKMAX]"
.PP
Definition at line 335 of file users.h.
.SS "char \fBWhoWasUser::server\fP[256]"
.PP
Definition at line 340 of file users.h.
.SS "time_t \fBWhoWasUser::signon\fP"
.PP
Definition at line 341 of file users.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
