xline.h
NAME
xline.h -
SYNOPSIS
#include <typeinfo>
#include <iostream>
#include <string>
#include <deque>
#include <sstream>
#include <vector>
#include 'users.h'
#include 'channels.h'
Compounds
class ELine
class GLine
GLine class.
class KLine
KLine class.
class QLine
QLine class.
class XLine
XLine is the base class for ban lines such as G lines and K lines.
class ZLine
ZLine class.
Functions
void read_xline_defaults ()
void add_gline (long duration, const char *source, const char *reason, const char *hostmask)
void add_qline (long duration, const char *source, const char *reason, const char *nickname)
void add_zline (long duration, const char *source, const char *reason, const char *ipaddr)
void add_kline (long duration, const char *source, const char *reason, const char *hostmask)
void add_eline (long duration, const char *source, const char *reason, const char *hostmask)
bool del_gline (const char *hostmask)
bool del_qline (const char *nickname)
bool del_zline (const char *ipaddr)
bool del_kline (const char *hostmask)
bool del_eline (const char *hostmask)
char * matches_qline (const char *nick)
char * matches_gline (const char *host)
char * matches_zline (const char *ipaddr)
char * matches_kline (const char *host)
char * matches_exception (const char *host)
void expire_lines ()
void apply_lines ()
void stats_k (userrec *user)
void stats_g (userrec *user)
void stats_q (userrec *user)
void stats_z (userrec *user)
void stats_e (userrec *user)
void gline_set_creation_time (char *host, time_t create_time)
void qline_set_creation_time (char *nick, time_t create_time)
void zline_set_creation_time (char *ip, time_t create_time)
bool zline_make_global (const char *ipaddr)
bool qline_make_global (const char *nickname)
void sync_xlines (serverrec *serv, char *tcp_host)
Function Documentation
void add_eline (long duration, const char * source, const char * reason, const char * hostmask)
Referenced by Server::AddELine().
void add_gline (long duration, const char * source, const char * reason, const char * hostmask)
Referenced by Server::AddGLine().
void add_kline (long duration, const char * source, const char * reason, const char * hostmask)
Referenced by Server::AddKLine().
void add_qline (long duration, const char * source, const char * reason, const char * nickname)
Referenced by Server::AddQLine().
void add_zline (long duration, const char * source, const char * reason, const char * ipaddr)
Referenced by Server::AddZLine().
void apply_lines ()
bool del_eline (const char * hostmask)
Referenced by Server::DelELine().
bool del_gline (const char * hostmask)
Referenced by Server::DelGLine().
bool del_kline (const char * hostmask)
Referenced by Server::DelKLine().
bool del_qline (const char * nickname)
Referenced by Server::DelQLine().
bool del_zline (const char * ipaddr)
Referenced by Server::DelZLine().
void expire_lines ()
void gline_set_creation_time (char * host, time_t create_time)
char* matches_exception (const char * host)
char* matches_gline (const char * host)
char* matches_kline (const char * host)
char* matches_qline (const char * nick)
char* matches_zline (const char * ipaddr)
bool qline_make_global (const char * nickname)
void qline_set_creation_time (char * nick, time_t create_time)
void read_xline_defaults ()
void stats_e (userrec * user)
void stats_g (userrec * user)
void stats_k (userrec * user)
void stats_q (userrec * user)
void stats_z (userrec * user)
void sync_xlines (serverrec * serv, char * tcp_host)
bool zline_make_global (const char * ipaddr)
void zline_set_creation_time (char * ip, time_t create_time)
Author
Generated automatically by Doxygen for InspIRCd from the source code.