.TH "channels.h" 3 "30 Apr 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
channels.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'base.h'\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Compounds"

.in +1c
.ti -1c
.RI "class \fBBanItem\fP"
.br
.RI "\fIA subclass of \fBHostItem\fP designed to hold channel bans (+b).\fP"
.ti -1c
.RI "class \fBchanrec\fP"
.br
.RI "\fIHolds all relevent information for a channel.\fP"
.ti -1c
.RI "class \fBExemptItem\fP"
.br
.RI "\fIA subclass of \fBHostItem\fP designed to hold channel exempts (+e).\fP"
.ti -1c
.RI "class \fBHostItem\fP"
.br
.RI "\fIHolds an entry for a ban list, exemption list, or invite list.\fP"
.ti -1c
.RI "class \fBInviteItem\fP"
.br
.RI "\fIA subclass of \fBHostItem\fP designed to hold channel invites (+I).\fP"
.ti -1c
.RI "class \fBModeParameter\fP"
.br
.RI "\fIHolds a custom parameter to a module-defined channel mode e.g.\fP"
.ti -1c
.RI "class \fBucrec\fP"
.br
.RI "\fIHolds a user's modes on a channel This class associates a users privilages with a channel by creating a pointer link between a userrec and chanrec class.\fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBUCMODE_OP\fP   1"
.br
.ti -1c
.RI "#define \fBUCMODE_VOICE\fP   2"
.br
.ti -1c
.RI "#define \fBUCMODE_HOP\fP   4"
.br
.ti -1c
.RI "#define \fBUCMODE_PROTECT\fP   8"
.br
.ti -1c
.RI "#define \fBUCMODE_FOUNDER\fP   16"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBBanItem\fP > \fBBanList\fP"
.br
.RI "\fIHolds a complete ban list.\fP"
.ti -1c
.RI "typedef std::vector< \fBExemptItem\fP > \fBExemptList\fP"
.br
.RI "\fIHolds a complete exempt list.\fP"
.ti -1c
.RI "typedef std::vector< \fBInviteItem\fP > \fBInviteList\fP"
.br
.RI "\fIHolds a complete invite list.\fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define UCMODE_FOUNDER   16"
.PP
Definition at line 184 of file channels.h.
.SS "#define UCMODE_HOP   4"
.PP
Definition at line 182 of file channels.h.
.SS "#define UCMODE_OP   1"
.PP
Definition at line 180 of file channels.h.
.SS "#define UCMODE_PROTECT   8"
.PP
Definition at line 183 of file channels.h.
.SS "#define UCMODE_VOICE   2"
.PP
Definition at line 181 of file channels.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<\fBBanItem\fP> BanList"
.PP
Holds a complete ban list.Definition at line 69 of file channels.h.
.SS "typedef std::vector<\fBExemptItem\fP> ExemptList"
.PP
Holds a complete exempt list.Definition at line 73 of file channels.h.
.SS "typedef std::vector<\fBInviteItem\fP> InviteList"
.PP
Holds a complete invite list.Definition at line 77 of file channels.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
