.TH "ExemptItem" 3 "30 Apr 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExemptItem \- A subclass of \fBHostItem\fP designed to hold channel exempts (+e). 

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <channels.h>\fP
.PP
Inherits \fBHostItem\fP.
.PP
.SH "Detailed Description"
.PP 
A subclass of \fBHostItem\fP designed to hold channel exempts (+e).Definition at line 42 of file channels.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
