.TH "ExtMode" 3 "30 Apr 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtMode \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBclassbase\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtMode\fP (char mc, int ty, bool oper, int p_on, int p_off)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBmodechar\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBparams_when_on\fP"
.br
.ti -1c
.RI "int \fBparams_when_off\fP"
.br
.ti -1c
.RI "bool \fBneedsoper\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExtMode::ExtMode (char mc, int ty, bool oper, int p_on, int p_off)\fC [inline]\fP"
.PP
Definition at line 29 of file modules.cpp.
.PP
.nf
29 : modechar(mc), type(ty), needsoper(oper), params_when_on(p_on), params_when_off(p_off) { };
.fi
.SH "Member Data Documentation"
.PP 
.SS "char ExtMode::modechar"
.PP
Definition at line 24 of file modules.cpp.
.SS "bool ExtMode::needsoper"
.PP
Definition at line 28 of file modules.cpp.
.SS "int ExtMode::params_when_off"
.PP
Definition at line 27 of file modules.cpp.
.SS "int ExtMode::params_when_on"
.PP
Definition at line 26 of file modules.cpp.
.SS "int ExtMode::type"
.PP
Definition at line 25 of file modules.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
