.TH "HostItem" 3 "30 Apr 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HostItem \- Holds an entry for a ban list, exemption list, or invite list. 

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <channels.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
Inherited by \fBBanItem\fP, \fBExemptItem\fP, and \fBInviteItem\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHostItem\fP ()"
.br
.ti -1c
.RI "virtual \fB~HostItem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBset_time\fP"
.br
.ti -1c
.RI "char \fBset_by\fP [NICKMAX]"
.br
.ti -1c
.RI "char \fBdata\fP [MAXBUF]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds an entry for a ban list, exemption list, or invite list.

This class contains a single element in a channel list, such as a banlist. 
.PP
Definition at line 18 of file channels.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HostItem::HostItem ()\fC [inline]\fP"
.PP
Definition at line 25 of file channels.h.
.PP
.nf
25 { /* stub */ }
.fi
.SS "virtual HostItem::~HostItem ()\fC [inline, virtual]\fP"
.PP
Definition at line 26 of file channels.h.
.PP
.nf
26 { /* stub */ }
.fi
.SH "Member Data Documentation"
.PP 
.SS "char HostItem::data[MAXBUF]"
.PP
Definition at line 23 of file channels.h.
.SS "char HostItem::set_by[NICKMAX]"
.PP
Definition at line 22 of file channels.h.
.SS "time_t HostItem::set_time"
.PP
Definition at line 21 of file channels.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
