.TH "packet" 3 "30 Apr 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet \- Class packet is deprecated. 

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <connection.h>\fP
.PP
Inherits \fBclassbase\fP.
.PP
.SH "Detailed Description"
.PP 
Class packet is deprecated.

This declaration is preserved here to maintain documentation only. 
.PP
Definition at line 155 of file connection.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
