.TH "servers.cpp" 3 "30 Apr 2004" "InspIRCd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
servers.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inspircd_config.h'\fP
.br
\fC#include 'servers.h'\fP
.br
\fC#include 'inspircd.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <map>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for InspIRCd from the source code.
