/* Auto generated by configure, do not modify! */
#ifndef __CONFIGURATION_AUTO__
#define __CONFIGURATION_AUTO__

#define CONFIG_USE_IOCP 1

#define CONFIG_FILE "../conf/inspircd.conf"
#define MOD_PATH "../modules"
#define MAX_DESCRIPTORS 1024
#define MAXCLIENTS 1024
#define MAXCLIENTS_S "1024"
#define SOMAXCONN_S "128"
#define NICKMAX 32
#define CHANMAX 65
#define MAXMODES 20
#define IDENTMAX 12
#define MAXQUIT 255
#define MAXTOPIC 307
#define MAXKICK 255
#define MAXGECOS 128
#define MAXAWAY 200
#define LIBRARYDIR "../lib"
#define VERSION "InspIRCd-1.1.7+Mozarella"
#define REVISION "7042"
#define SUPPORT_IP6LINKS 1
#define SYSTEM "Windows 5.2.3790 Service Pack 1"
#define MAXBUF 514

#include "inspircd_win32wrapper.h"

#endif

