#!/usr/bin/env perl
#
# InspIRCd -- Internet Relay Chat Daemon
#
#   Copyright (C) 2020-2021, 2024 Sadie Powell <sadie@sadiepowell.dev>
#
# This file is part of InspIRCd.  InspIRCd is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


use v5.26.0;
use strict;
use warnings FATAL => qw(all);

use CommonMark              ();
use File::Basename          qw(basename dirname);
use File::Spec::Functions   qw(catdir catfile rel2abs);
use FindBin                 qw($RealDir);
use HTML::FormatText        ();
use HTML::TreeBuilder       ();
use Text::Sentence          qw(split_sentences);
use YAML                    qw(LoadFile);

use constant {
	CC_BOLD      => -t STDOUT ? "\e[1m"    : '',
	CC_RESET     => -t STDOUT ? "\e[0m"    : '',
	CC_UNDERLINE => -t STDOUT ? "\e[4m"    : '',
	CC_RED       => -t STDOUT ? "\e[1;31m" : '',
	CC_GREEN     => -t STDOUT ? "\e[1;32m" : '',
};

sub execute(@) {
	say "${\CC_BOLD}\$${\CC_RESET} @_";
	return system @_;
}

sub print_error {
	print STDERR "${\CC_RED}Error:${\CC_RESET} ";
	for my $line (@_) {
		say STDERR $line;
	}
	exit 1;
}

sub major_version {
	my $path = catfile(dirname($RealDir), 'src', 'cmake', 'version.cmake');
	open(my $vh, '<', $path) or print_error "unable to read $path: $!";
	while (my $line = <$vh>) {
		if ($line =~ /\bset\(VERSION_MAJOR\s+(.+?)\)/) {
			close($vh);
			return $1;
		}
	}
	close($vh);
	print_error "unable to find the InspIRCd version: $path.";
}

unless (scalar @ARGV) {
	say STDERR "${\CC_GREEN}Usage:${\CC_RESET} $0 <${\CC_UNDERLINE}DOCS-SITE${\CC_RESET}>";
	exit 1;
}

my $docdir = rel2abs catdir $ARGV[0], 'docs', major_version(), 'modules';
print_error "unable to find the module directory at $docdir!" unless -d $docdir;

my @updated;
my $root = dirname $RealDir;
for my $module (<$root/modules/extra/*.cpp>, <$root/modules/*.cpp>, <$root/modules/*/main.cpp>) {
	my $module_name = ($module =~ /main\.cpp$/) ? basename(dirname($module)) : basename($module, '.cpp');
	print_error "unable to extract module name from $module!" unless $module_name;

	my $docfile = catfile $docdir, "$module_name.yml";
	print_error "unable to find the module documentation at $docfile!" unless -f $docfile;

	my ($docdata, undef, undef) = LoadFile($docfile) or print_error "unable to read from $docfile: $!";
	print_error "unable to find the module description in $docfile!" unless $docdata->{description};

	my $docraw = $docdata->{description} =~ s/(?:^This module |\{\{\s*[a-z_]+\s*\}\})//gr;
	my $docrendered = CommonMark->markdown_to_html(ucfirst $docraw);
	my $docplain = HTML::FormatText->new(leftmargin => 0, rightmargin => ~0)->format(HTML::TreeBuilder->new->parse($docrendered));

	my $description = (split_sentences $docplain)[0] =~ s/"/\\"/gr;
	chomp($description);

	open(my $mih, $module) or print_error "unable to read from $module: $!";
	my @lines;
	for my $line (<$mih>) {
		chomp $line;
		if ($line =~ /^(\t+:\s+Module\([^,]+,\s+")[^"]+("\))$/) {
			push @lines, join '', $1, $description, $2;
			push @updated, $module;
		} else {
			push @lines, $line;
		}
	}
	close $mih;

	open(my $moh, '>', $module) or print_error "unable to write to $module: $!";
	for my $line (@lines) {
		say $moh $line;
	}
	close $moh;
}

if ($ENV{MKDESCRIPTIONS_COMMIT} // 0) {
	execute 'git', 'commit',
		'--author', 'InspIRCd Robot <noreply@inspircd.org>',
		'--message', 'Update module descriptions.',
		'--', @updated;
}
