# Insp Makefile :p
#
#
#

CC = im a cheezeball

SRC_1 = inspircd.cpp inspircd_util.cpp inspircd_io.cpp
SRC_2 = dynamic.cpp users.cpp modules.cpp wildcard.cpp

SRC = $(SRC_1) $(SRC_2)
OBJS = $(SRC:.cpp=.o)

CXXFLAGS = -I$../../include ${FLAGS}

all: inspircd

inspircd: $(OBJS)
        $(CXX) -rdynamic $^ -o $@ $(LDLIBS)

