name: clandestine 
base: core20 
version: '3.15.0' 
summary: Fork of the InspIRCd 3.x code base, inspired by RatBox and Nefarious
description: |
  Fork of the InspIRCd 3.x code base, inspired by RatBox and Nefarious. It has it's own services, 
  which is a fork of the Anope source tree.

grade: devel 
confinement: devmode 

apps:
  ircd:
    command: ircd
  servicesd: 
    command: servicesd

parts:
  clandestine:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    source: . 
    build-packages:
      - libmysqlclient-dev
      - libutfcpp-dev
      - libmaxminddb-dev
      - libqrencode-dev
      - libpcre2-dev
      - libre2-dev
      - libhttp-parser-dev
      - libxcrypt-source
      - libsqlite3-dev
      - libgnutls28-dev
      - libmbedtls-dev 
      - libssl-dev
      - libargon2-dev
      - libpq-dev
      - libldap-dev
