name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install python3-pip
      run: sudo apt update && sudo apt -y install python3-pip
    - name: install conan
      run: pip3 install conan
    - name: conan profile
      run: conan profile detect --force
    - name: conan install vendored dependencies
      run: conan install . --output-folder=build/ --build=missing -s compiler.cppstd=11
    - name: cmake init 
      run: cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
      working-directory: ./build
    - name: make & install
      run: sudo make DESTDIR=./dist install
      working-directory: ./build
